### ISSUE TITLE
No response messages - error 403 - AuthenticationTypeDisabled

### ISSUE THREAD

**Issue by AxelQSam** [microsoft/sample-app-aoai-chatGPT#1000]
**Describe the bug**
No chat answers are given. Have been working before. Only given an error 403 message (both live and locally), shown below:
 
```
There was an error generating a response. Chat history can't be saved at this time. Error code: 403 - {'error': {'code': 'AuthenticationTypeDisabled', 'message': 'Key based authentication is disabled for this resource.'}}
```
 
 
**To Reproduce**
1. Run `$ ./start.sh`
2. Click on the provided link
3. Enter prompt
4. Receive error message
 
**Expected behavior**
I expect to receive a chat answer.
 
**Configuration: Please provide the following**
 
- Using 'gpt-35-turbo-16k, version 0613'
- Chat history is enabled
- Using data from Azure AI Search
 
Startup command and runtime configuration is shown below:
 
```
{
  "runtime": "PYTHON|3.11",
  "startupCommand": "python3 -m gunicorn app:app"
}
```
has context menu

**Comment by abhahn** [comment]
Hi @AxelQSam , based on the error message, it looks like one of your configured resources (either Azure Open AI or Azure Search) no longer supports key-based access.  Can you share the stack trace of the application failure so I can make recommendations for your RBAC setup to resolve the problem?
