### ISSUE TITLE
frontend_settings shows auth_enabled as false when you have entra ID configured

### ISSUE THREAD

**Issue by minhvu10** [microsoft/sample-app-aoai-chatGPT#1001]
![image](https://github.com/user-attachments/assets/2702050e-d6da-4f48-8445-d0e2c7632607)

**Comment by abhahn** [comment]
Hi @minhvu10 , just to clarify about the settings -- you will need to explicitly set `AUTH_ENABLED=true` in your app settings if you have already configured your identity provider.  Let me know if this is helpful, or if there's something I'm missing.

**Comment by minhvu10** [comment]
![image](https://github.com/user-attachments/assets/de6bb5ea-1d39-4f27-8beb-b2e0525aad75)
still has error.


If you deploy a new web app using the studio you'll get this error. may be something in the codebase that changed recently because this issue wasn't present 1 month ago and I didn't need to set auth_enabled=TRUE

![image](https://github.com/user-attachments/assets/e8ca6c1d-db88-4f03-af4e-7c7d2f00e757)

this used to populate with microsoft graph user.read and the apps user_impersonation. now it does not populate when you deploy a new app in AOAI Studio
