### ISSUE TITLE
Permissions required for connecting an endpoint to the frontend

### ISSUE THREAD

**Issue by brainlie** [microsoft/sample-app-aoai-chatGPT#1006]
**Describe the bug**
I have created an endpoint using azure ai studio promptflow, deploying it as an endpoint. After connecting the endpoint to the frontend using environment variables, I am getting an error on the chatbot response: "Execution failure in 'search_question_from_indexed_docs': (Exception) Exception occured in search_function_construction." 

![Screenshot 2024-07-15 at 4 40 11 PM](https://github.com/user-attachments/assets/38042672-80a8-4811-bdf7-0aa0245abf37)

These are my environment variables for my webapp
![Screenshot 2024-07-15 at 4 41 14 PM](https://github.com/user-attachments/assets/198b107d-8c9b-4337-ac28-85df65284d7d)

Is this related to identities? Or anything to do with CORS?

**Comment by wheatsnackbread** [comment]
Have you double-checked that USE_PROMPTFLOW is set to TRUE, and that AZURE_OPENAI_STREAM is set to FALSE?
