### ISSUE TITLE
azd up is asking for authClientId

### ISSUE THREAD

**Issue by DuboisABB** [microsoft/sample-app-aoai-chatGPT#1020]
**Describe the bug**
azd up is asking me for authClientId. I have no idea what to enter. Aren't the deployment scripts supposed to create that automatically? It seems related to me trying to use existing resources. See below. I don't see this question if I leave my .env file empty.

**To Reproduce**
azd auth login
azd env new
I'm trying to reuse AI search and OpenAI from another application in the same subscription so I added these variables to my .env file:
AZURE_OPENAI_MODEL="gpt-4-turbo"
AZURE_OPENAI_RESOURCE="cog-se-trnz2cbjn4ofs"
AZURE_OPENAI_RESOURCE_GROUP="BOCHAT-RG"
AZURE_OPENAI_SKU_NAME="S0"
AZURE_SEARCH_SERVICE="gptkb-trnz2cbjn4ofs"
AZURE_SEARCH_SERVICE_RESOURCE_GROUP="BOCHAT-RG"
AZURE_SEARCH_SKU_NAME="standard"

I'm also adding this variable because I'm interested in that feature:
AZURE_COSMOSDB_ENABLE_FEEDBACK="true"

Then simply:
azd up

It asks me for the subscription to use. Then it asks me for location. And then the weird authClientId:

PS C:\Programming\sample-app-aoai-chatGPT> azd up
? Select an Azure Subscription to use:  6. ABB-WE-ACE-DEV-xxxxxxxx (25b08136-92b0-43a2-a312-xxxxxxxxxx)
? Select an Azure location to use: 44. (US) East US (eastus)
? Enter a value for the 'authClientId' infrastructure parameter:

**Expected behavior**
Complete deployment without asking me for this.

**Comment by Manoj18kumar** [comment]
I'm also using existing resource and deploy using azd up ,asking same authClientId i don't want to enter give solution

**Comment by DuboisABB** [comment]
Sorry I can't recall how I fixed this but I don't have this issue anymore.

**Comment by Manoj18kumar** [comment]
We deployed initially by clicking on deploy  azure now I codespec want to
update app  using  azs up and asking authclientId don't know from where I
can get

**Comment by meharvansingh** [comment]
Does anybody have a solution? I'm getting the same thing with the same steps when trying to deploy above.
