### ISSUE TITLE
Unable to deploy the project with chat history from the CLI / via azd?

### ISSUE THREAD

**Issue by FrancoisNoyez** [microsoft/sample-app-aoai-chatGPT#1035]
Hi everyone,

I've been trying to deploy a WebApp via this project, for now with the version of the code associated to commit 16be120e of the 2024-03-16, via the console (so, using the azd tool).
After successfully deploying it, **I realized that the history feature does not seem to be activated**.

After investigating that (logging via ssh into the server hosting the backend, via the web interface providing this service), I realized that this may be **caused by the absence of the env variables related to the definition of the COSMOS db** (ex: 'AZURE_COSMOSDB_ACCOUNT'). At least it does not appear in the result of the 'env' command, and when I perform the API call with the '/history/ensure' path, I get the answer "CosmosDB is not configured", which suggests that this env variable does not exist from the point of view of the app either.
But **this env variable is indeed defined in my local .env file associated to the azd env that I'm using for that project**. So when I run the code on my computer, then everything works fine, and I do have access to the history functionality.
Something that I noticed is that this .env file is not packaged together with the rest of the files / folders, when running the 'azd package' command, which explains why this info is not available for the app when the WebApp is finally launched.

That said, when someone in my company deployed the project via the "GUI wizard on Azure OpenAI studio", the resulting deployed did have the history functionality, which I interpret as the fact that, for this way of deploying, at least some of the variables which are written in the .env file (via the content of the main.bicep) at the end of the provisioning process are / can then made available to the app which hosts the WebApp.
But **I want to be able to define the project 'as code' as much as possible**, for reproducibility of deployment purposes, so **I don't want to have to use any kind of GUI** in order to achieve the desired state of the project / of the solution.

So my questions are:
- **How can one make it so to deploy a completely working solution via this project - including any functionality which is based on the existence / the value of env variables which are usually defined in an azure .env file - using only command line interface / developers tools?**
- **If using the content of an .env file (completed via the provisioning process) is not the right way to do that, then how is one supposed to do?**

I've searched and searched the internet, but I have not been able to find a satisfactory answer yet. My latest lead is maybe setting variables in the 'pipeline' section of the 'azure.yml' file, but I was under the impression that the point of this is to provide env variables which are needed during the build / deployment phase only? Would that be correct for my use case, or not?

In any case, I think whatever the answer to my question is (even if it's a negative one) should be included in the documentation / README file which explains how to deploy the project using the 'azd' tool.

**Comment by Explorergt92** [comment]
It's because the Azure eastus region doesn't have any capacity available, change "eastus" to "eastus2" in ./infra/main.bicep on line 203

**Comment by FrancoisNoyez** [comment]
Hi @Explorergt92 
Ok, I see, thanks, I'll look into that.

**Comment by FrancoisNoyez** [comment]
> > After investigating that (logging via ssh into the server hosting the backend, via the web interface providing this service), I realized that this may be caused by the absence of the env variables related to the definition of the COSMOS db (ex: 'AZURE_COSMOSDB_ACCOUNT').
> 
> I am also experiencing the same issue as you, [@FrancoisNoyez](https://github.com/FrancoisNoyez). Otherwise I have to add the CosmosDB env variables manually every time I deploy.
> 
> I'm not quite understanding how the region would resolve the missing CosmosDB env variables.

Hi @woege 

For reference, in the end I implemented the ability to deploy the WebApp from the CLI / to update the env variables used by teh WebApp, via custom python scripts.
For instance, here is the relevant part for the script used to propagate the desired end variables:
```python
from azure.identity import DefaultAzureCredential
from azure.mgmt.web import WebSiteManagementClient

client = WebSiteManagementClient(
      credential=DefaultAzureCredential(),
      subscription_id=subscription_id,
  )

  # Upload the desired env vars
  # WARNING: The 'update' in question works by overwritting all the app settings,
  # so we need to fetch the current ones first, in order not to remove any by mistake
  existing_app_settings = client.web_apps.list_application_settings(
      resource_group_name=resource_group_name,
      name=web_app_service_name,
  )
  updated_app_settings = {
      k: getattr(existing_app_settings, k)
      for k in ["id", "name", "kind", "type", "properties"]
  }
  updated_app_settings["properties"].update(to_upload_env_vars)
  client.web_apps.update_application_settings(
      resource_group_name=resource_group_name,
      name=web_app_service_name,
      app_settings=updated_app_settings,
  )

  # Restart the webapp service
  response = client.web_apps.restart(
      resource_group_name=resource_group_name,
      name=web_app_service_name,
      synchronous=True,
  )
```
