### ISSUE TITLE
Updated UI keeps reverting back to Contoso branding

### ISSUE THREAD

**Issue by stbere** [microsoft/sample-app-aoai-chatGPT#1048]
**Describe the bug**
Help!! This is the 3rd time i've went into the Development Tools>SSH, nano into the css files and modify the color, branding etc. After an extended period of time, my web app keeps reverting back to the default "Contoso" branding that it has when you first deploy the model. What am I doing wrong?? Why does it keep reverting back? Do I need to disconnect it from the external git repo from the Azure portal?

**To Reproduce**
1. Go to Development Tools
2. Click on SSH
3. CD to ./static/assets/ and select the appropriate CSS to modify
4. Save files changes & test UI frontend and looks good for a few days, then after inactivity it reverted back to Contoso branding?

**Expected behavior**
My UI changes to stick on the frontend longer than 2-3 days

**Screenshots**

**Configuration: Please provide the following**
 - GPT-4o
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc) No

**Comment by matben1611** [comment]
Hi there, im currently working a project where a similar issue appears, could u tell me where you put your custom Logos and how u fixed your issue? For me the problem is, that the ./static/assets directory is getting nuked every time i trigger the build process via start.sh :)
