### ISSUE TITLE
what is max_tokens for gpt-35-turbo-16k?

### ISSUE THREAD

**Issue by HuapingLiu** [microsoft/sample-app-aoai-chatGPT#106]
offical doc mention max_tokens (AZURE_OPENAI_MAX_TOKENS) is 1500. [gpt-35-turbo-16k](https://review.learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data?branch=main#maximum-response)

Actually if I increase it 10000, it still works with gpt-35-turbo-16k model and the answer is much better. But after running few questions, I got the following errors:

> _424, message='Failed Dependency', url=URL('https://aoai-gpt-35-turbo-use-prod-0613.eastus.inference.ml.azure.com/v1/engines/gpt-35-turbo-16k/chat/completions?api-version=2023-06-01-preview')
> Call to LLM failed._ 

how to increase the max_token?

**Comment by sarah-widder** [comment]
Hi @HuapingLiu - are you using Azure OpenAI on your data? If so, this makes the underlying prompt sent to the model much longer as it includes the context from your documents. In that case, I would recommend setting the max_tokens to 8000 or less to allow for plenty of room for the long prompt.

**Comment by HuapingLiu** [comment]
Cool, yes, I am using Azure OpenAI on your data, I found around 8000 is a good value to have stable return.
