### ISSUE TITLE
Unable to see the feedback icon 

### ISSUE THREAD

**Issue by Rajeshcs79** [microsoft/sample-app-aoai-chatGPT#1066]
The feedback icon does not appear in the screen though it is available in the chat feature in AI studio. I don't see it as a configurable parameter. Do you have plans to include the feature or Iam i missing something?

**Comment by wheatsnackbread** [comment]
As long as you have Cosmos DB set up and connected, you should be able to enable the thumbs up/thumbs down feedback function using the environment variable `AZURE_COSMOSDB_ENABLE_FEEDBACK` and setting it to True. Check the readme.

**Comment by iseabock** [comment]
@Rajeshcs79 Let me know if you are still having issues.
