### ISSUE TITLE
Unable to update front end UI

### ISSUE THREAD

**Issue by mikki** [microsoft/sample-app-aoai-chatGPT#109]
I am trying to update the front UI but Azure web app doesn’t receive any update, although it shows success in the deployment center. 

I have tried with GitHub actions and codespace ( Az command) but still it’s the same. Did anyone face this issue? 

thanks for sharing :)

**Comment by motibenm** [comment]
I faced it, came here to open the exact same issue :)

**Comment by sarah-widder** [comment]
Make sure that you rebuild the frontend before deploying, e.g. run `npm run build` from the frontend folder.

**Comment by killchainrepo** [comment]
Thanks Sarah, will do.

**Comment by mikki** [comment]
Thanks Sarah, will do

**Comment by motibenm** [comment]
> Make sure that you rebuild the frontend before deploying, e.g. run `npm run build` from the frontend folder.

Hey Sarah, maybe I'm missing something, but it still doesn't work.
Even after making sure npm run build is working, when I deploy my changes using Azure CLI, the frontend code doesn't change and the Azure SVG is targeting a different file located under the static/assets folder (and not frontend/assets)

**Comment by motibenm** [comment]
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/140501804/9413669e-cebe-4f01-a106-a1753a62fe78)
And it doesn't change no matter what you do

**Comment by motibenm** [comment]
Ok, so a quick update because I totally didn't understand it :)
You need to run the changes -locally- (VS code is what I used). After you run the changes, run npm run build inside the frontend folder. This will the js, js.map files under the static folder. It will -also- alter the index.html file to use the latest js file :)
Thanks for the help!! :)

**Comment by sarah-widder** [comment]
Glad to help. Resolving this issue for now.
