### ISSUE TITLE
Responses from LLM not being recorded in Chat History DB

### ISSUE THREAD

**Issue by jack-vinitsky** [microsoft/sample-app-aoai-chatGPT#1111]
**Describe the bug**
Currently the chat history is only recording the end user's prompts and not the responses from the LLM.  Checking the Cosmos DB database only shows end user prompts.  

**To Reproduce**
1. Create a new chat and note the responses
2. Start a new chat and then go to chat history.
3. Click on a prior conversation.
4. Note that only the end user's prompts are displayed.

**Expected behavior**
The history of the conversation includes responses from the LLM.

**Screenshots**
Original Conversation:

![image](https://github.com/user-attachments/assets/a590f658-0475-419a-9d73-4e5740d5edd8)

Conversation Retrieved from Chat History:

![image](https://github.com/user-attachments/assets/83436aca-a30f-499d-b706-ac3d7893caea)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-35-turbo-16k, version 0613'): **gpt-4o**
 - Is chat history enabled? - **Yes**
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc) - **Azure AI Search**
```
```

**Additional context**
This is only happening on one of the 5 instances of this chatbot that we are running although this one is the most recent update that we have deployed (as of pull request #1073)

**Comment by dmytroHexagon** [comment]
Faced the same issue

**Comment by Ashutosh2547** [comment]
As far as I have seen the backend, there isn't any logic to save the responses in the database.
You can create your own endpoint to save the response in the conversations database and call it from the React code (to be precise Chat.tsx file).

**Comment by dmytroHexagon** [comment]
Yeap, I also investigated the code and haven't found saving of responses.
They used to work.
I didn't have time to find a commit where a problem was introduced.
Probably easier just to fix by myself.

**Comment by ukiguy** [comment]
We're seeing same issues. Also deployed using 1073

**Comment by dmytroHexagon** [comment]
The issue is fixed for me, using latest available image

**Comment by cdrguru** [comment]
Glad to see this issue resolved! We had the same problem with LLM responses not being captured in Cosmos DB, and this fix is crucial for teams relying on detailed logs for reporting.

For those exploring conversation analytics, capturing both user prompts and LLM responses helps track key metrics like response times or missed replies. This data is essential for optimizing AI interactions.

That’s why we built **AInsights for Power BI**, available on [AppSource](https://appsource.microsoft.com/en-us/product/power-bi/metropoliscorp1602190046889.chat-with-powerbi-analytics), to help teams analyze conversation data and improve system performance. 

Thanks again for the quick fix—it’s a big help!
