### ISSUE TITLE
Unable to update existing webapp

### ISSUE THREAD

**Issue by bibintb** [microsoft/sample-app-aoai-chatGPT#1123]
**Describe the bug**
When I deploy a webapp from the azure openAI studio, the app gets created but with a failed deployment. I have to manually add keys in the environment variable to make it work. Moreover, the app only works with the 2nd key.  

**Screenshots**
![image](https://github.com/user-attachments/assets/867d9a88-58bd-416f-bbea-f478033d9255)

![image](https://github.com/user-attachments/assets/1a2063bf-c653-4765-8e1a-410b480c347f)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version: all GPT- Models.

**Comment by RichDCs** [comment]
confirmed on my side (and with my customer).

Workaround for me was to deploy the web app from VS Code, using the Azure extension.

Finally, it is necessary to fill in the missing env variables: embedding model name, AI Search key. I confirm that the app only works with the 2nd key.
