### ISSUE TITLE
Documentation request: Intent generation and Azure AI Search parameters

### ISSUE THREAD

**Issue by sam-h-long** [microsoft/sample-app-aoai-chatGPT#1124]
**Is your feature request related to this sample app, or to an Azure service, such as Azure OpenAI or Azure AI Search?**
Primarily related to the sample app, I am asking for clarification on the intent generation process and what parameters are being passed to Azure AI Search.

**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem with understanding how the intent generation and Azure AI Search integration work within the sample app. Specifically, I am unclear about:

1. When and how the intent is generated (i.e., what prompt triggers it?).

2. What is being input into the Azure Search Service—whether it's the intent, the user question, or both.

3. How certain parameters are configured in the code, like `ELASTICSEARCH_STRICTNESS=3`, which I found while reviewing the sample app.

This lack of clarity makes it difficult to fully understand and extend the functionality of the app, especially when integrating additional services like Azure OpenAI or customizing the search behavior. Providing documentation or comments within the codebase would help solve this issue.

**Describe the solution you'd like**
Something like this... this is my current understanding: 

![image](https://github.com/user-attachments/assets/5b263aa7-7dac-46a9-b3bd-abe814a9c59d)

**Is this feature specific to your use case or your organization, or would it apply broadly across other uses of this app?**
General understanding 

**Describe alternatives you've considered**
I have tried searching the code base so any pointers to where the magic is happening would be great. 

**Additional context**
Referring to _2. What is being input into the Azure Search Service..._  are you using the [Python sdk implementation](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/search/azure-search-documents#create-a-searchclient)? If so, which parameters in the [SearchClient.search()](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/azure/search/documents/_search_client.py#L143) I am curious on is being used...

![image](https://github.com/user-attachments/assets/0d4b666e-36c1-46c3-aa61-8def3fdbc99e)

**Comment by sam-h-long** [comment]
Thanks @jack-vinitsky any insight on how the intent is being utilized in the system? For example, in the UI if I asked "What is the meaning of liffe?" 

Using Python I loaded the Cosmos DB Chat hIstory: 

![Image](https://github.com/user-attachments/assets/70b03a94-b666-4c33-a3c0-e682ff41dae2)


And if I process the json within `content` column I see`intent`: 

![Image](https://github.com/user-attachments/assets/5fd4d137-0944-4e1f-97c5-f253465e0f66)


Because the role is `tool` my guess is the Azure Search service is being called as a tool...

**Comment by jack-vinitsky** [comment]
I think the intent is what is sent to your configured search service (as a presumably better search query) then just sending only the prompt.  It might also be used to give a brief name to the conversation for the chat history panel.

**Comment by filipafcastro** [comment]
I'd also like to have more information on how the intent is generated. I'm having issues with unexpected token consumption (https://learn.microsoft.com/en-us/answers/questions/2103832/high-token-consumption-in-azure-openai-with-your-d) and having such explanation could help understand if this might be the reason.

**Comment by sam-h-long** [comment]
@filipafcastro I gave up. Still a lot of great stuff in this code base but for my use case I switched to [azure-search-openai-demo](https://github.com/Azure-Samples/azure-search-openai-demo) for better transparency on the backend LLM calls.

azure-search-openai-demo calls Azure Search Service as a tool call: https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/backend/approaches/chatreadretrieveread.py#L106 so that the search query "intent" is being generated by an LLM call 

My guess is this code base is doing the same but idk for certain
