### ISSUE TITLE
Deploy to web app option from azure ai studio fails during deployment every time

### ISSUE THREAD

**Issue by harishkm83** [microsoft/sample-app-aoai-chatGPT#1128]
**Describe the bug**
deployment of the web app fails every time.
I'm not sure, but I think it has to do with the recent deletion of the below file. the error message is pointing to this. 
![image](https://github.com/user-attachments/assets/71c8e5fd-5ff8-4a27-a6c9-df06a8025a24)

**To Reproduce**
1. deploy any playground settings to a new web app
2. the web app gets created, but deployment fails every time
3. see the deployment logs

**Expected behavior**
the web app deployment should have completed successfully 

**Screenshots**
![image](https://github.com/user-attachments/assets/12eec46c-c36c-4ffb-b013-893f7f65e742)
![image](https://github.com/user-attachments/assets/cae79844-b348-4db7-beb6-c5d34656821f)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-35-turbo-16k, version 0613')
 - gpt 4o 
 - Is chat history enabled?
 - Both case issue is happening.
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc)
 - Azure AI Search. 
- Verify the startup command and runtime configuration by showing the output of the following az CLI command:
```
az webapp show --name <app name> --resource-group <resource group name> --query "{startupCommand: siteConfig.appCommandLine, runtime: siteConfig.linuxFxVersion}"
```

**Logs**

1. If the application deployment is failing, please share the deployment logs using the following az CLI command:
```
az webapp log deployment show --name <app name> --resource-group <rg name>
```

2. If the application is crashing after deployment, please share the application logs using the following az CLI command:
```
az webapp log tail --name <app name> --resource-group <resource group name>
```

**Additional context**

**Comment by mekjr1** [comment]
Try Sync a few time. it might help
