### ISSUE TITLE
Error: Server disconnected -  LLM call failed for chat completion endpoint. Please set OAIGenerationConfig(is_chat=True)

### ISSUE THREAD

**Issue by vagnit** [microsoft/sample-app-aoai-chatGPT#114]
After a successful deployment to Azure using the wizard in Azure AI Studio, I am getting the error: 

"Error
Server disconnected
LLM call failed for chat completion endpoint. Please set OAIGenerationConfig(is_chat=True)"

Please let me know if any extra info is required.

![ScreenHunter_1644](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/2580514/8a3f5a1d-36bc-477b-90c9-2d1308c689cb)

**Comment by sarah-widder** [comment]
Hi @vagnit this may come from exceeding the rate limit on your model deployment. Please increase the TPM on your resource if possible, or wait between sending messages. Let us know if the problem persists.

**Comment by vagnit** [comment]
Hi @sarah-widder , thank you for your answer. It's strange as the error comes up really fast: I am the only one currently testing the app and I get the error usually after 2-3 small questions.

The TPM of the model I use (chatgpt), has already the maximum Tokens per Minute Rate Limit value: 120 K. Also, the App service plan is the maximum one for DEV: Basic B3.  The application setting: "AZURE_OPENAI_MAX_TOKENS" has the default value: 1000 but I think this is not associated with the TPM. Should I get a bigger service plan or there is another TPM configuration that I could change inside my web app?  


![ScreenHunter_1650](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/2580514/f657e327-0d62-4888-a96a-a58487352a68)

**Comment by arianna2001** [comment]
we have the same issue of @vagnit , sometimes work and sometimes no: let us know please how to ckeck these settings @sarah-widder

**Comment by andreas-amundsen** [comment]
I am also experiencing the same issue. My deployment was working fine until this error suddenly started occurring a couple of days ago.

**Comment by arianna2001** [comment]
i changed the max response token but not reaching 4000 cause in that case you do not have tokens left for input or previous messages: indeed 4000 token are shared between all of these and you need to find the correct balance maybe.

changing them at about 3000 seems to temporarly resolve my issue, but i need to test more

**Comment by Malikanhar** [comment]
I'm experiencing the same issue too, please let me know if you got the solutions on your hand!

**Comment by noplacelikecloud** [comment]
Same error... please send help!

**Comment by PeerW** [comment]
Same issue. Would appreciate any kind of support. Thanks!

**Comment by fellnerse** [comment]
Same issue here

**Comment by TomR2022** [comment]
Experiencing the same issue too

**Comment by davihub123** [comment]
Same issue here.

**Comment by Malikanhar** [comment]
lookslike there's an error in Europe deployment, have you tried to deploy on US? I'm having no issue on the US deployment

**Comment by arianna2001** [comment]
i need "bring your own data" feature and i need to stay in west europe or is useless in my situation

**Comment by Malikanhar** [comment]
Yep, i think so. We'll just wait for the Microsoft team to fix it

**Comment by arianna2001** [comment]
You can also check on OpenAI service health anche see this:

<img width="746" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/76773119/0520eadc-bc35-4d4f-939c-a775b1d85213">

**Comment by vagnit** [comment]
@arianna2001 you are right, my openai service also faces many health events the last days, only today there were 15 health events and it is currently unavalailable:

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/2580514/2dfce2fd-5535-4dd0-a914-8d0baa5c0d16)

**Comment by arianna2001** [comment]
interesting, thanks @davihub123 so it seems a problem with our region

**Comment by vagnit** [comment]
I just received a response from Azure support summarizing to the following, that we already knew actually:
-- Confirmation that only the WestEurope region has been affected. 
-- The product team is aware of the situation and is working on resolving the problem.
-- No firm estimate provided for when the problem will be resolved.
-- Suggestion to consider using a different AzureOpenAI instance in another region as a potential workaround if the application is needed urgently.

**Comment by arianna2001** [comment]
> I just received a response from Azure support summarizing to the following, that we already knew actually: -- Confirmation that only the WestEurope region has been affected. -- The product team is aware of the situation and is working on resolving the problem. -- No firm estimate provided for when the problem will be resolved. -- Suggestion to consider using a different AzureOpenAI instance in another region as a potential workaround if the application is needed urgently.

thanks @vagnit, appreciated it

**Comment by aamirmirzabaig** [comment]
Sad, happening in WE region as well.

**Comment by tobigels** [comment]
Issue still seems to be unresolved. Current health checks still say the service is unavailable or degraded
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/12412032/7c141f1f-7827-4740-b32f-5ccb1227ee87)

**Comment by aamirmirzabaig** [comment]
I found the fix for it, change the region to East US 👯‍♂️ 

It seems we need to enable the CORS for the storage account that is linked to your AOAI for documents read.

Go Inside the storage account > CORS > Blob service > then set all required values. 

Try and confirm if it resolves the issue ?

**Comment by timoknapp** [comment]
> Go Inside the storage account > CORS > Blob service > then set all required values.

@aamirmirzabaig what are the required values for the storage account? Can you share a screenshot of your configuration?

**Comment by arianna2001** [comment]
> I found the fix for it, change the region to East US 👯‍♂️
> 
> It seems we need to enable the CORS for the storage account that is linked to your AOAI for documents read.
> 
> Go Inside the storage account > CORS > Blob service > then set all required values.
> 
> Try and confirm if it resolves the issue ?

Thanks for the suggestion but it does not soubd like a fix if you need to stay in EU bridging your own data in a existing. subscription. In our case CORS settings are useless cause we are using indexes. Service is still not healty and we are waiting ofr a Microsoft resolution.

**Comment by SyadBabarAli** [comment]
Experiencing the same issue too

**Error**
Server disconnected
LLM call failed for chat completion endpoint. Please set OAIGenerationConfig(is_chat=True)


I have been facing this issue for almost a week now. Could you please fix it in the West Europe region? My organization is currently utilizing all resources in this region, so We can't change it.

Region
West Europe

**Comment by shamprasadrh** [comment]
Same issue I am also facing

**Comment by vagnit** [comment]
Good news!
Microsoft Support just informed me that : "_the problem has been completely resolved_." .
Indeed I have been testing for a while and I haven't get any errors so far.

**Comment by arianna2001** [comment]
> Good news! Microsoft Support just informed me that : "_the problem has been completely resolved_." . Indeed I have been testing for a while and I haven't get any errors so far.

Not in our case.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/76773119/01b607ab-a297-4878-a393-483f038c5ed6)

**Comment by shamprasadrh** [comment]
> Same issue I am also facing

I think issue still persists I got health issues today as well and Also service is very slow. 

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/28918386/081f83c9-a9e8-4f3d-b041-413bb444358f)


![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/28918386/64ede36d-bdd3-4897-a832-e6dbb6dd5473)

**Comment by miguelisidoro** [comment]
Hi,

Same error here, tried using the following regions: UK South, East US.
When will this be fixed?

Thanks

**Comment by miguelisidoro** [comment]
Hello,

When will this be fixed?
Same problems on UK South and East US.

Thanks

**Comment by davidm00** [comment]
Issue has been resolved.
