### ISSUE TITLE
Content filter raw error

### ISSUE THREAD

**Issue by zhamadagithub** [microsoft/sample-app-aoai-chatGPT#115]
When a user enter an inappropriate message that triggers content filter (such as " I want to kill all rats in the city"); webapp return a raw error message such as: 424, message='Failed Dependency', url=URL('https://xxxxxxxxxxxxxxxxxx.inference.ml.azure.com/v1/engines/gpt-35-turbo-16k/chat/completions?api-version=2023-06-01-preview') LLM call failed for chat completion endpoint. Please set OAIGenerationConfig(is_chat=True)
A more user friendly error should be returned.

**Comment by sarah-widder** [comment]
Hi @zhamadagithub thank you for the feedback, we are working on improving this error message.
