### ISSUE TITLE
AsyncClient.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by aphafzal** [microsoft/sample-app-aoai-chatGPT#1190]
I've randomly started getting this error from miday yesterday, anyone else facing this issue?

##full error##
Error
There was an error generating a response. Chat history can't be saved at this time. AsyncClient.__init__() got an unexpected keyword argument 'proxies'
##

Fix: updating Openai to 1.55.3 in the requirements file fixed the issue.

**Comment by craigpay** [comment]
I've been getting the same issue today on new web app deployments. Have Microsoft updated web apps again?

**Comment by MehmetStead** [comment]
@aphafzal  we deployed using azure data studio, (foundry) dont have a repository, how did you update the openai to 1.55.3, also the version I have is newer 1.6.1, but I am still getting this error. really frustrating that the off the shelf solution of microsoft is buggy.

**Comment by ragemnky** [comment]
@MehmetStead , I also had a deployment from azure data studio, had to do the following to get it going:
 
- Copied requirements.txt to /home/site/wwwroot/
- Updated openai in requirements.txt to 1.55.3
- Updated the startup command against the app service to be:

`pip install -r /home/site/wwwroot/requirements.txt && python3 -m gunicorn app:app`

- Restarted app service
- Working again

**Comment by r0hitacharya** [comment]
I am using Meta-Llama-3.1-70b-Instruct and still get the same error

**Comment by MehmetStead** [comment]
> [@MehmetStead](https://github.com/MehmetStead) , I also had a deployment from azure data studio, had to do the following to get it going:
> 
> * Copied requirements.txt to /home/site/wwwroot/
> * Updated openai in requirements.txt to 1.55.3
> * Updated the startup command against the app service to be:
> 
> `pip install -r /home/site/wwwroot/requirements.txt && python3 -m gunicorn app:app`
> 
> * Restarted app service
> * Working again

@ragemnky thanks so much but I found a better way. just fork the repository. Go to your app service, deployment center, disconnect the external git source, and add your forked repository as the new source. Make sure to select "app service build service" as deployment provider, that creates a web hook in your repository, now when you push, the app will be deployed automatically to your app service, great, no need for a deployment pipeline, or github workflow, or setting any environment variables.

**Comment by vleon-align** [comment]
Hi everyone,

I also deployed my app using Azure Data Studio (Foundry) and have tried several solutions, but I’m still facing the same error:

I added the requirements.txt file to the /home/site/wwwroot/ directory and installed the dependencies correctly.
I tried @MehmetStead   solution: I forked the repository, set my App Service to use that forked repository as the source in Deployment Center, disconnected the previous external Git source, and selected "App Service Build Service" as the deployment provider.
Despite these steps, I’m still encountering the same error.

Does anyone have any additional suggestions for what else I can try?

**Comment by himwroteCode** [comment]
Hi, I deployed from Azure Open AI or Azure Ai Studio and I am getting the same error "AsyncClient.__init__() got an unexpected keyword argument 'proxies'".  Since I followed the no code method so how I resolve this?

![Image](https://github.com/user-attachments/assets/381d6c27-7979-48cf-b8b7-4cdd4ff5bb69)

**Comment by ajallooeian** [comment]
Same issue here. I am using openai 1.9.0 and do now want to downgrade to 1.55.3.

**Comment by MehmetStead** [comment]
> Same issue here. I am using openai 1.9.0 and do now want to downgrade to 1.55.3.

You are not downgrading check openai releases, the numbering is weird 1.55.3 is higher

**Comment by NoSkillGuy** [comment]
same issue, upgrading to 1.55.3 worked

**Comment by vleon-align** [comment]
> > Hi everyone,
> > I also deployed my app using Azure Data Studio (Foundry) and have tried several solutions, but I’m still facing the same error:
> > I added the requirements.txt file to the /home/site/wwwroot/ directory and installed the dependencies correctly. I tried [@MehmetStead](https://github.com/MehmetStead) solution: I forked the repository, set my App Service to use that forked repository as the source in Deployment Center, disconnected the previous external Git source, and selected "App Service Build Service" as the deployment provider. Despite these steps, I’m still encountering the same error.
> > Does anyone have any additional suggestions for what else I can try?
> 
> [@vleon-align](https://github.com/vleon-align) You have to update python openai dependency to 1.55.3 in requirements and commit

Thanks a lot @MehmetStead  I changed to 1.55.3  and then commit and it works!

**Comment by sarah-widder** [comment]
Fixed with #1195

**Comment by himwroteCode** [comment]
> > [@MehmetStead](https://github.com/MehmetStead) , I also had a deployment from azure data studio, had to do the following to get it going:
> > 
> > * Copied requirements.txt to /home/site/wwwroot/
> > * Updated openai in requirements.txt to 1.55.3
> > * Updated the startup command against the app service to be:
> > 
> > `pip install -r /home/site/wwwroot/requirements.txt && python3 -m gunicorn app:app`
> > 
> > * Restarted app service
> > * Working again
> 
> [@ragemnky](https://github.com/ragemnky) thanks so much but I found a better way. just fork the repository. Go to your app service, deployment center, disconnect the external git source, and add your own forked repository as the new source. Make sure to select "app service build service" as deployment provider, that creates a web hook in your repository, now when you push, the app will be deployed automatically to your app service, great, no need for a deployment pipeline, or github workflow, or setting any environment variables. You can maintain the code from your own repository, so it really is a click ops solution that works. I am impressed

Hi @MehmetStead this was really helpful, after all workaround I find working.

**Comment by tahsinalamin** [comment]
Updating `openai` to `1.55.3` worked!
