### ISSUE TITLE
onedeploy to azure webapp not working

### ISSUE THREAD

**Issue by yull1860outlook** [microsoft/sample-app-aoai-chatGPT#120]
as the FrontEnd use **npm install / npm run build** which not available in azure app **python** image , please consider release a public ACR / dockerhub image so customer can use to play with . 

Also suggest to add a azure_startup.sh for setup the env in azure app . 
**start.cmd/start.sh** looks only work in local (binded to localhost: 127.0.0.1). 

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/60593105/5c44a87c-a3b7-4b99-acdf-75937821f2a3)

**Comment by ealasgarov** [comment]
you can find the image details at the bottom of this page
https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/.github/workflows/docker-image.yml

**Comment by yull1860outlook** [comment]
Thanks @ealasgarov sharing the docker image . tested working fine . 

Would you please update the **[main.bicep](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/infra/main.bicep)** to use the mentioned docker image (**fruoccopublic.azurecr.io/sample-app-aoai-chatgpt:latest**)  instead of **"python|3.10"** ? 
please note azure portal will invoke the main.bicep to provision test app ( https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/infrastructure/deployment.json is pointing correct container image ) which not supposed to work as I mentioned initially.  

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/60593105/8f32d115-5b9f-4df1-9034-7ed333b89b2f)
