### ISSUE TITLE
Support for Function Calling

### ISSUE THREAD

**Issue by rubenaster** [microsoft/sample-app-aoai-chatGPT#129]
Hi, and first of all, thanks for this great project!

I'd like to know if you already have implementing [function calling](https://openai.com/blog/function-calling-and-other-api-updates) on your roadmap? Even so I'm sure that it's not easy to think about a very general solution that makes sense for a shared project like this.

Best,

Ruben

**Comment by davidm00** [comment]
Hi, there is no information I can share about this at the moment but will update in the future if there are plans for this.
