### ISSUE TITLE
Microsoft Word and PowerPoint support?

### ISSUE THREAD

**Issue by raffertyuy** [microsoft/sample-app-aoai-chatGPT#130]
[Documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data#data-formats-and-file-types) says this supports MS Word and PowerPoint. Tried uploading .doc file and search index built has 0 data.

Please validate?

`./scripts/datautils.py` looks like only the ff filetypes is supported.
```python
FILE_FORMAT_DICT = {
        "md": "markdown",
        "txt": "text",
        "html": "html",
        "shtml": "html",
        "htm": "html",
        "py": "python",
        "pdf": "pdf"
    }
```

Also logged [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/113124)

**Comment by lindazqli** [comment]
Hi @raffertyuy, thanks for your feedback. MS word and PowerPoint are supported on AOAI studio https://oai.azure.com/portal, not through scripts now.
