### ISSUE TITLE
quota limit on cli deployment

### ISSUE THREAD

**Issue by unmuntean** [microsoft/sample-app-aoai-chatGPT#137]
I keep getting this : 
The specified capacity '1' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) - GPT-35-Turbo'. (Code: InsufficientQuota)

How to overcome it ?

**Comment by pamelafox** [comment]
You need to reduce the TPM of your existing deployments before you can make a new one, or try deploying to a different region. You can edit the TPM in the studio:

For each of your existing deployments, edit them and slide the slider down:

<img width="1211" alt="Screenshot 2023-08-06 at 9 05 03 PM" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/297042/f20d0fd8-f6d1-4766-8833-d4a1bb9e52f6">
