### ISSUE TITLE
Azure-search-openai-demo - Upload File

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#145]
I ran the scripts to deploy the application to the test signature. After deploying, when running the application, I uploaded a file. However, when clicking "Submit", the file upload is not taking place. There are no error messages during upload. I would like to know if it is necessary to adjust some parameter after deployment to allow the upload.

Upon reviewing the code, it appears that in order to perform the upload, the file needs to be saved locally so it can be split into pages and then pushed to the blob. The relevant snippet is in the "app.py" file, at line 79, where the file is saved in a local directory.  At line 160, the file is saved in a local directory. (filesave)
 
My question is the following: when deploying, is there any configuration that needs to be changed to ensure that the file is saved locally and later divided into pages for upload to the blob?

**Comment by pamelafox** [comment]
Hi @edercarlima, you made the same issue in the other repo: https://github.com/Azure-Samples/azure-search-openai-demo/issues/510
Was that a mistake, and this is the repo you're talking about? By Submit button, do you mean in the Azure OpenAI studio?

**Comment by pamelafox** [comment]
Closing the issue in this repo.
