### ISSUE TITLE
Request to add chat history & session states, issue: refreshing clears conversation

### ISSUE THREAD

**Issue by chrissaba** [microsoft/sample-app-aoai-chatGPT#146]
Hello,
Currently refreshing the page causes the chat & history to completely reset and doesn't allow much versatility for creating an app that uses this webapp on the side.  i.e. streamlit on python

Is there a way to keep session alive to the user? Similar to how chat.openai.com handles their chat history with sessions, but not to the extent of saving histories. At this point the cleanup chat button is redundant due to the refresh button on the browser.
Thank you

**Comment by aman-neudesic** [comment]
@chrissaba I am experiencing the same issue. @pamelafox

**Comment by lindazqli** [comment]
Hi @chrissaba @aman-neudesic, thanks for the feedback. Chat history is on our roadmap, and we will keep you posted.

**Comment by sarah-widder** [comment]
Hi @chrissaba @aman-neudesic we just merged an update adding chat history, which you can try out from the Azure OpenAI Playground or with one click deployment. Closing this thread!
