### ISSUE TITLE
QUESTIONS ABOUT .ENV.SAMPLE

### ISSUE THREAD

**Issue by phfontes** [microsoft/sample-app-aoai-chatGPT#151]
Hello,
I have two questions about filling out the .env.sample file
Is there any example to provide?
The other, how to improve and prevent it from falling into the conversation_without_data function.
We don't want him to use his knowledge to answer, only use his knowledge when he has documents.

**Comment by gopi-hl** [comment]
Here's what I did.

Used oai.azure.com and deployed a WebApp based on your private data. 
You'll get all the variables there from the website.

**Comment by phfontes** [comment]
@gopi-hl 
Hello,
I tried to do this same test and defining a condition in the system message, it is ignoring the condition.
Example: A system that answers questions about internal documents, I asked how much a car costs.
I put it in the condition, so that when he doesn't know, he can advise him to contact Leonardo.
But, the message "The requested information is not available in the retrieved data. Please try another query or topic."

In your case, did you have a nice experience?

**Comment by davidm00** [comment]
Hi, there is only one way to prevent users from receiving a response and that is by checking the "limit responses to your data" option in the studio. Currently, we do not support any way of modifying the message returned for out of scope questions.
