### ISSUE TITLE
File upload and index creation automatically

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#152]
Hi @pamelafox 

Doubt: Does the roadmap provide a version where it is possible to upload the file by the application and perform the reindexing automatically?
If it is on the roadmap, is there a plan to make this version available?

**Comment by sarah-widder** [comment]
Hi @edercarlima if you use the Azure OpenAI Chat Playground, you can add your data and schedule automatic index updates. See the documentation: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data#schedule-automatic-index-refreshes

**Comment by edercarlima** [comment]
@davidm00 I used the documentation mentioned and it helped a lot. Thanks a lot for the help.
