### ISSUE TITLE
Possibility to adjust Redirect URL

### ISSUE THREAD

**Issue by joeakim** [microsoft/sample-app-aoai-chatGPT#153]
Hi there,

so I am trying to publish the WebApp via Front Door or Application Gateway. Which both of course have a different URL than the WebApp. When accessing it via Front Door, and authenticating with AzureAD, I then get redirected to the WebApps "internal" URL. 

I don't know what is causing this and if it is the WebApp that has this somehow implemented and is ordered to redirect to it's "internal" URL. How can I stop it from doing so and redirect to the URL that was initially called? I would also be fine, if I had to enter the Front Door URL manually into the environment variables.

More about this issue can be found within this Microsoft Documentation:
https://learn.microsoft.com/en-us/azure/app-service/overview-authentication-authorization#considerations-when-using-azure-front-door

Thanks for your help!

**Comment by davidm00** [comment]
Hi, there is a setting on your AAD to modify or change the redirect URL.
