### ISSUE TITLE
HELP TO RUN LOCALLY

### ISSUE THREAD

**Issue by phfontes** [microsoft/sample-app-aoai-chatGPT#154]
Hello,
I would like some help to run the code locally, how much do I run
Returns openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>
I already made the settings in .env.sample
Could it be some setting in this file?

**Comment by pamelafox** [comment]
You should not be changing .env.sample, you should be making a new file based on .env.sample with the filename ".env", then that file will get automatically loaded in.

**Comment by christie-hill-za** [comment]
> Hi I have the same issue, I was searching .env.sample in the code to see if in some place is a dependency, I didnt find anything related. So why we should not change .env.sample by only .env? Anyway is producing the same error

env.sample is just an example, like a template. It is commonly used in web applications to provide a demonstration of what the actual .env should look like. It poses a security risk if a .env file is committed to version control, it can expose private keys and database access credentials. I hope this helps!
