### ISSUE TITLE
Error "LLM call failed for chat completion endpoint. Please set OAIGenerationConfig(is_chat=True")

### ISSUE THREAD

**Issue by miguelisidoro** [microsoft/sample-app-aoai-chatGPT#155]
Hello,

We have successfully provisioned in the Azure Portal the infrastructure necessary for a scenario of use your own data in Azure AI Studio.

In the Azure AI Studio portal everything is working fine.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/5429152/b11270d7-4d11-4445-8f7f-1912afb59a21)

But when we are using the API things are not working. What I've done is getting the request that the Azure AI Studio is creating and using it in a Postman request. The api key I am using for authentication is the one from our Azure Open AI resource in Azure.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/5429152/97df7055-760c-4682-9c08-c31b663ea10b)

The error we are obtaining is the following:

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/5429152/fd7e3d40-4ad8-45db-8f79-923f4549f29b)

We have tried 2 regions in our tests: UK South and East US and from what I searched over the internet, there are more persons complaing. Example: https://github.com/microsoft/sample-app-aoai-chatGPT/issues/114

Can you help?

Thanks,

Miguel

**Comment by miguelisidoro** [comment]
Hi,

Any feedback on this?

Thanks

**Comment by miguelisidoro** [comment]
Hello,

Any feedback on this issue?

Thanks

**Comment by sarah-widder** [comment]
Hi @miguelisidoro can you confirm if this issue is still occurring for you? If so please open a support ticket with Azure OpenAI so we can track the issue and resolution for you.

**Comment by miguelisidoro** [comment]
Hello, 

The issue was solved on Microsoft side.

Thanks
