### ISSUE TITLE
Add User Feedback Thumbs Up / Down to Answers

### ISSUE THREAD

**Issue by jzagelbaum** [microsoft/sample-app-aoai-chatGPT#160]
Add a mechanism to setup RLHF with a simple thumbs up / down that flags and logs user request and answer history for later review similar to BYOD feedback setup in AOAI studio

**Comment by ThomasLambertES** [comment]
+1

**Comment by iseabock** [comment]
[https://github.com/microsoft/sample-app-aoai-chatGPT/pull/396](396)
