### ISSUE TITLE
Contoso data present even after removing files from the project

### ISSUE THREAD

**Issue by timamay** [microsoft/sample-app-aoai-chatGPT#161]
I have created my own semantic search service using embeddings which reads files from an azure container. I also removed all the files in the project that were related to contoso. However, even after setting everything up to look at my own data, it still is including the contos data. Where is this data coming from? Is there some container or somewhere these files need to be removed so that it only sees the data related to the search service and index?

**Comment by sarah-widder** [comment]
Hi @timamay are you still seeing this issue? Can you clarify more about the Contoso data you're seeing?

**Comment by timamay** [comment]
This issue was resolved.

Thanks,
Tim
________________________________
