### ISSUE TITLE
:( Application Error If you are the application administrator, you can access the diagnostic resources.

### ISSUE THREAD

**Issue by nchan1994** [microsoft/sample-app-aoai-chatGPT#171]
Steps to Reproduce the error:

1. Pull new code from GitHub
2. Use 'One Click Azure Deployment' method at first deployment
3. Insert Env Variables, create resources. Deploy
4. Tested. Works fine.
5. Use 'Deploy with Azure CLI' method to deploy the code grabbed from Git hub WITHOUT CHANGING ANYTHING TO THE CODE.
6. After 'az login', run following code: az webapp config appsettings set -g <resource-group-name> -n <existing-app-name> --settings WEBSITE_WEBDEPLOY_USE_SCM=false (Note: replacing all the variables with necessary resource group name, app name etc)
7. Then run the following code: az webapp up --runtime PYTHON:3.10 --sku B1 --name <existing-app-name> --resource-group <resource-group-name> (Note: replacing all the variables with the necessary RG name, app name etc too)
8. Go back to my web app, now the error says ':( Application Error If you are the application administrator, you can access the diagnostic resources.'

Not sure what's happening or why this error occurs. I did not change anything to the code given on Github

**Comment by sarah-widder** [comment]
Hi @nchan1994 I believe this is likely a runtime mismatch issue. The 'One Click Azure Deployment' was recently changed to use Python 3.11 instead of 3.10. You may be able to recover by using `az webapp up --runtime PYTHON:3.11 --sku B1 --name --resource-group` (note the change in runtime). We will update the documentation for this as well.

**Comment by nchan1994** [comment]
Hi @sarah-widder, thanks for your reply!

May I understand correctly that if I use the 'One Click Azure Deployment' method, then I cannot use the az webapp up method?

**Comment by sarah-widder** [comment]
Hi @nchan1994 following up here. The problem with One Click deployment followed by `az webapp up` was that One Click deployment did not set the app setting SCM_DO_BUILD_DURING_DEPLOYMENT to true to allow the app to build when deploying from code directly. If you update that app setting on your app service, you should be able to deploy with `az webapp up` subsequently.

**Comment by PriscilaLepping-Atos** [comment]
I also have the same problem, the deployment worked but the url has problems, can you help please
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/136828946/1b3924d9-7cab-40d5-a3b5-04a904f1f621)

**Comment by justynatk** [comment]
> I also have the same problem, the deployment worked but the url has problems, can you help please ![image](https://private-user-images.githubusercontent.com/136828946/278666259-1b3924d9-7cab-40d5-a3b5-04a904f1f621.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTc0NDAsIm5iZiI6MTcwNDcxNzE0MCwicGF0aCI6Ii8xMzY4Mjg5NDYvMjc4NjY2MjU5LTFiMzkyNGQ5LTdjYWItNDBkNS1hM2I1LTA0YTkwNGYxZjYyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxMjMyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTJlNjY4MzNmZDA1NjNjNDA0ZmMwOGRiNDNhNmRiZDNlYWE2ZGY0ZWVkMmYzNmNkMDFhNmViOWRiOGNmNDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.obHDuVR0GCS4bbncmn5cLdIUu0gb0X8_cI2lwvn4xBM)

hello, did you manage to solve this issue as I'm currently facing it too?

**Comment by justynatk** [comment]
@PriscilaLepping-Atos  did you manage to solve this issue as I'm currently facing it too?

**Comment by kagoolastha23** [comment]
> Hi @nchan1994 following up here. The problem with One Click deployment followed by `az webapp up` was that One Click deployment did not set the app setting SCM_DO_BUILD_DURING_DEPLOYMENT to true to allow the app to build when deploying from code directly. If you update that app setting on your app service, you should be able to deploy with `az webapp up` subsequently.

Hi I am facing same and want to know what are the steps to solve this? How do I add SCM_DO..... to the app so that it runs properly.Please guide.

**Comment by kokatic** [comment]
same issue here!

**Comment by CarlaMamaniChavez** [comment]
Hey @kagoolastha23 
To be able to add the SCM_DO_BUILD_DURING_DEPLOYMENT variable just go to your web application > Configuration > Environment variables
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/66276312/230f9c47-c36b-4256-a2b1-253d0ed8cb2d)
