### ISSUE TITLE
Chat errors out often (starting today)

### ISSUE THREAD

**Issue by kcheriyath** [microsoft/sample-app-aoai-chatGPT#177]
The chat fails intermittently with an error as below from this morning. 

An error occurred. Please try again. If the problem persists, please contact the site administrator which seems to be coming from https://github.com/microsoft/sample-app-aoai-chatGPT/blob/594ac860e2108de2fc1979e803a4369597e12ef8/frontend/src/pages/chat/Chat.tsx#L92

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/14891259/4804da42-2bc7-4b0f-ac2e-e4b771a81d1f)

Trying again fixes the issue and continues the conversation, often on the first or second try. The errors are repeated on two separate deployments, on gpt-35-turbo and on gpt-4.

The error from browser console is

```
{
  "error": "415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'."
}
```

The instance is up to date and is on python 3.11. There was no problems previously, so I suspect this could be an azure openai glitch as well.

**Comment by sarah-widder** [comment]
Hi @kcheriyath are you still hitting this issue? If so, please open a support ticket with Azure OpenAI service to get help with debugging.

**Comment by kcheriyath** [comment]
The errors lasted a day or so and disappeared on its own. Closing the issue

**Comment by ZumelzuR** [comment]
This is continue happening today
