### ISSUE TITLE
Support for English language only in OpenAI API - missing queryLanguage parameter 

### ISSUE THREAD

**Issue by kacpermuszynski** [microsoft/sample-app-aoai-chatGPT#183]
Hi !
I am trying to find a way of defining in which language Cognitive Search is searching for content.

From my observation in Search Service API you specify **queryLanguage**. Is it also possible to specify this language in Azure Portal:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/62251767/1e72e2d0-5b47-4ec5-b339-cf4adc960968)

I wanted to specify language in **dataSources**, but I haven't find such an option in documentation.
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/62251767/5d9eb7d5-5126-4bbf-b1bd-815f7c3be838)

How can I bypass this limitation?

Thanks !

**Comment by sarah-widder** [comment]
Hi @kacpermuszynski  you can set the language of your documents when creating your index if you use the `data_preparation.py` script included in this repo: https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/scripts/readme.md . Here are some additional best practices for multi lingual support: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data#interacting-with-the-model
