### ISSUE TITLE
CHANGE TEXT DEF_CONVERSATION_WITHOU_DATA

### ISSUE THREAD

**Issue by phfontes** [microsoft/sample-app-aoai-chatGPT#184]
Hello,
Would you know how I can customize the text "The requested information is not found in the retrieved data. Please try another query or topic." which is triggered in the def_conversation_without_data function, when the question asked does not have an answer within the cognitive search documents.

**Comment by sarah-widder** [comment]
Hi @phfontes this message is not currently customizable. You could add some postprocessing on the message before it's displayed to the user to replace it with another string if you wanted though.

**Comment by phfontes** [comment]
Hi,
Thanks for the feedback, I tried doing some tests.
Through the debug, I saw that the function below is responsible for taking the content and sending it.
In the else part where the deltatext is created, it ends in yield, triggering another function, def format_as_ndjson(obj: dict) -> str:
And then it goes back to yield and goes up to the for line
I believe you could put an if in the variable that stores the content sent to the body and check if it is different from "The requested information..."
But I can't understand where it collects the deltatext information and sends it to the body of the page
Could you clarify?
def stream_with_data(body, headers, endpoint):
    s = requests.Session()
    linhas = []
    response = {
        "id": "",
        "model": "",
        "created": 0,
        "object": "",
        "choices": [{
            "messages": []
        }]
    }
    try:
        with s.post(endpoint, json=body, headers=headers, stream=True) as r:
            #linha onde busca o conteúdo, acompanhar pela propriedade line, nas variaveis locais
            for line in r.iter_lines(chunk_size=10):
                if line:
                    lineJson = json.loads(line.lstrip(b'data:').decode('utf-8'))
                    if 'error' in lineJson:
                        yield format_as_ndjson(lineJson)
                    response["id"] = lineJson["id"]
                    response["model"] = lineJson["model"]
                    response["created"] = lineJson["created"]
                    response["object"] = lineJson["object"]

                    role = lineJson["choices"][0]["messages"][0]["delta"].get("role")
                    if role == "tool":
                        response["choices"][0]["messages"].append(lineJson["choices"][0]["messages"][0]["delta"])
                    elif role == "assistant": 
                        #adiciona chave role e content ao messages
                        response["choices"][0]["messages"].append({
                            "role": "assistant",
                            "content": ""
                        
                        })
                    else:
                        deltaText = lineJson["choices"][0]["messages"][0]["delta"]["content"]
                        if deltaText != "[DONE]":
                            #adiciona o conteúdo do deltatext ao content
                            response["choices"][0]["messages"][1]["content"] += deltaText
                            linhas.append(deltaText)
                            
            

                    #retorna para outra função formatar em json
                    #yield
                    
                    yield format_as_ndjson(response)
            print(linhas)
    except Exception as e:
        yield format_as_ndjson({"error": str(e)})

**Comment by ms-porini** [comment]
is it still not possible?
