### ISSUE TITLE
Refresh token strategy

### ISSUE THREAD

**Issue by KevinJaroschewski** [microsoft/sample-app-aoai-chatGPT#199]
Hello, I have configured my identity provider, and everything is functioning properly. However, after approximately an hour, the access token expires and fails to refresh. The refresh only occurs after deleting the cookie. I have also enabled the 'offline_access' scope, as I have read that this is related to facilitating the refresh token expiration. What steps should I take to ensure that my access token is automatically refreshed before it expires?

**Comment by Epstone** [comment]
What is the solution to this? I am currently seeing following log error:
ERROR:root:Error fetching user groups: 401 {"error":{"code":"InvalidAuthenticationToken","message":"Lifetime validation failed, the token is expired.","innerError":{"date":"2024-03-28T12:09:54","request-id":"...","client-request-id":"..."}}}

**Comment by kd4293-lattice** [comment]
@KevinJaroschewski , what is the solution, I'm facing the same issue.

**Comment by 2gad** [comment]
Did anyone find a solution for this? I am experiencing the same problem when trying to use the X-Ms-Token-Aad-Id-Token for document filtering
