### ISSUE TITLE
user.readbasic.all scope after deployment

### ISSUE THREAD

**Issue by RobSch1406** [microsoft/sample-app-aoai-chatGPT#209]
Somehow admint consent request needs to approve user.readbasic.all scope. 
Deployment functionality of azure open AI Studio used. 
Within API Permission no Graph permissions listed. 

Hardcoded? Where could not find anything in repo

**Comment by sarah-widder** [comment]
Hi @RobSch1406 this permission is configured in the authsettingsv2 config on the app service, it is used to support document-level access control when using Azure OpenAI on your data. You can view and modify the authsettingsv2 config in the resource explorer https://resources.azure.com/ or with the ARM API: https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/get-auth-settings-v2

**Comment by SinishaDjukic** [comment]
Dear @sarah-widder thank you very much for this much needed hint!
However, I cannot find the authsettingsv2 config UI in the resource explorer - no similar settings available under Web App > Settings > Authentication blade, i.e.:
https://portal.azure.com/<org>/resource/subscriptions/<subid>/resourceGroups/<resgroupid>/providers/Microsoft.Web/sites/<serviceapp>/eauth

I only see the general auth settings and the choice of the identity provider. Could you kindly give some extra hints?

**Comment by sarah-widder** [comment]
Hi @SinishaDjukic in the resource explorer (https://resources.azure.com/ , not the Azure portal), expand the sections on the left:
subscriptions > (Your subscription name) > resourceGroups > (your resource group name) > providers > Microsoft.Web > sites > (your web app name) > config > authsettingsv2

**Comment by SinishaDjukic** [comment]
Dear @sarah-widder, thank you! That path worked for me, but also in the meantime I used postman to update the policy, so the permissions have effectively been reduced. But it seems that the code cannot handle that currently. The chat UI is shown, but issuing any kind of chat msg results in two errors:

Access denied due to Virtual Network/Firewall rules.
An error occurred. Answers can't be saved at this time. If the problem persists, please contact the site administrator.

So no real chat response.
Is there a plan to make these permissions truly optional in the code?

**Comment by keisari-ch** [comment]
Hello,

I just deployed the solution, i can say Hi, get an a first answerm, and quickly then, i cant get past the following error :

```
Error
An error occurred. Answers can't be saved at this time. If the problem persists, please contact the site administrator.
```

I can observe a _lot_ of python errors on the logs like :
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/28117379/85f53981-5052-4389-990d-72c595692a92)

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/28117379/3afbd963-6121-4ec8-825d-b7e8c0a5168c)

This is a private deployment. 
openai, search, cosmosdb and the app service are deployed in the same VNET
app service has private endpoint and vnet integration.
NSG FLow Logs show no traffic denied
All outbound traffic to internet is routed via Azure Firewall and no traffic is denied as the following fqdn were allowed prior to deployment of the app service :

```
        - sts.windows.net
        - dc.services.visualstudio.com
        - github.com
        - oryx-cdn.microsoft.io
        - pypi.org
        - files.pythonhosted.org
        - login.microsoftonline.com
```

Any idea how i can debug further ?

**Comment by sarah-widder** [comment]
User.ReadBasic.All has been removed from app deployment flow in Azure OpenAI Studio. Closing this issue.
