### ISSUE TITLE
Not receiving logs in CosmosDB

### ISSUE THREAD

**Issue by dcbrown16** [microsoft/sample-app-aoai-chatGPT#235]
Hello, I'm in Azure Pro Direct support and we have a customer inquiry about the logging mechanism. We are reaching out here as best effort.
The customer is not receiving any logs from their app. We verified that when there are requests to the Web App resource, there is a similar number of requests to the Cosmos DB resource, so it seems that the connection is working, but there are no files created in the Cosmos DB app.
We also verified that all of these settings are present on the app.
・AZURE_COSMOSDB_ACCOUNT
・AZURE_COSMOSDB_DATABASE
・AZURE_COSMOSDB_CONVERSATIONS_CONTAINER
・AZURE_COSMOSDB_ACCOUNT_KEY

Any ideas for how to troubleshoot this would be appreciated. Our team does not have coding expertise but we can pass info on to the customer. You can also reach me internally for more details. Thanks!

**Comment by dcbrown16** [comment]
Taking this internal, but I will try to report back here if we resolve it.

**Comment by Shubhamj5** [comment]
Hey @dcbrown16,
I am currently struggling with using COSMOS DB parameters in the environment variables.
I have created the COSMOS DB for Mongo DB vCore.
But I can only see Connection String.

Could you please let me know what AZURE_COSMOSDB_ACCOUNT and AZURE_COSMOSDB_ACCOUNT_KEY denotes?

Also AZURE_COSMOSDB_DATABASE and AZURE_COSMOSDB_CONVERSATIONS_CONTAINER should be created manually from the azure portal -> cosmos for Mongo (created resource) -> Preview and Code there right?
