### ISSUE TITLE
Filenames are not returned in Citations - With semantic hybrid search with vector field in the index, the references are named as citation1, citation 2 and so on

### ISSUE THREAD

**Issue by howtodoml** [microsoft/sample-app-aoai-chatGPT#238]
When we use simple search with no vector field in the index, the references are retrieved as filenames:
 
<img width="622" alt="image001" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/103862974/18ea7395-9c52-4718-98bf-e4084f277a42">

 

When we use semantic hybrid search with vector field in the index, the references are named as citation1, citation 2 and so on:
 
<img width="607" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/103862974/e00c45eb-f322-467c-886e-47aedb784dab">

The image shows the comparison of the response from Vector index and simple index. The vector index when used does not return metadata and chunk_id (notice they are null). 
<img width="719" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/103862974/a556b0e4-506a-42f8-bd75-500d1c083d1a">

**Comment by sarah-widder** [comment]
Hi @howtodoml this was just fixed in #251 - thanks for bringing it up! Closing the issue for now.
