### ISSUE TITLE
Split AI resource from the other resources?

### ISSUE THREAD

**Issue by schraepf** [microsoft/sample-app-aoai-chatGPT#242]
Another sample project has options to separately place the OpenAI resource and the remaining resources. We're only approved for OpenAI in Canada East, but the deployment fails because some of the other resources aren't available in the region. Similarly, we can't deploy to US East because we aren't approved for OpenAI there yet.

**Comment by sarah-widder** [comment]
Hi @schraepf you can point your app to any Azure OpenAI resource (across regions and subscriptions) by providing the right resource endpoint and key. Just update the AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_KEY environment variables on the app service.

**Comment by schraepf** [comment]
Hi Sarah,

Thanks for the quick response on this. We have research POCs for the Air Force and Department of Defense that require data stay in the US, so the Canada East deployment doesn’t fit.

I’m also running into issues with sample projects from Microsoft that don’t require the OpenAI resource and cosmos DB resources be in the same region, and that’s not possible in Canada east. This is impacting our ability to demonstrate these concepts to our commercial customers.

Is there any availability in US East or US East 2 region for GPT-4 access?

Mike
________________________________

**Comment by lindazqli** [comment]
Hi Mike, GPT4 is available in East US and East US 2, please refer to the documentation here https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-models

**Comment by schraepf** [comment]
Hello,

In the link you sent it states that I must request access, which is the purpose of this email thread. Please see screenshot below:

[A screenshot of a black screen  Description automatically generated]

Can we please have access to GPT-4-32k in East US or East US 2?

Mike

Michael Schraepfer, CISSP, ITIL, AWS SAA, MCITP, MCSE, MCSA
Partner, CTO
Essendis
31 East Bridge Street | Suite 304 | Berea, OH 44017
440.202.9074
www.essendis.com<http://www.essendis.com/>
SBC ID: 002263271 | UEI: GZEHUQR13DE7 | CAGE: 9DX02

From: Linda Li ***@***.***>
Date: Thursday, September 14, 2023 at 7:53 PM
To: microsoft/sample-app-aoai-chatGPT ***@***.***>
Cc: Michael Schraepfer ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/sample-app-aoai-chatGPT] Split AI resource from the other resources? (Issue #242)

Hi Mike, GPT4 is available in East US and East US 2, please refer to the documentation here https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-models
