### ISSUE TITLE
Chat history dose not work with Google Authentication 

### ISSUE THREAD

**Issue by tanvlt** [microsoft/sample-app-aoai-chatGPT#247]
I enabled Chat history and it works well with default authentication (Microsoft Provider). But when i change to use Google the error occurs.
![Screenshot 2023-09-14 at 11 25 56 AM](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/16603146/c57326a0-bef6-4e81-b166-167154afa024)
When i check in browser debug, There is an 500 error with api /history/list.
And this is the app service console log.
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/16603146/4cd62101-cca3-496a-8cba-90d665102fce)

**Comment by sarah-widder** [comment]
Hi @tanvlt the chat history feature leverages the Microsoft Identity Provider to get the logged in user's user ID, which is used to store/retrieve/update entries in the CosmosDB for that user. You can see we fetch the user ID from the backend request header in this function: https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/backend/auth/auth_utils.py#L1 

To use another authentication provider, you would need to modify this logic to get a unique user ID for the logged in user from that provider. Then that ID can be used when interacting with the CosmosDB. 

Hope that helps!

**Comment by Brennan-Richards** [comment]
Hey, Sarah, will this also apply to AAD B2C added as an OIDC auth provider? It seems like the request from AAD B2C should include the same headers used in the application code that you pointed to, yet I experience the same "...CosmosDB is not working..." message. Any advice you can provide on reconciling the chat history feature with AAD B2C would be greatly appreciated by our team and customers!
