### ISSUE TITLE
ChatGPT 4 chatbot not working

### ISSUE THREAD

**Issue by CinderZhang** [microsoft/sample-app-aoai-chatGPT#249]
when I input "Hi", the following message appears:
**### Additional information: I saw an authentication error message flash through before the chatbot loaded.**

Error
There was an error generating a response. Chat history can't be saved at this time. If the problem persists, please contact the site administrator.
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/72751738/d988e574-4b03-4a81-bf3c-450b9247d589)
![gpt4_error](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/72751738/8860a15a-b82d-4b3b-b105-d25b90cc3841)

**Comment by nunes-bruno-m** [comment]
Could you check on the console if you have any error?
I have the same issue and I see an error saying:
net::ERR_INVALID_CHUNKED_ENCODING 200 (OK)

**Comment by CinderZhang** [comment]
> Could you check on the console if you have any error? I have the same issue and I see an error saying: net::ERR_INVALID_CHUNKED_ENCODING 200 (OK)

Where can I check the console? Or, where is the console?

**Comment by CinderZhang** [comment]
> I'm referring to the console in the developer tools of the browser, just press F12 or go to the settings -> more tools -> developer tools.

I see. There are more errors in my instance.
### Edge:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/72751738/7c088095-111d-4864-b79c-24c63cdb509d)

### Chrome:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/72751738/d1bb092b-a921-421b-ba52-63562fd91fae)

**Comment by CinderZhang** [comment]
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/72751738/d82080bd-16da-4d8c-9336-fe2bed21408e)

Playground does not even function properly. Could that be OpenAI cut the traffic from Azure?
Can someone comment on this? Thanks.

**Comment by CinderZhang** [comment]
Now, cannot deploy. After click on Deploy, the deploy window has been frozen there for more than 10 minutes. GPT4 works just fine and better than well on my local machine projects where I call OpenAI API. I guess I should go back to that instead of Azure OpenAI.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/72751738/ab517eff-0f77-4c1f-a699-e2e003b34dff)

**Comment by CinderZhang** [comment]
I did the following and seems to working:
- Scale up to P3V1
- Switch to East US 2 or East US. I had Central US previously, I believe.

**Comment by agrecaBAS** [comment]
We're still experiencing this issue after deployed and it seems to happen when the response or prompt would violate the content filter rules. From what we can tell this only started happening after we enabled Chat History. Prior to that we actually got the message saying it violated the content filter.
