### ISSUE TITLE
User role:"system" in extenstions API

### ISSUE THREAD

**Issue by HuapingLiu** [microsoft/sample-app-aoai-chatGPT#253]
looks the extensions API body messages property only support "role":"user", not "role":"system". This makes extensions API's functionality is limited to just find answer from your question based on your data, but hard to do other custom task.
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions-extensions

For example, I just want update the input sentence based on my own data. So I update the messages in body like 

```
    "messages": [
        {
            "role": "system",
            "content": "You are an AI assistant, only update the user input sentence base on my data and output the updated input, not need answer the question."
        },
        {
            "role": "user",
            "content": "What are the differences between Azure Machine Learning and Azure AI services?"
        }
    ]
```
    
I hope it could just update "What are the differences between Azure Machine Learning and Azure AI services?" a little bit and output it. But I got "The requested information is not found in the retrieved data. Please try another query or topic."
    
I hope we could have the system role input in extensions API. Or if you missed anything, please let me know.

**Comment by sarah-widder** [comment]
Hi @HuapingLiu, the "roleInformation" parameter can be used to guide the bot in terms of its role, domain, tone, etc. much like what you might often put in a "system" message. So you could try putting your instructions there. The "roleInformation" is incorporated into a much longer prompt including retrieved documents and instructions, so the model may not strictly adhere to the instructions you give. In general, the extensions API is built to answer questions based on your data and has not been tuned to support other custom tasks like the one you presented here.

**Comment by HuapingLiu** [comment]
Thank you, I tried to do a simple update on "roleInformation" parameter, like "You are an AI assistant that helps people find information. Just repeat what the user says.", looks it does not work.
No worries, if extensions API is built to answer questions, not for other goals, we could close this issue.
