### ISSUE TITLE
Only simple and semantic queryType seems working

### ISSUE THREAD

**Issue by mirkon90** [microsoft/sample-app-aoai-chatGPT#262]
I am using the 2023-06-01-preview REST API. According to the documentation, you could pass simple, semantic, vector, vectorSemanticHybrid or vectorSimpleHybrid as possible "queryType" values. However, every time that I use "vector", "vectorSemanticHybrid" or "vectorSimpleHybrid" the API returns 500. I get the same error if I try to pass whatever word different than "simple" or "semantic". In the body, I am passing the embeddingEndpoint, the embeddingKey and the vectorFields with the name of the field containing the embeddings.
What I am doing wrong?

**Comment by sarah-widder** [comment]
Hi @mirkon90 - can you share your full request body (minus the keys of course)? Make sure that your embedding endpoint is a full endpoint, e.g. ""https://<AOAI resource>.openai.azure.com/openai/deployments/<Ada deployment>/embeddings?api-version=2023-06-01-preview"

**Comment by mirkon90** [comment]
Hi @sarah-widder  you were right. In the body, I was using the full embedding endpoint, but I was missing the querystring parameter with the api-version. Adding that, the queryType is recognized correctly. Thanks!
As a suggestion, you could add a full endpoint example into the Readme.
