### ISSUE TITLE
AOAI ERROR

### ISSUE THREAD

**Issue by phfontes** [microsoft/sample-app-aoai-chatGPT#263]
Hello,
I am debugging the application locally and the attached message is showing.
Even if I go to the Azure Open AI resource > Explore > Quotas, it hasn't exceeded the limit.
How to reset or where to adjust to stop giving messages?
![Sem título](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/132704972/05b3948f-17db-4992-b0ea-fbe0475322ca)

**Comment by howtodoml** [comment]
> Hello, I am debugging the application locally and the attached message is showing. Even if I go to the Azure Open AI resource > Explore > Quotas, it hasn't exceeded the limit. How to reset or where to adjust to stop giving messages? ![Sem título](https://user-images.githubusercontent.com/132704972/268956427-05b3948f-17db-4992-b0ea-fbe0475322ca.png)

You need to make sure you stay within the model token limit of 8K (GPT-4).  Try GPT35-Turbo 16K
