### ISSUE TITLE
Is it possible to run the app without using the azure cognitive search service at all?

### ISSUE THREAD

**Issue by hassanb199** [microsoft/sample-app-aoai-chatGPT#274]
Basically, is there a way to make it so that it works without using Azure Cognitive Search? Thanks.

**Comment by VincentSchmid** [comment]
yes you can. By default it wont use it

**Comment by davidm00** [comment]
Yes, you can simply click deploy to a new web app in the Azure OpenAI studio without adding any data resources. @hassanb199 
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/43946287/1f152925-fa95-40ea-943a-25398881e6e6)
