### ISSUE TITLE
How to make OpenAI answer only withing the documents bound?

### ISSUE THREAD

**Issue by RicBruD4S** [microsoft/sample-app-aoai-chatGPT#289]
HI, I've configured the project with a temperature of zero and I still receive responses out of context; for example prompting questions such as "who is the president of the USA?" , the model first replies something like: "I don't know, there is no sources about that" but if I continue asking the same or somehow "forcing" the reply, at the end the model replies (sometimes after 2-3 times, sometimes after 6-10 times asking the same question). 
How can I limit the model in a definitive way to answer to in-bound questions and discarding anything else out-of-context?
I was thinking to something like if there is no reference for the answer, discard it anyway, but sometimes it happens that the model gives the wrong citation with a out-of-context answer, which is really problematic and erroneous.

Have you any idea on that? Thank you.

**Comment by wherewith** [comment]
There isn't really a set method to limit the model in that way. For almost all LLMs there's a way to "break" them and get out of context answers. You basically just need to have a very rigid prompt and add multiple sentences on how it should not answer questions unrelated to the documents. Also, some people have tried "post-prompting" or appending an additional prompt to user input messages. See https://community.openai.com/t/how-to-prevent-chatgpt-from-answering-questions-that-are-outside-the-scope-of-the-provided-context-in-the-system-role-message/112027 and https://community.openai.com/t/how-to-limit-question-results-to-proprietary-dataset/98708/2

**Comment by davidm00** [comment]
Hi @RicBruD4S, I second @wherewith's response and can also offer you some resources we have for configuring system message/prompt with Azure OpenAI. 

[Prompt Engineering](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/prompt-engineering)
[Prompt Engineering Techniques](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/advanced-prompt-engineering?pivots=programming-language-chat-completions)
[System Message Templates](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/system-message)

**Comment by RicBruD4S** [comment]
Ok thank you, I'll have a look into them! Thanks.
