### ISSUE TITLE
Authn authorization in Teams App

### ISSUE THREAD

**Issue by ButtersXO** [microsoft/sample-app-aoai-chatGPT#333]
I would like to integrate this sample app into Microsoft Teams as a personal app. Is there a way to enable the authorization flow within the Teams environment? The issue I'm encountering is that when I create a Teams app and upload it, I consistently encounter a blank screen with the error message "Refused to display 'login.microsoftonline...' in a frame because it sets 'X-Frame-Options' to 'deny'." I am unsure of how to implement this authorization method as a popup.

**Comment by marianocalero** [comment]
> [@marianocalero](https://github.com/marianocalero) Yes i did. With two different authentication flows. One for Teams in Browser and one for Teams App with Redirection and Popups

That's great to hear. 

@ButtersXO - by any chance is there any specific documentation or steps that you followed to get it working? Thanks!
