### ISSUE TITLE
Strictness Parameter

### ISSUE THREAD

**Issue by miggytrinidad** [microsoft/sample-app-aoai-chatGPT#338]
In the app.py, I can see that we have a parameter "strictness", where is this being passed onto? 

I don't see any documentation in Azure Cognitive Search that uses this parameter.

**Comment by sarah-widder** [comment]
Hi @miggytrinidad please see the documentation for Azure OpenAI On Your Data: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data#custom-parameters
