### ISSUE TITLE
Getting Error in response to every question.

### ISSUE THREAD

**Issue by VikashLalit** [microsoft/sample-app-aoai-chatGPT#342]
I am trying to setup this sample app in my local but it seems chat is not working.
For every question m getting response like attached image .
Error
'messages'
![16983038349464360633064917410336](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/149046133/3bee6bde-3331-4bf8-8694-74d1514122a4)

**Comment by sarah-widder** [comment]
Hi @VikashLalit please ensure you have all of the required environment variables set as described in the README

**Comment by VikashLalit** [comment]
Hi @sarah-widder ,
I followed README only for setting up all env variables.
Please confirm even if I'm trying to setup this in my local machine then also deploying this application to azure AI studio is mandatory for chat to work by running 'AZD up' .

Also where i can check the logs of the application.
