### ISSUE TITLE
AZURE_SEARCH_PERMITTED_GROUPS_COLUMN and other settings not well documented

### ISSUE THREAD

**Issue by SPSCS-Simon** [microsoft/sample-app-aoai-chatGPT#344]
Please and you update the documentation to clearly define the purpose of each Environment Variable.

Especially `AZURE_SEARCH_PERMITTED_GROUPS_COLUMN`  

Whilst we can try to walk the call tree in the `app.py` we assume assuming this will block access if the user does not have such a group membership?

Thanks!

**Comment by sarah-widder** [comment]
Hi @SPSCS-Simon this setting is used for document level access control - please see more detail in the documentation: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data#document-level-access-control 

If your Cognitive Search index is constructed with a permitted groups column, the setting will ensure that users of the app will only see responses based on documents in the index they have access to.

**Comment by hemastransform** [comment]
Hi i am currently looking into this option in my project, i am using this repository and the application is deployed from the ai foundry.  can you please explain this further? like in steps how to get this done? i have created a sharepoint column(groups_ids) for this i am using ADsecurity groups
