### ISSUE TITLE
Repeated text in answer

### ISSUE THREAD

**Issue by membersubs** [microsoft/sample-app-aoai-chatGPT#363]
Any idea why this is happening? I'm running locally. Azure Studio webapp works fine and the response is generated as expected - "Hello! How can I assist you today?" . Running locally generates the response seen below in the screenshot.

Screenshot:

![azure](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/137643969/8f917647-c348-4020-ab30-de2e6e7de6dd)

**Comment by sarah-widder** [comment]
Hi @membersubs are you using the latest code from main? Make sure you have the latest including the static files.

**Comment by membersubs** [comment]
Hi @sarah-widder , latest pull fixed the issue. Thank you!
