### ISSUE TITLE
Broken chat completion endpoint for bring your own data?

### ISSUE THREAD

**Issue by fellnerse** [microsoft/sample-app-aoai-chatGPT#384]
Hey,

since today my team experiences following problem:

when posting a valid request against the `extensions/chat/completions?api-version=2023-06-01-preview` endpoint we get this error message:

`{"error": {"requestid": "XXX", "code": 400, "message": "The data loss prevention feature will be supported soon."}}`
Does someone else experience the same?
If not what can I change to make it work again?

Note: the endpoints without `extension` in the path seem to work fine

Edit:

Minimal request to reproduce:

```bash
curl "https://<recource-name>.openai.azure.com/openai/deployments/<deployment-name>/extensions/chat/completions?api-version=2023-06-01-preview" \
		-X POST \
		-H 'api-key: <api-key>' \
		-H "Content-Type: application/json" \
		-d '{
  "messages": [
    {
      "role": "user",
      "content": "asdf"
    }
  ],
  "dataSources": [
    {
      "type": "AzureCognitiveSearch",
      "parameters": {
        "endpoint": "",
        "key": "",
        "indexName": ""
      }
    }
  ]
}'
```

It seems like the request is not even processed until it would post a request to azure cognitive search, as it does not matter if the params there are valid or not.

**Comment by aclouvel** [comment]
Hey @fellnerse , I think you have a networking issue when trying to connect to datasources (it is why it is working without the /extensions), try to put 
    "properties": {
      "restrictOutboundNetworkAccess": false
    }
in the OpenAi resource

**Comment by fellnerse** [comment]
Hey @aclouvel thanks for your answer!
you are right, it seems like the option never had any effect, and after some update on MS server side it was implemented...this is not like you would expect it to work but well not it works;

I assume this also applies to other services as well?

**Comment by sayedirfan** [comment]
hey @aclouvel , @fellnerse could you please tell where to set this 
"properties": {
"restrictOutboundNetworkAccess": false
}
thank you!

**Comment by aclouvel** [comment]
Param not available in the UI (but I think by default set to false), to be change via IaC deployment, az rest or REST API @sayedirfan
