### ISSUE TITLE
Titles of responding contents from the cognitive search?

### ISSUE THREAD

**Issue by ButtersXO** [microsoft/sample-app-aoai-chatGPT#388]
I am currently working with the Azure Cognitive Search service and have configured my environment using the 

AZURE_SEARCH_CONTENT_COLUMNS parameter as follows:
AZURE_SEARCH_CONTENT_COLUMNS="email|location|phone"

While testing, I noticed that the response from Cognitive Search is in the following format:
123@123.de\nengland\n+23123123

To enhance the clarity and usability of the response, I would like to request a modification so that the response is formatted as:

email: 123@123.de\nlocation: england\nphone: +23123123

This structured format, with labeled identifiers for each piece of information, would greatly improve the readability.

**Comment by sarah-widder** [comment]
Hi @ButtersXO thanks for raising this request. While formatting with the field names currently isn't supported, we do have an additional optional parameter for the fieldsmapping called "contentFieldsSeparator", which sets the separator between content from each field in the response. The default value is "\n". You could try setting this to another value (e.g. more whitespace/newlines) to make it more readable. Or, try setting this to a custom string, and implement some post processing on the citation returned to replace the custom string with the field names.

**Comment by ButtersXO** [comment]
Worked like charm, thx.
