### ISSUE TITLE
data.temperature must be valid exactly by one definition (0 matches found)

### ISSUE THREAD

**Issue by LV-Amit** [microsoft/sample-app-aoai-chatGPT#39]
We deployed the sample bot using one click, "Deploy to Azure," and it was terrific for the last few days. We added new data sources, and the preview works fine, but once deployed to the resource, we now get the error.

`data.temperature must be valid exactly by one definition (0 matches found)` but the `/conversation` request returns a 200.

Assuming there are constant updates to this preview, what recently changed to make this happen? 

We deployed the GPT-4 model and blob storage as a data source.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/136777361/a2809d75-1182-4071-aaf3-ff0991773a00)

**Comment by sarah-widder** [comment]
Hi @LV-Amit this issue should be fixed by #37, please try to pull in that change and try again.

**Comment by sarah-widder** [comment]
As the issue should be fixed, closing this thread. @LV-Amit please feel free to reopen if you update your app code and still get this issue.

**Comment by LV-Amit** [comment]
Thanks for the fix, @sarah-widder. Assuming that the one-click deploy pulls from the latest main when redeployed, it does not seem to have fixed the issue. I can still get results in the chat playground but not in the deployed app. This error only happens when assigning a data source, If I remove the source, it's back to normal.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/136777361/fc169ec3-bfb7-4247-8871-c148f6545192)

**Comment by LV-Amit** [comment]
Thanks, @sarah-widder - I had to manually sync the branch from the deployment center and redeploy. I can confirm that #37 has fixed the issue.
