### ISSUE TITLE
Azure web app- Need admin approval

### ISSUE THREAD

**Issue by aropenai** [microsoft/sample-app-aoai-chatGPT#403]
I get the below error when a user tries to open the deployed webapp. What permissions are required? I currently have the below 

needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it

**Comment by ross-p-smith** [comment]
I believe that you need to be Owner of the subscription otherwise RolePermissions are note created properly

**Comment by Epstone** [comment]
It depends how your Entra ID stuff is set up. You need the permissions as follows granted:
![grafik](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/1425860/e8423391-e270-433f-acbd-7ed773a5bfa1)

Those potentially need to be granted by your Entra admin.

**Comment by aaronba** [comment]
Also, if you set "Assignment Required" on your Enterprise Application, then any grants need to be handled by Admin consent.

More info is here in the docs.
https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/application-sign-in-unexpected-user-consent-prompt#view-user-assignment-settings.

**Comment by aropenai** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ARAJEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ARAJEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Microsoft Graph | email | View users' email address
-- | -- | --
Microsoft Graph | offline_access | Maintain access to data you have given it access to
Microsoft Graph | openid | Sign users in
Microsoft Graph | profile | View users' basic profile
Microsoft Graph | User.Read | Sign in and read user profile
Microsoft Graph | User.Read.All | Read all users' full profiles
Microsoft Graph | User.ReadBasic.All | Read all users' basic profiles



</body>

</html>
