### ISSUE TITLE
Apps cannot work suddenly

### ISSUE THREAD

**Issue by robinzhengwang** [microsoft/sample-app-aoai-chatGPT#404]
Hi,

I have run several apps successfully already.
But this morning, I found all of them cannot work with error:
{"error": "Expecting value: line 1 column 1 (char 0)"}

May I know what happened, any changes on the endpoint?

Thanks.

**Comment by npsquared** [comment]
We are experiencing the same issue. All resources on East US location. Was working fine until this morning. 
The index itself works ok as I am able to do a search against it. 
However, the web app returns an error. The playground returns an error. The indexing process using blob storage doesn't work either. 

Any indication on what might be happening. 

Thanks.

**Comment by robinzhengwang** [comment]
> We are experiencing the same issue. All resources on East US location. Was working fine until this morning. The index itself works ok as I am able to do a search against it. However, the web app returns an error. The playground returns an error. The indexing process using blob storage doesn't work either.
> 
> Any indication on what might be happening.
> 
> Thanks.

Also on East US location, but I can use playground, not sure what happened?

**Comment by npsquared** [comment]
> Also on East US location, but I can use playground, not sure what happened?

Are you able to attach your existing index in the playground and use it there?

**Comment by robinzhengwang** [comment]
> > Also on East US location, but I can use playground, not sure what happened?
> 
> Are you able to attach your existing index in the playground and use it there?

You are correct, I see the 
Error: no healthy upstream.
Same error from you?

**Comment by npsquared** [comment]
Yes, same error. 
I tried to rebuild the index using blob storage but the process just hangs for a long time and then errors out with the following: 
We couldn't connect your data
Could not execute skill because the Web Api request failed.

**Comment by robinzhengwang** [comment]
Can anyone help to give us some confirm? Thanks.

**Comment by npsquared** [comment]
@sarah-widder @pamelafox

**Comment by npsquared** [comment]
Our app started working momentarily and then stopped again. I guess there is something going on behind the scenes. 
When the app started working, the playground was also working. Then both stopped.

**Comment by sarah-widder** [comment]
Hi folks, we are investigating an issue causing service disruptions in East US at the moment. Other regions should be healthy if you're able to point your apps to resources in another region. We're working to resolve the issue as quickly as possible, appreciate your patience!

**Comment by sarah-widder** [comment]
Update: service has been restored in East US. Please let us know or submit a support ticket to Microsoft if you're still seeing failures in East US.

**Comment by robinzhengwang** [comment]
Thanks, it can work now.
