### ISSUE TITLE
CosmosDB with MongoDB vCore - Multiple Content Fields Separator

### ISSUE THREAD

**Issue by tsjdev-apps** [microsoft/sample-app-aoai-chatGPT#407]
I'm using [Azure OpenAI Studio](https://oai.azure.com) to create a copilot using an Azure CosmosDB with MongoDB vCore as data source. 

On the last step you need to specify the *Content data*. The hint below mentioned that you need to seperate the values by comma.

![Unbenannt-2](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/19834782/1a4bbe82-430f-4211-a6b1-f4fcea6fbae3)

This is working for the chat playground within the portal.

If you now deploy this app, it doesn't work.

![Unbenannt-1](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/19834782/78716827-372e-4c95-b3e6-307fff27977f)

The fix is pretty easy, because if you take a look at the `app.py` file you see that the seperator should be `|` instead of `,`. If you update these values a redeploy the application is it working. 

So please adjust the code in the `app.py` to accept `,` as seperator, because otherwise the chat playground is broken.

**Comment by sarah-widder** [comment]
This is fixed by #483
