### ISSUE TITLE
No chunks found. Please check the data path and chunk size.

### ISSUE THREAD

**Issue by HARISHKUMAR1112001** [microsoft/sample-app-aoai-chatGPT#41]
When I am trying to working with json dataset getting this error: "No chunks found. Please check the data path and chunk size."

**Comment by HARISHKUMAR1112001** [comment]
#42

**Comment by sarah-widder** [comment]
Hi Harish, as mentioned on the PR, JSON format data is not currently supported when using Azure OpenAI on your data. You may continue to use your JSON parsing changes to create your index but we will not pick up this change at this time, thanks for your understanding.
