### ISSUE TITLE
Chat stops responding

### ISSUE THREAD

**Issue by cyrilgarnea** [microsoft/sample-app-aoai-chatGPT#410]
When testing the app, the chat sometimes stop responding. The "AI-generated content may be incorrect" stops being displayed and no more interaction is possible.

Somehow, asking "tell me more" or similar query as a follow-up seems to trigger the behavior...

**Comment by metchick** [comment]
the same problem

**Comment by sarah-widder** [comment]
Hi folks, we recently fixed a bug that produced this behavior. #385 , #375 and #372 were the related fixes. Can you verify that your app is running the most recent code from main? If not, you can trigger a sync by going to the Deployment Center for your app service and clicking "Sync". When it completes, restart the app. Or, try deploying a new app from the studio.
