### ISSUE TITLE
Allow disabling identity provider requirement with an environment variable

### ISSUE THREAD

**Issue by Xtrah** [microsoft/sample-app-aoai-chatGPT#45]
Disabling identity provider authentication through an environment variable would be a great quality of life improvement.

Doing it manually in the code itself is easy, but also seems to require a bunch of additional steps to set up a new pipeline, hosting a new Docker image or manually getting the code onto an Azure Web App.

**Comment by entmike** [comment]
> Disabling identity provider authentication through an environment variable would be a great quality of life improvement.
> 
> Doing it manually in the code itself is easy, but also seems to require a bunch of additional steps to set up a new pipeline, hosting a new Docker image or manually getting the code onto an Azure Web App.

Where did you manage to disable the IDP?  I'm trying to run in a devcontainer but I am hit with the Authentication error when trying to run via `start.sh`.  This is after populating the `.env` as completely as possible.

**Comment by Mshz2** [comment]
@entmike @Xtrah Hi all, can I please ask how did you disabled the identity provider authentication requirements? just by converting "localhost" into "127.0.0.1"? because for me didn't work. I appreciate your help. Best

**Comment by Xtrah** [comment]
@Mshz2 this is what I did when I created the issue a month back: https://github.com/Xtrah/sample-app-aoai-chatGPT/commit/3981666ca802c55b161c6df49e3e2d39e95d3b4f

Be aware that the above fork is a few commits behind this repository now, so the code might have changed.

**Comment by ashutosh-suryawanshi-cloudaeon** [comment]
> @Mshz2 this is what I did when I created the issue a month back: https://github.com/Xtrah/sample-app-aoai-chatGPT/commit/3981666ca802c55b161c6df49e3e2d39e95d3b4f
> 
> Be aware that the above fork is a few commits behind this repository now, so the code might have changed.

@Xtrah The link seems to be unavailable now! Could you please guide us through all the changes you made to disable the IDP. I am still being redirected to Microsoft login page.

**Comment by iseabock** [comment]
Addressed in [436](https://github.com/microsoft/sample-app-aoai-chatGPT/pull/436)
