### ISSUE TITLE
Chat history and user management

### ISSUE THREAD

**Issue by Rassibassi** [microsoft/sample-app-aoai-chatGPT#46]
Hi,

Thanks for the great work.

I am wondering if there are any plans of moving the Azure Active Directory (AD) into the app, and building a per AD-user conversation archive just like we know it from the OpenAI ChatGPT interface. 

At the moment the AD seems to be done by an API gateway, and further for data persistence across sessions also some database would need to be integrated. We are implementing this into our organization and are considering such functionality, or are you lot already working on it? Is it in your backlog?

Also, which of the Microsoft implementations should we bet on? This repository or the one over [here](https://github.com/Azure-Samples/azure-search-openai-demo/tree/main)? Is one being deprecated over time?

Thanks, and all the best,
Rasmus

**Comment by sarah-widder** [comment]
Thanks @Rassibassi for your feedback! Tagging @NHaiby to comment.

**Comment by davidjrh** [comment]
Any update on this?

**Comment by lindazqli** [comment]
Hi @davidjrh, 

Thanks for your feedback following are answers / comments: 

Conversation archive & AAD database-- This is currently not available in our Web App but is on our roadmap. Please stay tuned! Until we support this you can customize your Web App and add it this functionality to your Web App. 

Repo -- both repos will be maintained. the two repo/products are developed for different purposes: this one is a hosted service as part of Azure OpenAI on your data where you don't need to worry about the technical details. It is easier to use and tune parameters and provides all the benefits of a cloud service. [Azure-Samples/azure-search-openai-demo: A sample app for the Retrieval-Augmented Generation pattern running in Azure, using Azure Cognitive Search for retrieval and Azure OpenAI large language models to power ChatGPT-style and Q&A experiences. (github.com)](https://github.com/Azure-Samples/azure-search-openai-demo/tree/main) is a sample of RAG and requires more implementation to include all logic in the app and offers more customizable features.

**Comment by sarah-widder** [comment]
Hi @Rassibassi and @davidjrh we just released an update including a chat history feature for the web app. Closing this thread :)

**Comment by davidjrh** [comment]
Wow! Thanks! Going to test it ASAP!
