### ISSUE TITLE
REQUEST : LIKE/DISLIKE button to be added

### ISSUE THREAD

**Issue by koichino** [microsoft/sample-app-aoai-chatGPT#471]
My customer wanted to analyze if answers are satisfying to users or now so that they can improve/ review indexes or something else.
So LIKE / DISLIKE button for answers would be better to add on UI as Copilot has to get feedback from users.

**Comment by sarah-widder** [comment]
Hi @koichino - this was added in #396 . The readme is updated with the environment variable needed to turn the feature on. Note that the CosmosDB for chat history is required to store the feedback.

**Comment by koichino** [comment]
[heart]         Kohei Ichinohe reacted to your message:
________________________________
