### ISSUE TITLE
API version 2023-07-01-preview breaks convo with data

### ISSUE THREAD

**Issue by tendau** [microsoft/sample-app-aoai-chatGPT#492]
Using the API preview version 2023-07-01-preview version errors out in the "stream_with_data" function

**Comment by sarah-widder** [comment]
Hi @tendau I would recommend using the 2023-08-01-preview version. As the API changes quickly, we won't always be backwards compatible with previous preview versions.

**Comment by tendau** [comment]
@sarah-widder thank you for the response and yes we upgrading and that is working just wanted to make sure the team was aware of this break. While I have you we have also been working on the needed changes to update to openai 1.6.1 and were wondering if your team had any plans on upgrading it or if you might be amenable to a PR with those changes made.

**Comment by sarah-widder** [comment]
@tendau in fact yes I have a PR #460 that bumps openai to 1.x so it will be upgraded soon!
