### ISSUE TITLE
Repeating characters at the end of the response

### ISSUE THREAD

**Issue by mc-code1** [microsoft/sample-app-aoai-chatGPT#513]
### Discussed in https://github.com/microsoft/sample-app-aoai-chatGPT/discussions/479

<div type='discussions-op-text'>

<sup>Originally posted by **mc-code1** January  3, 2024</sup>
Whenever I get a response, the last character of the response is repeated. For instance, in the screenshot shared here, the question mark is repeated twice. Is anyone else experiencing this issue too? Any tips for how to fix?

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/152879900/9730a727-5cac-4ce5-b6d6-c0327f9881a4)
</div>

**Comment by sarah-widder** [comment]
This has been fiixed!
