### ISSUE TITLE
Error message on the front end using cognitive search

### ISSUE THREAD

**Issue by rochaktarika123** [microsoft/sample-app-aoai-chatGPT#515]
I am getting an error when I use cognitive search on the front end only. While I can see from the network that I am getting a response from OpenAI. I have synced up the code as well so I have the latest code as of a few days back and the same code works locally on my laptop but it gives me this error the moment I deploy it on the Azure web app. Any ideas?

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/73043045/36d08c97-26d6-4b48-af2e-ca51ee45c17a)

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/73043045/c1d7ee2f-20d7-4a31-bcb8-1403cb778ab1)

**Comment by sarah-widder** [comment]
Hi @rochaktarika123 can you verify that the environment variable settings you have locally match the settings on the deployed app?

**Comment by rochaktarika123** [comment]
Thanks Sarah. There was an issue when I redeployed the latest build and this issue was in the previous build. This issue has been resolved now with the latest code.
