### ISSUE TITLE
How to access the chat history without the cosmos db enabled?

### ISSUE THREAD

**Issue by jainrahulsethi** [microsoft/sample-app-aoai-chatGPT#532]
Is it possible to access the chats that the users have had when I have not enabled the cosmos db instance on my webapp and also chose the do not store the history option while creating the app using the UI from the playground. Thank you.

**Comment by nrobert** [comment]
The data needs to be stored somewhere to be displayed later, so there is necessary a storage somewhere. This sample uses CosmosDb for it, so you need to enable it to get chat history.

**Comment by jainrahulsethi** [comment]
Thanks @nrobert
