### ISSUE TITLE
Feedback is not working

### ISSUE THREAD

**Issue by sgkalyans** [microsoft/sample-app-aoai-chatGPT#533]
Regarding the feedback feature, the thumbs up/down icons appeared but it is not capturing the feedback data to conversation database, receiving this error message "Entity with the specified id does not exist in the system." Not sure whether any issue on the messageId that send to backend API to update the message for feedback. 

Any idea how to resolve this ?

**Comment by beplay** [comment]
This seems to happen if the message is not properly stored in the CosmosDB, i.e., the feedback looks for a message with the corresponding 'id' and if not found you will get that error message. I observed this issue infrequently when running the app locally, however, when deployed to Azure, the messages were correctly stored and the feedback worked as expected.

**Comment by justynatk** [comment]
Same happened to me but only for the most recent message. If the feedback was provided for any of the previous system's responses or the chat was reloaded - it worked - and the feedback was saved to the database.

**Comment by sgkalyans** [comment]
For my case, it worked locally but not working when I deployed it to Azure.

**Comment by jasredyy5** [comment]
Any update on this issue? I am getting the same error "Entity with the specified id does not exist in the system." when running the app locally. Appreciate any inputs.

**Comment by eshwarhs** [comment]
I think the backend is not using the UUID generated by the frontend, but rather creating a new UUID and storing it in the db. The appContext is unaware of the change in UUID. I got it working on my deployment. @sarah-widder Can I take this up?

**Comment by sgkalyans** [comment]
The message ID inserted into DB and the message Id returned to frontend are not the same, that’s why this issue. If we load the chat history then it return the correct message id for the past chat and can do the feedback but not for new chat messages. Hi @eshwarhs, possible to share the fix details ? Thanks

**Comment by sarah-widder** [comment]
Hi @eshwarhs if you have a working solution, please do open a PR and we can take a look. I would also recommend testing thoroughly that the feedback is maintained across reloads, changing between conversations, sending additional messages, etc. Just to ensure that the state is being properly tracked in all parts of the stack.

**Comment by sarah-widder** [comment]
Hi folks #623 should have resolved this. @sgkalyans can you give it a try with that fix?

**Comment by sgkalyans** [comment]
Hi @sarah-widder , tested okay. Thanks for the follow up.
