### ISSUE TITLE
Azure Open AI Studio - Indexing process timing out since yesterday

### ISSUE THREAD

**Issue by npsquared** [microsoft/sample-app-aoai-chatGPT#546]
Hello, 
Is there an issue with Azure Open AI Studio? I have not been able to get the chat playground to ingest my data and create an index since yesterday. I've tried both the Azure Blob storage option and the Upload files option. The process gets stuck in the preprocessing phase and then times out after a long time. 

Any one else experiencing this issue? I am on 'East US' location. Process used to work fine previously. Total file size is only 12 mb. 
@sarah-widder

**Comment by sarah-widder** [comment]
Hi @npsquared thanks for raising this issue. The best way to get help for an issue like this is to raise a support request from Azure OpenAI studio - that will engage customer support to collect your resource information and debug the issue with you.

**Comment by npsquared** [comment]
Thanks for your response Sarah. The issue is with the Azure AI Studio in the East US location. The problem has gone away when we moved to an alternate location. Closing this issue.

**Comment by npsquared** [comment]
Thanks for your response Sarah. The issue is with the Azure AI Studio in the East US location. The problem has gone away when we moved to an alternate location. Closing this issue.
