### ISSUE TITLE
API Version 08-01-2023 Deprecation

### ISSUE THREAD

**Issue by Bahri-19** [microsoft/sample-app-aoai-chatGPT#556]
I have noticed that this repo uses the API version 08-01-2023-Preview which will be deprecated by April 1st, will there be an update for the new 12-01-2023-Preview API version? Also, this repo uses the old package of openai 0.26.* and we're currently at 1.6.0 (currently there is support for tool calling) which wasn't supported in an older version.

**Comment by sarah-widder** [comment]
Hi @Bahri-19 - #460 just updated to 2023-12-01-preview and openai 1.6.1 :)
