### ISSUE TITLE
UI bug - the plus sign acts as 'clear the conversation' instead of copying  

### ISSUE THREAD

**Issue by gw37** [microsoft/sample-app-aoai-chatGPT#557]
deployed a web app directly from Azure AI Studio on Monday 29-Jan-2024 and the "+" is doing the same thing as the "broom" icon.

**Comment by gw37** [comment]
this is with the conversation history enabled and a cosmosdb instance in place.

**Comment by sarah-widder** [comment]
Hi @gw37 , the "broom" will clear all of the messages from the current conversation entry, while keeping the conversation entry in the DB. The "+" will start a new conversation entry, keeping all of the previous messages in the previous conversation entry. Hope that clears it up!
