### ISSUE TITLE
The API deployment for this resource does not exist.

### ISSUE THREAD

**Issue by akashtalole** [microsoft/sample-app-aoai-chatGPT#56]
I am getting below error while send chat query

openai.error.InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

I have added below variables in .env with correct values
`AZURE_OPENAI_RESOURCE=
AZURE_OPENAI_MODEL=
AZURE_OPENAI_KEY=`

**Comment by sarah-widder** [comment]
Hi @akashtalole, were you deploying with `az webapp up`? In this case, you will need to subsequently update the environment variables on the app using `az webapp config appsettings set`. See more details here: https://learn.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set.

**Comment by akashtalole** [comment]
Thanks issue is resolved
