### ISSUE TITLE
Add (Azure) speech capabilities (STT / TTS)

### ISSUE THREAD

**Issue by iMicknl** [microsoft/sample-app-aoai-chatGPT#560]
Would be great to add (optional) voice capabilities to the sample app, based on a feature flag. Similar to what is currently available in the Azure OpenAI Playground.

**Components**
- Azure Speech to Text (after click / hold on input button)
- Azure Text to Speech (on streaming output, not just on the final answer)

**Requires:**
- Azure Speech deployment
- Back-end work to retrieve token (Managed Identity or Key) and pass a short-term access token
- Environment variables to enable / disable voice, set voice configuration 

**Open discussion**
- How to set the input language, via environment variables or in the interface?
- Should we use recognizeOnceAsync (one-shot) or continuous until user closes / a long pause is detected. Benefit of continous is that you can stream the input to the question field, where with one-shot you can only share the result.

**Comment by pamelafox** [comment]
If its helpful, the speech team contributed text-to-speech in a PR for our similar RAG repository here: https://github.com/Azure-Samples/azure-search-openai-demo/
The comments on that PR might also be helpful to see what developers have requested from the feature.
