### ISSUE TITLE
Sign-in error code 90094 for my colleagues

### ISSUE THREAD

**Issue by aagirre92** [microsoft/sample-app-aoai-chatGPT#572]
Hello there!

I have just deployed this application to Azure App service and it is working perfectly fine for me (only for me)

My tenant colleagues cannot access it (admin consent required error 90094 is presented to them, preventing them to access the web application).

**Side notes**:

- I have granted email, offline_access, openid, profile, User.Read and User.ReadBasic.All API permissions to the client. None of these require admin grant.
- I am using enterprise application too so that I can select which users from my tenant have access to this.
- Within Enterprise Appications > Consent and permissions > User consent settings the option "allow user consent for apps" is checked
- I have ensured that the publisher domain of the application is verified

I do not understand why this error keeps on popping to my colleagues, as this client does not require any permission that requires admin grant...

Any idea why this is happening? Thanks a lot!

**Comment by sarah-widder** [comment]
Hi @aagirre92 one thing to try is to remove the identity provider from the app service, and then add it back with a new app registration. Perhaps something about the default configuration of the app registration when deploying is not compatible with your tenant policies.
