### ISSUE TITLE
Chat history is not enabled warning, while chat history is not configured

### ISSUE THREAD

**Issue by iMicknl** [microsoft/sample-app-aoai-chatGPT#575]
Since https://github.com/microsoft/sample-app-aoai-chatGPT/pull/460, I receive the message that "Chat history is not enabled", even though I haven't configured this.

This is an optional feature, but it seems this is now enabled out of the box.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/1424596/a62d7c8f-4e2f-4498-a58d-7d3ef980adef)

**Comment by sarah-widder** [comment]
Yes, this is a bug. Working on a fix!
