### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cameronjy** [microsoft/sample-app-aoai-chatGPT#578]
New deployments of this web app from the Azure AI Studio Preview are resulting in an "Internal Server Error".  This occurs with or without deploying Chat History.

**Comment by AliKemalSahin** [comment]
Hi, i'm trying to pull this repository from azure app service but it's giving "internal server error". Is this general problem?

**Comment by jbrodsky-code** [comment]
I'm seeing the same behavior. App Service Logs and Diagnostic Logs do not show anything related to the error.

**Comment by sarah-widder** [comment]
Hi, we're looking into an issue with AI studio web app deployment. In the meantime, you can try to deploy from Azure OpenAI Studio.

**Comment by sarah-widder** [comment]
@cameronjy @jbrodsky-code You can also "rescue" your AI studio app by configuring the App Startup command like below:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/19666316/58de3204-fe35-4aaa-a594-5034b4443bc3)
Be sure to restart the app and give it a few minutes before trying again.

**Comment by jbrodsky-code** [comment]
Thanks, I'll give it a try.

**Comment by jbrodsky-code** [comment]
@sarah-widder That startup command worked.  Thanks again!

**Comment by mathiastnielsen** [comment]
Worked for me to :)

**Comment by kichul5252hey** [comment]
it worked well Thx b.
I was struggling with persistent 'internal errors' during local deployment, but I managed to resolve the issue using the method described above.

**Comment by kagoolastha23** [comment]
I am getting this error as well
