### ISSUE TITLE
Error with showing html code

### ISSUE THREAD

**Issue by lichengxihuang** [microsoft/sample-app-aoai-chatGPT#580]
With the latest deployment, it seems cannot show the html code exactly.

Below is an example when I ask it to give me an simple html document.

```
Certainly! Below is a simple example of an HTML document that displays a webpage with a heading and a paragraph:


   <h1>Welcome to My Webpage</h1>
   <p>This is a simple HTML example.</p>

```

**Comment by sarah-widder** [comment]
Hi @lichengxihuang can you describe in more detail what you want to happen in response or the display, and share a screenshot of what you're seeing? Generally it's not recommended to directly render HTML generated by the model, since users may try to abuse the system and get the model to generate something malicious, or the model may miss some syntax and end up crashing the page.

**Comment by lichengxihuang** [comment]
I think this is because the html tags are not rendered correctly.
Here is what I get:

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/43096483/b0e0b731-53d2-4b5d-a81b-897a7c0f5ca1)

**Comment by lichengxihuang** [comment]
> Hi @lichengxihuang can you describe in more detail what you want to happen in response or the display, and share a screenshot of what you're seeing? Generally it's not recommended to directly render HTML generated by the model, since users may try to abuse the system and get the model to generate something malicious, or the model may miss some syntax and end up crashing the page.

However, when I use the Azure OpenAI Studio Chat Playground, it works fine.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/43096483/ce018715-0291-4960-a9ca-21c142db5bfc)

**Comment by wpitallo** [comment]
I am also having this issue. I have looked at the response packet generate. 

The message content does exist eg:

```
   "messages": [
                {
                    "role": "assistant",
                    "content": " methods"
                }
            ]
```
But the content in this example: "methods" is not written the ui. Its just blank.

One thing I noticed is that there are multiple methods with the same created timestamp.

```
{
    "id": "chatcmpl-8syzo9azZ2A236kKf9KRvAK2mGaLm",
    "model": "gpt-4",
    "created": 1708114872,
    "object": "chat.completion.chunk",
    "choices": [
        {
            "messages": [
                {
                    "role": "assistant",
                    "content": ","
                }
            ]
        }
    ],
    "history_metadata": {
        "title": "please create a vue component",
        "date": "2024-02-16T20:21:10.334623",
        "conversation_id": "015eebb9-71b1-4040-a649-572a99d48659"
    }
}{
    "id": "chatcmpl-8syzo9azZ2A236kKf9KRvAK2mGaLm",
    "model": "gpt-4",
    "created": 1708114872,
    "object": "chat.completion.chunk",
    "choices": [
        {
            "messages": [
                {
                    "role": "assistant",
                    "content": " methods"
                }
            ]
        }
    ],
   ```
   
Notice: 
```
"created": 1708114872,
```

Is the same in both. Not sure if this is used to somehow to render the message and if its skipping the message if the created timestamp has already been rendered. Have not had a chance to investigate and confirm so just a guess at this point.

**Comment by wpitallo** [comment]
Def something wrong though with how the chunks are being written to the UI.
