### ISSUE TITLE
I am having trouble with the chat history not displaying properly

### ISSUE THREAD

**Issue by mitsu07** [microsoft/sample-app-aoai-chatGPT#585]
I'm having trouble with the following: When I enter a chat, it displays fine, but after refreshing the browser, the chat history shows the questions and answers in reverse order, or the answers disappear. I would like to know why this is happening. I know it's a lot to ask, but I appreciate your checking into this.

![test1 2024-02-05 152550](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/158248853/115c35c6-6751-4ca6-9d22-e0342effbd3c)
![test1_2 2024-02-05 152550](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/158248853/f3a0e55e-7f02-4aa3-9aad-13a4eb7e1c04)
![test2 2024-02-05 152550](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/158248853/33aa5022-be89-4335-b66a-ac51be20a7ae)
![test2-2 2024-02-05 152550](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/158248853/e1fb193a-38cf-4fef-9e3e-04f587301c35)

**Comment by nrobert** [comment]
FYI I also faced a similar behavior on Friday after the latest updates - having the messages being in reverse order

**Comment by mitsu07** [comment]
@iseabock  Yes. I'm still experiencing the behavior.   Our platform has already applied the latest update.

**Comment by iseabock** [comment]
Hi @mitsu07 Can you give me more details on your app? Are you running locally, deployed from Azure Studio, Azure OpenAI Studio? model? api version? etc. Thanks!

**Comment by sarah-widder** [comment]
Hi @mitsu07, @nrobert - can you share more details on how/when you're encountering this error? 
- Is it consistent? 
- What commit of the app code are you running?
- Do you see it locally, in the deployed app, or both?

**Comment by nrobert** [comment]
Hi @sarah-widder 

Not anymore on my side, it was 3 weeks ago when you pushed the asynchrony changes
