### ISSUE TITLE
Unclosed client session error

### ISSUE THREAD

**Issue by beplay** [microsoft/sample-app-aoai-chatGPT#593]
First of all, many thanks to @sarah-widder et al. for providing this sample, it helped us greatly to deploy a custom chat solution!

We merged the latest changes, especially the major refactoring that included an upgrade from Flask to Quart. While the changes seem to work, we now get an error when running the chat locally:

`ERROR:asyncio:Unclosed client session`
`client_session: <aiohttp.client.ClientSession object at 0x7f822a653a90>`

This message appears only when generating a response and not while e.g., loading/refreshing the web app:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/18634262/efec0a55-931f-4be8-a295-24e83e0939a3)

This message seems to be generated by Quart, however without any references to where in the code this error is triggered. Not sure if this relates to the `cosmos_conversation_client.cosmosdb_client.close()` method not being called after e.g., an error? Or is Quart somehow not closing open `ClientSession`s although I could not find a reference in the code?

Any guidance is appreciated!

**Comment by Epstone** [comment]
Same problem here. After the update to #16be120 we see many of these entries in the log. Any ideas?
![grafik](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/1425860/7fc2afaf-3a32-4559-867c-3b097cb660b2)

**Comment by Epstone** [comment]
The error is gone when cosmos db feature is deactivated. Potentitally something with my configuration. But indeed some log output may be missing on error.

**Comment by beplay** [comment]
Closing this thread and continuing in #751
