### ISSUE TITLE
we sometimes face `An error occurred. undefined` error at `Chat.tsx / makeApiRequestWithCosmosDB func`

### ISSUE THREAD

**Issue by KazuOnuki** [microsoft/sample-app-aoai-chatGPT#596]
when debugging, it appears that while the decoded value itself is being returned, the error is occurring due to parsing failure when the JSON of each child element within the 'objects' array, split by newline characters, is not in a complete form that can be parsed by `JSON.parse`.

//  where the `An error occurred. undefined error` is being triggered.
![db4941f5-1dde-4988-9625-d330950437e5](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/93357408/73e8199f-7da3-4e0a-bd87-fdea7159db16)

// when executing `JSON.parse` returned `obj` above
![df7cd9ea-3f42-4569-b931-14e506da0b29](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/93357408/f4ac60ec-0f1c-4f06-a18a-f05ac0e484ea)

Would you pls check it?

**Comment by sarah-widder** [comment]
Hi @KazuOnuki I have a possible fix in #599 if you want to take a look. I haven't been able to reproduce this consistently on my side, if you would be able to pull in the changes and give it a try in your app, that would be very helpful to validate that this addresses the issue.

**Comment by KazuOnuki** [comment]
Hi @sarah-widder thank you for considering prompt fix. I'll try it.

**Comment by KazuOnuki** [comment]
HI @sarah-widder , I checked it now, It seems it works fine. I think your fix is great.
by your fixed code, incomplete JSON parsing  is skipped. 
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/93357408/43e8e8f7-7134-4603-8e23-e2e9c3b1a038)

**Comment by Shubhamj5** [comment]
Hey @KazuOnuki,
I am currently struggling with using COSMOS DB parameters in the environment variables.
I have created the COSMOS DB for Mongo DB vCore.
But I can only see Connection String.

Could you please let me know what AZURE_COSMOSDB_ACCOUNT and AZURE_COSMOSDB_ACCOUNT_KEY denotes?

Also AZURE_COSMOSDB_DATABASE and AZURE_COSMOSDB_CONVERSATIONS_CONTAINER should be created manually from the azure portal -> cosmos for Mongo (created resource) -> Preview and Code there right?

Thanks

**Comment by KazuOnuki** [comment]
@Shubhamj5  this issue is closed so, would u mind if you creating NEW issue or discussion for more investigation? 
the environment variables(`AZURE_COSMOSDB_ACCOUNT`, `AZURE_COSMOSDB_ACCOUNT_KEY`, `AZURE_COSMOSDB_DATABASE`, `AZURE_COSMOSDB_CONVERSATIONS_CONTAINER`) is used for saving chat history, and this parameter is probably for Azure COSMOS DB for NoSQL not COSMOSDB for Mongo DB vCore. [code here](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/49fb343ce1d26b92371be9ea2543c069e8703a4e/app.py#L269) or [here](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/49fb343ce1d26b92371be9ea2543c069e8703a4e/app.py#L119)
At least, I've never specify Mongo DB vCore resource info at these parameter.
if you want to know about it in detail, could you pls raise issue.
