### ISSUE TITLE
Unable to update front end UI from azure CLI command

### ISSUE THREAD

**Issue by qzhang25** [microsoft/sample-app-aoai-chatGPT#597]
I forked the repo and gitclone into my azure shell.  I made changes in the frontend, Chat.tsx file. 

Then I run az webapp up --name test123 --resource-group group1,  and I still get the default UI.  

Is there a way to fix this by using Azure CLI? 
<img width="1682" alt="Screenshot 2024-02-06 at 11 02 33 PM" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/25287237/dc9bebfd-c683-464a-9340-3e7c8eea9e97">
<img width="1274" alt="Screenshot 2024-02-06 at 11 03 39 PM" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/25287237/f952d874-5185-46c2-ae75-23b372c603a2">

**Comment by qzhang25** [comment]
The chat should be like Starttest davidzhang chatting right?

**Comment by beplay** [comment]
After a code change in the frontend, you should first run the start.sh or start.cmd skript. Check the [note in the README](https://github.com/microsoft/sample-app-aoai-chatGPT?tab=readme-ov-file#deploy-with-the-azure-cli) for details.

**Comment by qzhang25** [comment]
@beplay Thanks for helping,  but I faced this issue below which failed to build the frontend.  
<img width="1945" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/25287237/aaf5d4e8-5bb9-406b-91a3-1e76d2cee7b9">

**Comment by CaptainBukko** [comment]
I'm having the same issue.  I was able to get past that error by supplying the command "export NODE_OPTIONS="--max-old-space-size=8192"" before running start.sh.  That said, not I get an error about building the back end saying I need to run "apt-get install python3-venv" which cannot be done from Kudu (BASH).  I'm pretty new to all this so possibly there's an easy fix.
