### ISSUE TITLE
Issue while running prepdocs.py script 

### ISSUE THREAD

**Issue by VikashLalit** [microsoft/sample-app-aoai-chatGPT#598]
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

  0%|                                                                                                                                                | 0/1 [00:01<?, ?it/s]

Traceback (most recent call last):

  File "C:\Users\vk\git\sample-app-aoai-chatGPT-main\scripts\prepdocs.py", line 233, in <module>

    create_and_populate_index(

  File "C:\Users\vk\git\sample-app-aoai-chatGPT-main\scripts\prepdocs.py", line 137, in create_and_populate_index

**Comment by VikashLalit** [comment]
@sarah-widder Can you please help me for above mentioned issue .

**Comment by VikashLalit** [comment]
@sarah-widder Hi , Can you please suggest for above mentioned issue . Its coming while running prepdocs.py

**Comment by Neil-Schneider** [comment]
Are you behind a corporate firewall? You might need to add your corporate CA cert to your Python CA file.

**Comment by VikashLalit** [comment]
@Neil-Schneider yes i am under corporate firewall and app is working fine in my local machine. Its just that after deploying it to azure chat is not working and m getting above error in logs.

I have already created vnet and confirmed that in my app service resource, also enabled access to this web app from selected networks..
