### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by guitaliba** [microsoft/sample-app-aoai-chatGPT#60]
Hello! I'm trying to modify the landing page to another language (pt-br). For example, we would like to change "Start Chatting" to "Faça a sua Pergunta", and other page details.
We are deploying the solution through Azure OpenAI Playground, clicking on "Deploy to Web App" button. 
Any chance to modify the source files through FTP or VSCode, directly on Azure Web App?

Thanks in advance!

**Comment by sarah-widder** [comment]
Hi @guitaliba to make changes to your app, you can clone this repo and make your changes to the frontend files (in your case, I think primarily Chat.tsx). Then follow the README instructions to build the app locally, and then deploy the app. The Azure CLI instructions may be easiest for deploying to an existing app published from the AOAI Playground.

**Comment by guitaliba** [comment]
Thanks a lot Sarah, worked like a charm!
