### ISSUE TITLE
Using WebApp.DockerFile getting error: "no module named gunicorn"

### ISSUE THREAD

**Issue by QuentinAd** [microsoft/sample-app-aoai-chatGPT#600]
**Describe the bug**
During deployment using WebApp.DockerFile getting error: "no module named gunicorn"

**To Reproduce**
1. run docker build on the WebApp.DockerFile
2. run docker run on the built image

**Expected behavior**
Expected gunicorn to start

**Configuration: Please provide the following**
 - Ran on WSL Ubuntu on local posix machine

**Additional context**
I have applied a fix in the docker file, to pip install gunicorn instead of uwsgi which is the following:

Fix:
Line 21: && pip install --no-cache-dir gunicorn
 
Previous state:
&& pip install --no-cache-dir uwsgi

**Comment by sarah-widder** [comment]
Hi @QuentinAd - in addition to installing gunicorn, you can try modifying the last CMD line to `CMD ["gunicorn", "app:app"]`. We're working on fully validating these changes and will push a fix to the Dockerfile soon.

**Comment by nrobert** [comment]
@QuentinAd  see my #602 post about an additional issue, where I fixed this "no module named gunicorn" issue by adding gunicorn to the requirements.txt file

**Comment by QuentinAd** [comment]
@sarah-widder,

## gunicorn.conf.py
### Added the missing 80 in the bind

```
import multiprocessing

max_requests = 1000
max_requests_jitter = 50
log_file = "-"
bind = "0.0.0.0:80"

timeout = 230

num_cpus = multiprocessing.cpu_count()
workers = (num_cpus * 2) + 1
worker_class = "uvicorn.workers.UvicornWorker"
```
