### ISSUE TITLE
Can not see the history button 

### ISSUE THREAD

**Issue by ayoubazaouyat** [microsoft/sample-app-aoai-chatGPT#612]
**Describe the bug**
I have created a cosmodb resource ( I am using a one generated by AI Studio), Also added the variables. but when deployed I cant see the button it says it is not Configured

**Configuration: Please provide the following**
 - Azure OpenAI model name and version : GPT-4 1106-Preview 
 - Is chat history enabled : yes
 - Are you using data? If so, what data source? Azure AI Search

**Comment by thomas-schertler** [comment]
In my case the history button disappears, if UI_SHOW_SHARE_BUTTON is set to false

**Comment by sarah-widder** [comment]
@ayoubazaouyat you have added the cosmosdb account name, database, container, and account key? Can you see from backend logs whether an error is returned in the initial `/ensure` call?

**Comment by ayoubazaouyat** [comment]
@sarah-widder yes it return a 404 
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/58346743/2d837e1e-6e1d-46ff-b934-6195d95300e4)

**Comment by ayoubazaouyat** [comment]
@thomas-schertler i have the `UI_SHOW_SHARE_BUTTON` set to true

**Comment by ayoubazaouyat** [comment]
I have managed to solve the problem, with writing the value of cosmosdb account name, database, container, and account key in `app.py` directly to the variable and remove the `os.environ.get`. this fix doesnt make much sense to me as the other env variables are working fine. but now it working.
