### ISSUE TITLE
start.cmd missing port parameter & bad mime-type configuration js module

### ISSUE THREAD

**Issue by Epstone** [microsoft/sample-app-aoai-chatGPT#617]
**Describe the bug**
- start.cmd is missing the correct port parameter for starting the backend (and potentially also the reload flag) - `call uvicorn app:app  `
(compare to start.sh)
- After fixing this I cannot open the chatbot in the browser locally because of some wrong mime type configuration security issue. Same in Chrome and Firefox. See screenshot. 
-
**Screenshots**
![grafik](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/1425860/c3bc77a8-b01a-470e-be2e-641a1a17004e)

Thanks for your effort!

**Comment by NeliasGer** [comment]
Does anyone have a solution for this problem? I have the same problem.

**Comment by Epstone** [comment]
@sarah-widder  Thanks for the port fix! 

mimetype:
Weird, I just switched branches, executed `npm run watch` in the frontend folder, and now the frontend_settings file is loading. So cannot reproduce for now. It is working now here. I will keep you posted if I see it again. 

@NeliasGer 
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/1425860/c8cb1b96-e486-4143-822c-c7ea9a9a0df7)
That is how it looks on the headers here now.
It could have been also old cached files on the repo, so maybe git cleanup could help as well.
