### ISSUE TITLE
Add configuration variables to set logo sizing to UI_LOGO and UI_CHAT_LOG

### ISSUE THREAD

**Issue by guyyardeni** [microsoft/sample-app-aoai-chatGPT#620]
*Is it possible to expand the UI variables (which are fantastic, thanks!) to include logo sizing? When using a logo that's not the same size as the contoso logo, it would be great to be able to increase the size so the logo presents correctly.

**Comment by iMicknl** [comment]
This is mainly applicable to the `UI_CHAT_LOGO`, right? The horizontal logo size is not hardcoded for both logo's. Do you have an example of what you would like to see different? What CSS tweaks would you like to see? 

- The header logo has a height of 32px (max height of the header bar) and will scale automatically in the width.
- The chat logo has a height of 62px, and will scale automatically in the width.

**Comment by guyyardeni** [comment]
Thanks for the reply. Given the auto width setting in the CSS, no changes are needed. Closed issue.
