### ISSUE TITLE
Guidance on creating a Stored Procedure for Chat History in Azure Cosmos DB account

### ISSUE THREAD

**Issue by jegberin** [microsoft/sample-app-aoai-chatGPT#640]
Could you provide a feature that will automatically delete all chat conversations and messages for all users, from the Cosmos DB older than XX days?

Or some guidance on how we can create a Stored Procedure (or other solution) that will facilitate this need?

**Comment by justynatk** [comment]
you can actually set this in the CosmosDB resource directly in the settings of the container under "Time to live"
