### ISSUE TITLE
Unterminated string starting at: line 1 column 217 (char 216)

### ISSUE THREAD

**Issue by chkrause** [microsoft/sample-app-aoai-chatGPT#646]
**Describe the bug**
I used Azure AI Studio to deploy the application, In the Playground of Azure AI the Chat works as expected in the deployed application I receive the following error:

**Screenshots**
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/40870406/1c5de6fe-1ba1-4862-a13c-2eaeea958183)

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/40870406/e95e6a85-48f5-421a-9bf0-24620596d12b)

**Comment by hnabbasi** [comment]
I am seeing this in one of my apps as well. Seems like Python error. See screenshots attached,
![Screenshot 2024-05-22 at 2 38 06 PM](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/12173156/fd9dadf1-269b-4cea-92b4-4cb157873746)
![Screenshot 2024-05-22 at 2 37 41 PM](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/12173156/123d4c8c-77c9-4045-a89d-4e4bfc9a27cd)
![Screenshot 2024-05-22 at 2 36 03 PM](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/12173156/74829ae3-1f56-4737-bfd8-9f973dfccd74)

**Comment by haritha91** [comment]
Having the same issue. Any work arounds to solve this?

**Comment by wdavidcamden** [comment]
I'm having the same issue as well. It seems to be related to a particular prompt and an index with my data I am using.
