### ISSUE TITLE
Clearer Instructions on how to turn off authentication

### ISSUE THREAD

**Issue by Grantglass** [microsoft/sample-app-aoai-chatGPT#65]
Hello,

I am trying to change the authentication on the app, so anyone can access it, but it is confusing on how to do this. There is some documentation, but it does not tell you what exactly needs to be changed:

Add an identity provider
After deployment, you will need to add an identity provider to provide authentication support in your app. See [this tutorial](https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service) for more information.

If you don't add an identity provider, the chat functionality of your app will be blocked to prevent unauthorized access to your resources and data. To remove this restriction, or add further access controls, update the logic in getUserInfoList in frontend/src/pages/chat/Chat.tsx.

What logic in the Chat.tsx needs to be adjusted?

**Comment by Br-Al** [comment]
1. Disable authentication on your Azure app service
2. Update the getUserInfoList on frontend/src/pages/Chat.tsx
3. And Voila
`    const getUserInfoList = async () => {
        // const userInfoList = await getUserInfo();
        // if (userInfoList.length === 0 && window.location.hostname !== "127.0.0.1") {
        //     setShowAuthMessage(true);
        // }
        // else {
        //     setShowAuthMessage(false);
        // }
        setShowAuthMessage(false);
    }
`

**Comment by james88080** [comment]
I tried updating the .tsx file but the .js.map file isn't updating. Is there anything I missed out?
