### ISSUE TITLE
Error Message In App - when Running App Locally in a Docker Container using the ./start.sh command.

### ISSUE THREAD

**Issue by bsonnek** [microsoft/sample-app-aoai-chatGPT#660]
**Describe the bug**
I am currently getting the error message below, after asking a question in the web app. This is ONLY when running the app locally in a docker container using the ./start.sh method to launch the app locally.

**I do not get the error message below when using the ./start.cmd command running locally without a docker container.**

ERROR Message:

Error
There was an error generating a response. Chat history can't be saved at this time. Error code: 400 - {'error': {'requestid': '75b97be4-56f7-4d1e-a4d6-b9c5a36a3307', 'code': 400, 'message': 'Failed to get managed identity token. Response: {"error":{"code":"ManagedIdentityIsNotEnabled","message":"Managed Identity (MI) is not set for this account while the encryption key source is \'Microsoft.KeyVault\', customer managed storage or Network Security Perimeter is used."}}'}}

**To Reproduce**
1. Clone repo locally
2. add your .azure and .env folder/files to root
3. Build repo in Dev Container
4. Open Terminal - Run ./start.sh
5. Ask any question int the web app.
6. You should now see a red box with the error message I posted.

**Expected behavior**
I should receive a response to my question in the app.

**Screenshots**
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/10324197/8c316df1-98bf-461b-b521-cb1d446a61d3)

**Configuration: Please provide the following**
 - Same configuration works fine without a docker container.

**Additional context**

**Comment by sarah-widder** [comment]
Hi @bsonnek - are you using key-based auth (passing the AZURE_SEARCH_KEY env variable) in both scenarios? It looks like the docker container environment may be missing the key, so managed identity auth to the AI search resource is being attempted, but the search resource is not configured properly for this.

**Comment by bsonnek** [comment]
Hi @sarah-widder - Thank you for the quick response and all your hard work on this project! I greatly appreciate it!

I do have the AZURE_SEARCH_KEY=  variable in my .azure/folder/.env file and also is the same variable that is in the .env in the root of the repo. My other env variables seem to be loading since I do get my CosmosDB History results. 

Would I be missing the value in any other location?

Thank you!
Blair

**Comment by bsonnek** [comment]
@sarah-widder  - No need to spend any time on this from your end. 

There is an issue with my .env file in the .azure/folder/.env file.  I copied all the variables from my .env in the root of my repo and replaced the same variables in the .azure/ env variables. I no longer get the error message and my issues are resolved.  

Thanks again for all your help. I'll close this out.
