### ISSUE TITLE
UI customization via environment variables works locally but not when deployed via azure cli

### ISSUE THREAD

**Issue by drobbins-ancile** [microsoft/sample-app-aoai-chatGPT#685]
**Describe the bug**
Per the README I've created a .env file using the env.sample file and modified the `UI_` variables to change the logo, title, and description. I've run `bash start.sh` to build and run the app successfully. I can see the UI modifications when hitting the app locally (http://127.0.0.1:50505). 

After building the app I have deployed it to Azure using the [instructions in the README](https://github.com/microsoft/sample-app-aoai-chatGPT?tab=readme-ov-file#deploy-with-the-azure-cli).

The app is deployed successfully and It works when I go to the URL for the web app. However, it does not show my UI modifications. It still shows the stock "Contoso" branding.

Is the README incorrect? Is there something else I need to do to get my local modifications deployed to the webapp in azure?

**To Reproduce**
1. clone the repo locally
2. copy .env.sample to .env
3. update the `UI_` env variables in the .env file
4. run `bash start.sh` to build and run the app
5. browse to the app running locally and verify the UI changes were made
6. kill the locally running app and run the two az cli commands [here](https://github.com/microsoft/sample-app-aoai-chatGPT?tab=readme-ov-file#deploy-with-the-azure-cli)
7. configure an identity provider for the newly created app in the azure cli
8. browse to the web app URL
9. verify standard "Contoso" branding

**Expected behavior**
The UI modifications that work locally should be reflected in the deployed web app.

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-35-turbo-16k, version 0613')
 gpt-35-turbo
 - Is chat history enabled?
 no
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc)
 no

**Additional context**
None

**Comment by gabrielsusai** [comment]
When you deploy the app, the new configuration keys don't get exported to the existing app. Make sure you have the keys in the configurations, if not add them and restart the app.
<img width="368" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/2603374/5a74adf4-31d2-4158-a4aa-e8c36c547cb4">

**Comment by Richard-ANX** [comment]
can you please clarify: only the keys, or the values included? 
im asking because i´m not sure if you mean the values will be synched from the code

thank you

**Comment by gabrielsusai** [comment]
@Richard-ANX You need to add both the keys and values. For example, the UI configuration keys were recently added and you could see them in the .env.sample but when you deploy the app, these keys don't get exported. So, you need to go to the Configuration in Azure and add these key and values for the application to use it. You may need to restart the app service.

**Comment by Richard-ANX** [comment]
thank you for your reply!
that worked for me!
