### ISSUE TITLE
Code Snippet Rendering Issue: HTML Entity Conversion for Less-Than Symbol

### ISSUE THREAD

**Issue by jegberin** [microsoft/sample-app-aoai-chatGPT#689]
**Describe the bug**
We have encountered a recurring issue within our web application where code snippets are not being displayed correctly. Specifically, the less-than symbol ('<') is being converted to its corresponding HTML entity ('<') when rendered on web pages, which is causing confusion and misinterpretation of the code presented to our users.

Examples of the Issue:

When displaying a C# for loop, the less-than symbol in the loop condition is being converted, resulting in incorrect display:

Expected: ` (int i = 0; i < 5; i++)`
Actual:  `(int i = 0; i &lt; 5; i++)`
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/117689604/4b1f78d2-fa21-4bae-bb7e-761bfbff73ed)
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/117689604/bca7dbb9-7420-4fdd-adf9-ddd0c22fa253)
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/117689604/5ec2a184-e74a-4dbd-adce-91c5f2cb353d)

**To Reproduce**
The issue does not occur in OAI Playground. 
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/117689604/a0ec842a-cb53-4770-acac-ae6f95a89f46)

**Configuration: Please provide the following**
-  Issue is encountered regardless of version gpt-4 1106-Preview and 0125-Preview. 
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc) No

**Comment by MoellerAI** [comment]
@iseabock this still doesn't work as intended. The code should be formatted using react-syntax-highlighter when there is a block of code, not when single symbols are mentioned, e.g. if the chatbot answers something inside `` as the example also shows in the PR. also my < sign is still renedered as raw hml inside the code blocks.
