### ISSUE TITLE
API version needs to be updated

### ISSUE THREAD

**Issue by tkudo-ms** [microsoft/sample-app-aoai-chatGPT#695]
**Is your feature request related to this sample app, or to an Azure service, such as Azure OpenAI or Azure AI Search?**
this sample app

**Is your feature request related to a problem? Please describe.**
The version of the API (2023-12-01-preview) we are using will no longer be available on April 2, 2024.
https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation#retiring-soon

**Describe the solution you'd like**
Update the API version you are using to the latest 2024-03-01-preview

**Is this feature specific to your use case or your organization, or would it apply broadly across other uses of this app?**
it apply broadly across other uses of this app

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sebastian-nowak-hycom** [comment]
I think a solution is on the way and you can find it here:
https://github.com/microsoft/sample-app-aoai-chatGPT/pull/697/files

Yesterday I migrated these changes to my project and it seems to work for both 2024-02-15-preview and 2024-03-01-preview
