### ISSUE TITLE
Failed to get managed identity token.

### ISSUE THREAD

**Issue by gabrielsusai** [microsoft/sample-app-aoai-chatGPT#699]
**Describe the bug**
While testing the code locally using your own data. I am getting the below error. Works well for just chat. 

Error
Error code: 400 - {'error': {'requestid': 'aae728a0-799f-49de-8ade-c1e51a5bbbbc', 'code': 400, 'message': 'Failed to get managed identity token. Response: {"error":{"code":"ManagedIdentityIsNotEnabled","message":"Managed Identity (MI) is not set for this account while the encryption key source is \'Microsoft.KeyVault\', customer managed storage or Network Security Perimeter is used."}}'}}

Use AzureSearch Service with semantic search

**To Reproduce**

**Expected behavior**
No error.

**Screenshots**
<img width="505" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/2603374/46c77658-c3b7-4742-a2bf-ebde944ef415">

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-35-turbo-16k, version 0613'): gtp35turbo
 - Is chat history enabled? No
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc) AzureAI Search

**Additional context**
We have multiple AI apps using data is deployment are running successfully. I checked out the latest code to test and upgrade all the AI apps eventually.

**Comment by sarah-widder** [comment]
Hi @gabrielsusai have you set AZURE_OPENAI_KEY and AZURE_SEARCH_KEY in your local .env file? It looks like it's attempting to use managed identity authentication which is not configured for your resource, so you should set the keys instead.

**Comment by gabrielsusai** [comment]
@sarah-widder All the below keys have values in my local .env file. I have two copies of the sample-app. The older copy works fine which is currently deployed in production with the same resources. Now, I took the latest version of the sample-app and using the same configuration. Does the new code requires to make any change in the Azure AI resources?

AZURE_OPENAI_RESOURCE=bxxxxx
AZURE_OPENAI_MODEL=Gxxxxx
AZURE_OPENAI_KEY=6xxxxx
AZURE_OPENAI_MODEL_NAME=gptxxxxx
AZURE_SEARCH_SERVICE=bxxxxx
AZURE_SEARCH_INDEX=axxxxxx
AZURE_SEARCH_KEY=Yxxxxx
AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG=default

**Comment by neissljanik** [comment]
Could there be an API Version mismatch? I've had this issue before and resolved it by updating the API version in the .env file to the version actually used by the application code. If these values don't match, the API expects the payload in a different format compared to what it actually receives from the application.

**Comment by gabrielsusai** [comment]
@neissljanik  Latest version of the code resolved the issue and I noticed a few changes in the utilization of API version and your own data.

**Comment by GraysonQuartech** [comment]
I am currently also getting this error.... same repro steps as above.  using typescript 
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/122839257/16e48ab1-5dfc-42ed-82ec-16bb51a9e987)

**Comment by harshbangad** [comment]
Started getting this error since last week. Chat playground works fine on Azure AI Studio but the webapp throws this error. @gabrielsusai Please check this bug https://github.com/microsoft/sample-app-aoai-chatGPT/issues/1024

**Comment by sarah-widder** [comment]
@harshbangad @GraysonQuartech check if system assigned managed identity is enabled on the Azure OpenAI resource, that would be the cause of this error message. It needs to be enabled.

**Comment by harshbangad** [comment]
@sarah-widder It is enabled. I never changed anything. I have other similar deployments which work fine in both chat and webapp. But since last week, the chat is working fine but webapp is not. You can check the bug i posted above. Others are facing it too. Did something change on webapp side?

![image](https://github.com/user-attachments/assets/27dcb91c-6582-4359-b13d-e1c23b1e39dc)

**Comment by kunalghangas** [comment]
Same issue here.

**Comment by LucasPonzo** [comment]
> @harshbangad @GraysonQuartech check if system assigned managed identity is enabled on the Azure OpenAI resource, that would be the cause of this error message. It needs to be enabled.

In my case, as in 30/Aug/2024 it was disabled. I enabled the managed identity for the AI Service (created via AI Studio Hub) and the Web App worked gracefully!

**Comment by thenewnano** [comment]
I can confirm that I had the same strange understanding that the managed identity for the AI Services need to be enabled, and it solved the issue.
