### ISSUE TITLE
Azure AI search tool message citations chunk_id always 0

### ISSUE THREAD

**Issue by wyttime04** [microsoft/sample-app-aoai-chatGPT#706]
**Describe the bug**
I'm using `data_preparation.py` to upload my data to AI search index.
Then I chat with AI and it response fine but then citations `chunk_id` is always `"0"`.
How can I specify this citations `chunk_id` ?

**To Reproduce**
1. Prepare data with [scripts/readme.md](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/scripts/readme.md)

2. Add `chunk_id` field in `data_preparation.py` when create search index

3. Add `chunk_id` field when chunk file

4. Run `data_preparation.py` with `config.json`

5. AI search result can see the `chunk_id` field
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/52523342/ee290fa4-9e19-427d-ba1d-c911a94c8134)

6. Start App with this index

7. AI response message citations `chunk_id` always `"0"`
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/52523342/b6137e99-4b34-461f-b06e-d6a38c153ce0)

**Expected behavior**
`chunk_id` should response AI search fields value

**Screenshots**

**Configuration: Please provide the following**
 - Azure OpenAI model name and version: `gpt-35-turbo`
 - Is chat history enabled? I didn't try this.
 - Are you using data? If so, what data source? `Azure AI Search`

**Additional context**
- `AZURE_OPENAI_PREVIEW_API_VERSION`: I have tried `2024-02-15-preview` and `2024-02-01`

**Comment by taigrr** [comment]
Hey, I ran into this using the golang SDK. I'm sure you've moved on for now, but the solution for me was to use the FieldMappings option to map the chunkID to the Filename property. Then I can get the filename property back (which is actually the chunk_id) and perform another query against Cognitive Search using a filter. It's definitely less than ideal, but shouldn't break even after this is fixed.

**Comment by wyttime04** [comment]
Hi @taigrr , the method I use is the same as yours. I mark the chunk ID in the `filepath` like `path/to/file - Part 1` and the total chunk number in the metadata field, which is useful when I want to delete all chunks of one file. I think this approach is acceptable for now.
Btw, I found something strange, when setting the chunk size larger, the API response `chunk_id` may be greater than 0. Does this mean the chat completion API might be automatically chunked? 🤔
