### ISSUE TITLE
UI customization not working?

### ISSUE THREAD

**Issue by NealSneijersPXL** [microsoft/sample-app-aoai-chatGPT#707]
**Describe the bug**
When I change the values in my .env file for UI customization, changes are not reflected when the app is ran locally.

**To Reproduce**
1. Clone the git repo
2. Once cloning is complete, pull to make sure to have the newest version of the repo
3. make a .env file in the root directory of the folder
4. copy & past the contents of .env.sample into .env
5. add a value for the UI customization variables
6. start the web app in the CLI (./start.cmd)
7. UI has not changed

**Expected behavior**
I expected for the UI to have been personalized to my use case.

**Screenshots**
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/93264239/2bda7e5b-0b52-4931-8f95-7cf40bae8d1d)
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/93264239/81f31f00-9169-4ff0-b736-94fcacf7892c)

**Configuration: Please provide the following**
 - gpt-35-turbo-16k
 - Is chat history enabled? no
 - Are you using data? no

**Comment by ajoublin** [comment]
Hi, it is not working for me neither, how did you solve it ?

Thanks.

**Comment by NealSneijersPXL** [comment]
Heya, the code where they import the actual .env file is placed after the declaration of the UI variables. Just need to put it above those and it's fixed!
