### ISSUE TITLE
data_preparation.py should support Word/PPT file format (docx pptx)

### ISSUE THREAD

**Issue by koichino** [microsoft/sample-app-aoai-chatGPT#71]
Currently, On Your Data UI feature is not support local language analyzer. So users need to prepare for indexes using data_preparation.py. However, it looks not support Word/PPT format as FILE_FORMAT_DICT in data_utils.py doesn't have Word/PPT format.

I think supported data format should along with the page " https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/use-your-data#data-formats-and-file-types " even for data_preparation.py.

**Comment by yuchim0828** [comment]
Support for word, ppt is important. Thank you in advance.

**Comment by lindazqli** [comment]
Hi @yuchim0828 @koichino, thanks for your feedback. Could you please clarify On Your Data UI feature a little? Are you referred to the web app you deployed from the studio? Can I say what you are asking is to the ability to upload word/ppt in the web app?

**Comment by koichino** [comment]
Hi Linda,

The feature should not be a part of UI. On Your Data Git has manual data preparation tool. You can refer to https://github.com/microsoft/sample-app-aoai-chatGPT/blob/7128fa0b683e9c6e921cd049cda157b0b0f6dd1d/scripts/readme.md.
My request is for it that should support word, ppt file.
