### ISSUE TITLE
'An error occurred. undefined'

### ISSUE THREAD

**Issue by DanError** [microsoft/sample-app-aoai-chatGPT#710]
First of all, I would like to say a huge thank you to @sarah-widder, @iseabock and everyone else that works on this project. This project has been transformative for our organisation. 
I’d like to share an error that we have noticeably seen over the last month.

**Describe the bug**
_'An error occurred. undefined' _and_ 'An error occured. Answers can't be saved at this time. if the problem persits, please contact the site administrator.'_

We regularly hit ‘undefined’ error messages, the console shows a 'failed to load resource' ERR_INCOMPLETE_CHUNKED_ENCODING and 500 error (screenshot below). Following the error you’re able to get back into the conversation by prompting again. Sometimes the error occurs midway through the response being generated on screen, the response is then hidden and the error shows. Sometimes the error shows as an immediate response to the question asked. 
In our experience the error will occur regardless of network, device, browser or time - Any advice on where to start troubleshooting this would be highly appreciated, thank you.

**To Reproduce**
1. Go to 'Frontend of App Service'
2. Click on 'Type a new question'
3. Initiate a dialogue or continue existing dialogue
4. See error at approx 1 in 10 conversations

**Expected behavior**
Preferable behavior would be that the incomplete answer is shown to the user, and/or the service automatically attempts to try again.

**Screenshots**
![Screenshot 2024-03-19 at 16 11 17](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/148348481/e50dcd5a-1ce8-445a-8dcf-11701b239800)
![Screenshot 2024-03-19 at 16 12 31](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/148348481/7b90a65f-d4b1-46f8-87f0-c43e6e09275f)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version - gpt-4, 1106-Preview
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? Azure AI Search 'keyword' indexing Blob Storage
 - App Service - Premium v2 P1V2
 - Max Tokens 2000

**Additional context**
Overall the service works really well, the error appears to occur regardless of number of concurrent users, and appears whether a citation is used or not.
Our setup follows the guidance here - https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/use-your-data-securely#resources-configuration

**Comment by leonardomoreira88** [comment]
Same problem here "An error occurred. undefined" some solution for that error?
