### ISSUE TITLE
There is a frontend bug in the stopping response generation scenario

### ISSUE THREAD

**Issue by mmdmirh** [microsoft/sample-app-aoai-chatGPT#729]
**Describe the bug**
There is a frontend bug in the stopping response generation scenario. Meaning that, stopping answer generation would be resulted in this bug. This occurs in the following two scenarios:
- The conversation title is already created
- The conversation title is not created

**To Reproduce**

- The conversation title is already created

1. send a prompt
2. the app is in waiting for answer generation
3. the stop button is activated
4. click on stop button to stop getting answer
5. history/update returns 500
6. the error Error "An error occurred. Answers can't be saved at this time. If the problem persists, please contact the site administrator." is displayed in the answer section
7. send another prompt
8. the prompt is not visible (the screenshot is attached)

- The conversation title is not created:

1. send the first prompt of the conversation
2. the app is in waiting for answer generation
3. the stop button is activated
4. click on stop button to stop getting answer
5. send another prompt
6. the prompt is changed to the second one.

**Expected behavior**
Choosing stop generation button should not resulted in error display and the next prompt should displayed in order.

**Screenshots**
For scenario one the screenshot is as: 
<img width="708" alt="Screenshot 1403-01-09 at 1 02 35 at night" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/109295869/aee22548-a031-4131-a4f6-fde0b52aa025">
Screen Record For second Scenario:

**Configuration: Please provide the following**
 - Azure OpenAI model name and version: gpt-4, version 2024-02-15-preview
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc) No

**Additional context**
There is also another bug in attached video that i think the rootcauses are as the same so I did not mention it.

**Comment by mmdmirh** [comment]
it seems that the screen record is too big to be updated here.

**Comment by jasredyy5** [comment]
Hi everyone, is there any update on this issue? Thank you!
