### ISSUE TITLE
Promptflow endpoint does not activate

### ISSUE THREAD

**Issue by JukkaAGit** [microsoft/sample-app-aoai-chatGPT#731]
**Describe the bug**
After configuring promptflow to .env file, chat app does not forward question to promptflow.

# Chat with data: Prompt flow API
USE_PROMPTFLOW=True
PROMPTFLOW_ENDPOINT=https://xxxxx.ml.azure.com/score
PROMPTFLOW_API_KEY=xxxxxx
PROMPTFLOW_RESPONSE_TIMEOUT=120
PROMPTFLOW_REQUEST_FIELD_NAME=question
PROMPTFLOW_RESPONSE_FIELD_NAME=items

**To Reproduce**
1. Configure promptflow to .env
2. Deploy chat app
3. Start asking questions in chat. No error msg, chat does not answer based on promptflow flow. Answer comes from llm.

**Expected behavior**
Answers comes from promptflow.

**Configuration: Please provide the following**
 - Azure OpenAI model name and version 'gpt-35-turbo-16k
 - Is chat history enabled? --> yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc) --> promptflow

**Comment by JukkaAGit** [comment]
Now it works. It seems that promptflow works only in non-stream flow.

**Comment by chillnova** [comment]
is there a way we can enable stream with the prompt flow?
