### ISSUE TITLE
{"citations": [], "intent": "[]"} text shows up above the answer text after several question 

### ISSUE THREAD

**Issue by mverhov** [microsoft/sample-app-aoai-chatGPT#738]
**Describe the bug**
{"citations": [], "intent": "[]"} text shows up above the answer text after several questions 

**To Reproduce**
1. The easiest way to reproduce is to ask the same question several times
2. {"citations": [], "intent": "[]"} will show up

**Expected behavior**
No {"citations": [], "intent": "[]"} text 

**Screenshots**
![Screenshot 2024-03-29 at 11 10 13 AM](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/3923671/86b904dd-93b0-4844-b1de-0d645ba6f7fd)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (gpt-35-turbo, version 0301)
 - Is chat history enabled? Yes
 - Are you using data? Azure AI Search index from blob

**Additional context**
It happens only with the code deployed starting with this commit Update request/responses to use OYD 2024-02-15-preview API (https://github.com/microsoft/sample-app-aoai-chatGPT/pull/697)

Everything works fine if I remove the Azure AI Search

I also built a generic app with Open AI Studio with "add your data". Everything works fine in the playground, but I'm getting the same {"citations": [], "intent": "[]"} messages, after deploying the code as a web app. The app also uses 2024-02-15-preview, so something is wrong or new in that API version.

**Comment by QuentinAd** [comment]
Same here, thank you for submitting the bug

**Comment by michellereppspur** [comment]
I'm seeing the same thing as well.

**Comment by Hadi2525** [comment]
Does AI Search index any documents or data from any containers/resources? A possibility for this returned json object is that AI Search has an empty index content.

Test the app when you add documents to a container.

Take a look at environment variables https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/.env.sample

You may want to set SEARCH_ENABLE_IN_DOMAIN=False if you are not using the AI Search Indexer.

**Comment by michellereppspur** [comment]
> Does AI Search index any documents or data from any containers/resources? A possibility for this returned json object is that AI Search has an empty index content.
> 
> Test the app when you add documents to a container.
> 
> Take a look at environment variables https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/.env.sample
> 
> You may want to set SEARCH_ENABLE_IN_DOMAIN=False if you are not using the AI Search Indexer.

I'm seeing something similar but not exactly the same. It is actually referencing content and looks like this (displays out the json object in the chat window - expected behavior would be to not have this json object displayed):
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/159586456/401c17fc-1fba-4af0-9046-d2341372325c)

It is finding a document located in a container.

**Comment by Hadi2525** [comment]
@michellereppspur Somehow the system prompt along with retrieved chunks are leaked to the output response.

A few ways you can manage it: Go to Azure OpenAI Studio and in the model deployment set the temperature to zero and in the playground work with the system prompt and do some prompt engineering. That should work.

Once your prompt is grounded enough then set it to `AZURE_OPENAI_SYSTEM_MESSAGE` variable.

**Comment by mverhov** [comment]
I think this https://github.com/microsoft/sample-app-aoai-chatGPT/pull/756 is the fix for this bug.
