### ISSUE TITLE
Creation index using blob containers 

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#74]
Hello. I'm trying to create an index using files stored in a blob container. However, when running the create script, a message is being displayed that the path to the blob cannot be found. On the other hand, when the files are stored in a local directory, such as "c:\data\test", the files are found and the index is successfully created. I wonder if the index creation scripts are prepared to find files that are in a blob?

**Comment by sarah-widder** [comment]
Hi @edercarlima, currently the index creation script is only set up for local files. You can ingest your data from blob storage using the Azure OpenAI Studio. Follow this quickstart and select "Azure Blob Storage" as the data source, then you can select the container with your files: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/use-your-data-quickstart?tabs=command-line&pivots=programming-language-studio . I'll close this issue for now.
