### ISSUE TITLE
frontend building faces error due to lack of react-syntax-highlighter package 

### ISSUE THREAD

**Issue by mmdmirh** [microsoft/sample-app-aoai-chatGPT#746]
**Describe the bug**
frontend building returns error as the syntax highlighter package is missed
**To Reproduce**
1. run ./start.sh in the root folder of the app
2. you can see that frontend building is failed
3. the error is because of missed syntax highlighter package which should be included in package.json and package-lock.json
**Expected behavior**
frontend should be build without problem in building app
**Screenshots**
N/A
**Configuration: Please provide the following**
 - Azure OpenAI model name and version GPT4
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? No

**Additional context**
the problem is solved by running:
 - npm install react-syntax-highlighter  
 - npm install --save-dev @types/react-syntax-highlighter

**Comment by abhahn** [comment]
Hi @mmdmirh , sorry for the delayed response to your issue.  This was recently solved in #758 .  I'm going to close this issue now, but please feel free to reopen if you think there is still a problem.
