### ISSUE TITLE
Question Regarding Chatbot Buttons

### ISSUE THREAD

**Issue by makazano** [microsoft/sample-app-aoai-chatGPT#750]
When using the web app, there are two buttons: A plus button and a broom button. I was wondering if clarification can be provided regarding each button's intended use. 

My current understanding is that the plus button creates a new session and the broom button clears the session.

**Comment by iseabock** [comment]
@makazano your understanding is correct. If I were to prompt with "tell me about the US constitution" then his the + and prompt with "tell me about the US senate" I would have two entries in the chat history. One would be about the constitution and the other would be about the senate. If I prompt with "tell me about cats" then hit the broom and prompt "tell me about dogs" I will have one entry in chat history about cats and dogs.
