### ISSUE TITLE
ERROR:asyncio:Unclosed client session

### ISSUE THREAD

**Issue by qad002** [microsoft/sample-app-aoai-chatGPT#751]
**Describe the bug**
ERROR:asyncio:Unclosed client session

**To Reproduce**

1. Use latest updates you provided
2. Unsure how to reproduce except for enabling chat history and making multiple concurrent requests.
3. We were not able to reproduce in our QA env so far but it seems to happen in production with about 200 users per day.

**Expected behavior**
Expected the client sessions to close but for some reason it is staying open.

**Screenshots**

```log
2024-04-02T11:04:36.654029827Z ERROR:asyncio:Unclosed client session
2024-04-02T11:04:36.654049227Z client_session: <aiohttp.client.ClientSession object at 0x706d143d01d0>
```

**Configuration: Please provide the following**
 - Azure OpenAI model name and version
gpt-4 1106 (turbo) also gpt-3.5-turbo 1106
 - Is chat history enabled?
 yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc)
No data sources used

**Additional context**

**Comment by Hadi2525** [comment]
@qad002 Can you share what hardware tier you're using for the `Web Service`? Do you have an estimate population of users accessing the web app?

Check Your Azure Logs for the subscription you are running the `App Service`, run `AppServiceHTTPLogs` and watch for crashes or code errors.

**Comment by QuentinAd** [comment]
@abhahn  I have been able to reproduce. What happens is in app.py the init_cosmosdb_client() uses the azure.identity.aio import DefaultAzureCredential which is the async declination, but the DefaultAzureCredential session is not being closed, as seen here:

```
            if not AZURE_COSMOSDB_ACCOUNT_KEY:
                credential = DefaultAzureCredential()
            else:
                credential = AZURE_COSMOSDB_ACCOUNT_KEY
  ```

**Comment by Epstone** [comment]
Same issue as this one I guess:
#593 Unclosed client session error

I still have the cosmos features deactivated to get around this. Maybe one could find the time for a PR? :)
