### ISSUE TITLE
error TS2786

### ISSUE THREAD

**Issue by michbalazs** [microsoft/sample-app-aoai-chatGPT#754]
**Describe the bug**
Run Start.cmd. It runs though until comes to building front end  then i get 17 ts2786 errors
eg
**src/components/Answer/Answer.tsx:318:22 - error TS2786: 'DefaultButton' cannot be used as a JSX component.
  Its instance type 'DefaultButton' is not a valid JSX element.**

**To Reproduce**
Steps to reproduce the behavior: using VScode. In the integrated terminal ./start.cmd

**Expected behavior**
I expected it to finish. 

**Configuration: Please provide the following**
 - Azure OpenAI model name and version -- gpt-4)
 - Is chat history enabled? yes
 - Are you using data? If so, what data source?Azure AI Search,
**Additional context**
All works from azure , just trying to run locally.

**Comment by joshsavachik** [comment]
I was able to work around this by adding the following code under compilerOptions in tsconfig.json

"paths": {
    "react": [ "./node_modules/@types/react" ]
}

**Comment by iseabock** [comment]
@michbalazs Are you still having this issue? I'm not able to reproduce.
