### ISSUE TITLE
Responds in english even though "own data" and questions are in danish

### ISSUE THREAD

**Issue by AThomsen** [microsoft/sample-app-aoai-chatGPT#76]
I've fed some pdf documents in danish into the search service and configured this sample project to use the index with chatgpt-35-turbo. I then ask questions in danish and to begin with it answers back in danish. Then at some point it starts answering in english!

There doesn't seem to any pattern to this. The english replys are still correct in the sense that they corresponds with the contents of the documents, although translated.

Any idea what's up with this?

**Comment by sarah-widder** [comment]
Thanks for raising this issue. Adding @ashatabak786 to look into this.

**Comment by ashatabak786** [comment]
I think this is just chatgpt not following instructions properly which can happen as the context becomes longer. I recommend you can try few things:
1. Add a system message - "You are an AI assistant that helps users find information using retrieved documents. You are given Danish documents which you should read carefully to answer user queries in Danish. Please answer all questions in Danish without translation.
2. Put the system message in Danish itself - If all of the prompt are in English, then the model might move to English overtime. Hence another idea is to use the above system message but translated in Danish.
3. If this does not work, after every query add - "Please answer in Danish without translation".

Let me know if this helps!
