### ISSUE TITLE
Output from Playground is not constant

### ISSUE THREAD

**Issue by kagoolastha23** [microsoft/sample-app-aoai-chatGPT#760]
**Describe the bug**
Output from the playground is not constant 

**To Reproduce**
1. Go to 'Azure AI Studio'
2. Click on 'Bring your own data.'
3. Scroll down to ' create index with default chunk size and enable chat history'
4. Deploy as a webapp and test it with questions

**Expected behavior**
The output of same question should be same in every session while interacting with the bot.

**Screenshots**
<img width="627" alt="sampleappissue1" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/146183991/28befd09-3f71-4bec-9225-9ecb4ae0a4f1">

<img width="620" alt="sampleappissue2" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/146183991/ca69aab5-b148-4557-b3aa-db9c5c3680a2">

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-4-32k')
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search)

**Additional context**
The index was created using Azure Blob source.

This randomness in output is something which I am not understanding. Please guide. I changed Strictness Environment variable to 5 as well still no improvement.

**Comment by abhahn** [comment]
Hi @kagoolastha23 , thanks for reaching out!

AFAIK, results from an LLM can't be guaranteed to be reproducible 100% of the time, but there are a few guidelines you can follow here to increase the stability of your results:  https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/reproducible-output?tabs=pyton

The key here is to use, at minimum, the `seed` parameter, but you can also add `system_fingerprint` to further increase the stability of the response.

The value of `seed` can be arbitrary, but the value of `system_fingerprint` is specific to the model deployment.  I am not seeing an easy way to get the value of `system_fingerprint` outside of the chat completion response payload received from AOAI, so we might want to think about the best way to address this in the webapp.  One option might be to use the first value of `system_fingerprint` encountered during the chat for subsequent messages.

I will discuss internally with a few team members to get some feedback, but in the meantime, you could try customizing the request object in app.py with the two parameters mentioned above to see if this helps.

**Comment by Hadi2525** [comment]
The way your Azure AI Search indexed your documents may cause this issue. Try changing the chunk sizes and consider some overlapping over the contents.

Additionally, make sure your AI Search is actually enabled for `Semantic Search` and therefore you need to add `vector embeddings` model from the Azure OpenAI Studio deployment models.

**Comment by kagoolastha23** [comment]
> The way your Azure AI Search indexed your documents may cause this issue. Try changing the chunk sizes and consider some overlapping over the contents.
> 
> Additionally, make sure your AI Search is actually enabled for `Semantic Search` and therefore you need to add `vector embeddings` model from the Azure OpenAI Studio deployment models.

Chunk size options are given in the playground.Where are chuck overlap options given in playground?Please elaborate?
