### ISSUE TITLE
Error message saying Authentication not configured

### ISSUE THREAD

**Issue by premsonbaby** [microsoft/sample-app-aoai-chatGPT#762]
**Describe the bug**
"Authentication not configured" message showing for a moment even if the Authentication is enabled using Microsoft Identity provider. The authentication is working but the attached screen is still displayed.

**To Reproduce**
1. Enable the Authentication provider as Microsoft and select all default settings.
2. Access the application. Microsoft standard login screen will be provided.
3. Even after a successful authentication or accessing the app a second time the attached screen will be visible for a short period.
4. See attached image

**Expected behavior**
Once after a successful authentication, no error page should be displayed.

**Screenshots**
![Screenshot1](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/31508228/216adb2a-749b-47ed-97fe-59e589569f53)

**Comment by sgkalyans** [comment]
any fix for this? It was working but still showing the same page after we add admin grant for application in AAD.
