### ISSUE TITLE
How to remove Show Chat History button from UI?

### ISSUE THREAD

**Issue by kagoolastha23** [microsoft/sample-app-aoai-chatGPT#765]
**Describe the bug**
I want the chat history to be enabled but I don't want the chat history button to be seen on right hand side. 

**To Reproduce**
I want to customize the default contoso app and remove the chat history button .Which functions I'll have to delete it?
 I have no knowledge of UI and need assistance which functions or modules have to be removed from the folder to make it happen?

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-4-32k')
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search)

**Additional context**
This is a custom requirement question.

**Comment by Hadi2525** [comment]
@kagoolastha23 If you only want to remove the chat history button, comment lines 82, 83, 84 of https://github.com/microsoft/sample-app-aoai-chatGPT/blob/ec893ded14cee8979b51884739a742faaf5075c9/frontend/src/pages/layout/Layout.tsx#L82

**Comment by Hadi2525** [comment]
FYI, https://github.com/microsoft/sample-app-aoai-chatGPT/pull/771 is a PR that helps with your request on hiding the `chat history`. Remember that once you hide the chat history and publish it to web services then it cannot be accessed from the UI. You still can retrieve chat history in CosmosDB.

**Comment by kagoolastha23** [comment]
> @kagoolastha23 If you only want to remove the chat history button, comment lines 82, 83, 84 of
> 
> https://github.com/microsoft/sample-app-aoai-chatGPT/blob/ec893ded14cee8979b51884739a742faaf5075c9/frontend/src/pages/layout/Layout.tsx#L82

I want to make this change and deploy the app? It is mentioned I need to run start.cmd before deploying the app.I didn't understand that part. I am cloning the repo and using Azure CLI to deploy it to web app.How will I run that in Azure Cloud Shell?

**Comment by Hadi2525** [comment]
start.cmd is for running the app locally. To deploy it to Azure follow instructions in this section:
https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/README.md#deploy-with-the-azure-cli

**Comment by kagoolastha23** [comment]
> start.cmd is for running the app locally. To deploy it to Azure follow instructions in this section: https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/README.md#deploy-with-the-azure-cli

NOTE: If you've made code changes, be sure to build the app code with start.cmd or start.sh before you deploy, otherwise your changes will not be picked up. If you've updated any files in the frontend folder, make sure you see updates to the files in the static folder before you deploy. How do I do this step?

**Comment by Hadi2525** [comment]
from your command terminal run `./start.cmd` it builds the full-stack package (python for backend / typescript for the frontend). Have you tried running it from CLI?

**Comment by kagoolastha23** [comment]
<img width="944" alt="sampleissue1" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/146183991/01ffea6e-77ea-4a98-8d6f-53a7d55fafda">
I am getting this error when I commented line 82 83 84 and then executed ./start.sh and deployed the app.

**Comment by kagoolastha23** [comment]
Here is what I am seeing on my application logs
<img width="708" alt="sampleissue1" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/146183991/8e28f3d3-e5b6-47c8-ae2f-14189981531d">
