### ISSUE TITLE
history/update is not executed when there are no errors in currentChat

### ISSUE THREAD

**Issue by tateren** [microsoft/sample-app-aoai-chatGPT#766]
**Describe the bug**
We have enabled chat history.
However, only user messages are being saved, and the assistant's responses are not being saved.

**To Reproduce**
1. Enable chat history.
2. Start the chat.

**Expected behavior**
Chat history is saved.

**Configuration: Please provide the following**
 - Azure OpenAI model name and version. gpt-35-turbo-16k
 - Is chat history enabled? Yes
 - Are you using data? No

**Additional context**
In this process, I believe that if there are no errors in currentChat, saveToDB is not being called.
https://github.com/microsoft/sample-app-aoai-chatGPT/blob/c6162b695b5997d3d63d2eb05e5adda4a6539cd8/frontend/src/pages/chat/Chat.tsx#L555-L558

**Comment by bsonnek** [comment]
I have this same issue. The tools and assistant role history are not being saved to Cosmos DB.  If I deploy a new Web App and Cosmos DB from the AI Playground, History is saved correctly.   If I use the current code against my existing web app and  Cosmos  DBs, the history isn't saved correctly.  

This doesn't seem to be called at any point of the conversation.

@bp.route("/history/generate", methods=["POST"])
async def add_conversation():

**Comment by tateren** [comment]
I have confirmed that this will be fixed by this pull request.
#768

**Comment by bsonnek** [comment]
The changes from #768 fixed the issue for me. Great work finding the issue so quickly!
