### ISSUE TITLE
Getting error while running data preparation script to crack and ingest PDF documents

### ISSUE THREAD

**Issue by kagoolastha23** [microsoft/sample-app-aoai-chatGPT#772]
**Describe the bug**
Unable to create index using Optional: Crack PDFs to Text

**To Reproduce**
1. Go to repo
2. Click on 'scripts'
3. Scroll down to 'read.me' and follow the steps to prepare data locally. I want to crack pdfs to text to create an index
4. I created config.json to include the details
5. See error

**Expected behavior**
The code should execute and index should be created.

**Screenshots**
<img width="948" alt="sampleappissue1" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/146183991/f559a4ad-ea20-4442-a8a6-098503a90d0c">

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt -4')
 - Is chat history enabled? No
 - Are you using data? If so, what data source? (e.g. Azure AI Search.) I have given blob url as data path in config.json

**Additional context**
I don't know how to resolve the above error. Please give me step -by-step instructions to resolve it.

**Comment by abhahn** [comment]
Hi @kagoolastha23 , it looks like maybe there is an issue with your config.json on line 9.  Are you missing a quote somewhere on that line?  It might help to open it in an IDE with JSON support to see the issue more clearly.

**Comment by kagoolastha23** [comment]
> Hi @kagoolastha23 , it looks like maybe there is an issue with your config.json on line 9. Are you missing a quote somewhere on that line? It might help to open it in an IDE with JSON support to see the issue more clearly.

Once I add the double quotes in config.json.I saved it. How to deploy that change? I can't run start.cmd on Azure CLoud shell.

**Comment by kagoolastha23** [comment]
I updated config.json and ran the code .I got this error.
![Uploading sampleappissue1.png…]()

**Comment by kagoolastha23** [comment]
I updated config.json and ran the code and I got this error
![Uploading sampleappissue1.png…]()

How to resolve this error? What authorization mismatch it has?
