### ISSUE TITLE
Reproducible Crash

### ISSUE THREAD

**Issue by Smtuten** [microsoft/sample-app-aoai-chatGPT#78]
The example code works very well.  However, we have found that simply chatting with the app for a small number of back and forths, say less than 10, that have any amount of text causes the web app to hang.  Once it is hung you must restart the app in order to get the app to respond.  If you ask a question, get a response and then clear each time it doesn't seem to have an issue.  It seems to suggest that the app may not be handling token limits correctly?

**Comment by guitaliba** [comment]
We have an similar issue. But when we reload the page, we are facing a delay (about 30 / 60 seconds) to have the page reloaded. 
We have already changed the app service tier (we are using premium Premium v2 P2V2), and the problem persists.

**Comment by robinzhengwang** [comment]
I met the same problem. When I ask common question outside of document scope, it will crash. sometimes no response, sometimes jump out.

**Comment by MarcosChavarria** [comment]
same, any ideas?

**Comment by davidm00** [comment]
Hi, I believe this issue has been resolved. If not, please create a new issue
