### ISSUE TITLE
Unable to retrieve response from API Postman

### ISSUE THREAD

**Issue by sreddyvari** [microsoft/sample-app-aoai-chatGPT#79]
I am unable to retrieve the post api response to use the generated context for a asked question.

Attached the response.
![error](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/139426854/bc09f5ec-518f-4429-97c0-013d9fb3c325)

**Comment by sreddyvari** [comment]
Hi @sarah-widder,

Thank You for the details. I tried but giving 404 error. COuld you help with body ?

**Comment by davidm00** [comment]
Hi @sreddyvari, if this is still an issue, please create a new issue and I can further help.
