### ISSUE TITLE
CosmosDB not recording Feedback 

### ISSUE THREAD

**Issue by gw37** [microsoft/sample-app-aoai-chatGPT#793]
**Describe the bug**
The CosmosDB is not recording Feedback 

**To Reproduce**
1. using AOAI on your data with app deployed from OpenAI Studio, ENABLE_FEEDBACK = TRUE
2. submit a question corresponding to documents in the search index
3. Click the ThumbsUp/Thumbs Down icon
4. Error, whether we indicate Positive or Negative, and Negative with a checkbox selected, the CosmosDB record shows Feedback as "" , an empty string

**Expected behavior**
In other deployments we see the feedback recorded as POSITIVE or with the negative reason selected e.g. "missing_citation"

**Screenshots**
Screenshot and log stream attached
![Cosmos-Error-Screenshot 2024-04-17-173452](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/13895481/b1ec4a06-d512-4479-9180-cf71c90fc83a)
[2024-04-18T001811.881624599Z --ERROR-re-feedback.zip](https://github.com/microsoft/sample-app-aoai-chatGPT/files/15018413/2024-04-18T001811.881624599Z.--ERROR-re-feedback.zip)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version -- GPT4-turbo-0125-Preview
 - Is chat history enabled?  --YES
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc)  AI Search w/ AZBlobStorage

**Additional context**
In the web application there are no on-screen error messages, all else is working, conversation history is recorded, but the saving of feedback is hitting error. Several users have tried to submit feedback on answers and get the same bad result.

**Comment by gw37** [comment]
i did an update of the code today (Apr.25) and the issue is now resolved. If anyone else encounters this its probably an anomaly in whatever version of the code you have, so try an update.

**Comment by BLauRDI** [comment]
Still getting an empty string for feedback. I believe we have the latest from github. 
![image](https://github.com/user-attachments/assets/48284f81-2564-49c4-8f59-5346078dbc91)

**Comment by iseabock** [comment]
@BLauRDI Can you confirm you do have the latest code and you db configured properly? I am not able to reproduce this since it was fixed previously.

**Comment by martin-at-RTS** [comment]
We are also seeing the same issue. Confirmed we have the latest updates from the github repo, including the package update for quart. Data flows from CosmosDB and is reflected in the chat history for users but feedback is not recorded outside of the browser tab itself.

![Image](https://github.com/user-attachments/assets/95d869db-13ff-458a-9bd6-8a285e7eaaa5)
