### ISSUE TITLE
Web app crash when asking problem outside of doc scope

### ISSUE THREAD

**Issue by robinzhengwang** [microsoft/sample-app-aoai-chatGPT#80]
I like this app sample, it is very helpful. But recently, I met some issues, when I ask some common questions out of the document scope, the app will be stuck for a long time, and then prompt error information. Then I must reload the web page to get it work again. I have tried stop generating and resubmit the question, but it will hang there no response.
My settings, 
I use my own index and indexer within 3 small one-page pdf files for test (no file chunk):
AZURE_OPENAI_TEMPERATURE: 0.2
SEARCH_INDEX_IS_PRECHUNKED: false
AZURE_SEARCH_USE_SEMANTIC_SEARCH: true 
 
When I check from web explorer tools, I found something as following:
Could you please help me to check it? Thank you very much.
/********************************
TypeError: Cannot read properties of undefined (reading '0') at https://XXX.azurewebsites.net/assets/index-97ad713f.js:108:69 at Array.forEach (<anonymous>) at y (https://xxx.azurewebsites.net/assets/index-97ad713f.js:108:4)
message
: 
"Cannot read properties of undefined (reading '0')"

obj
: 
"{\"error\": \"Expecting value: line 1 column 1 (char 0)\"}"

**Comment by davidm00** [comment]
Hi @robinzhengwang, if you are still experiencing issues with this please create a new issue and I can follow up.

**Comment by robinzhengwang** [comment]
Thanks, not happened again after updating the apps.
