### ISSUE TITLE
Render entire PDF's instead of single page in citation

### ISSUE THREAD

**Issue by VikashLalit** [microsoft/sample-app-aoai-chatGPT#811]
**Describe the bug**
When we open citation then currently it just shows content of some particular chunk but it will be better if we can see the entire doc .

**To Reproduce**
1. ask any question to bot 
2. Click on citation 
3. It will just show Content of particular chunk

**Expected behavior**
It should render entire pdf data after clicking on citation.

**Screenshots**

**Configuration: Please provide the following**
 - Azure OpenAI model name and version : gpt-4
 - Is chat history enabled No
 - Are you using data? If so, what data source - Azure AI Search

**Additional context**

**Comment by VikashLalit** [comment]
@sarah-widder @pamelafox  It will be a great help if you can guide me for this one.

**Comment by VikashLalit** [comment]
@sarah-widder can you please guide me for above issue?

**Comment by sarah-widder** [comment]
Hi @VikashLalit, currently the chunks displayed are what is returned by the Azure OpenAI On Your Data API, which returns what it has retrieved from the search index. The index contains chunked data for best quality when using with the chat models. If you want to fetch the original documents, you can use the filename or url properties of the citation, and write your own logic to retrieve the source documents from blob storage to display.

**Comment by VikashLalit** [comment]
@sarah-widder I have added source url of confluence at the end of every document and also included in system message to add the source url of every reference document at the end of the answer...but its not working...so wanted your suggestions like what i should do so that model will include source confluence url  in citation or at the end of answer.

**Comment by v-hsalman** [comment]
@VikashLalit Not sure if you're a developer or not, but if you want to implement that functionality then try going [here](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/app/frontend/src/components/AnalysisPanel/AnalysisPanel.tsx) which is a different repository, but also by microsoft. If you go [here](https://app-backend-xw55anu4yrb3k.azurewebsites.net/#/) then you can see what the app would look like. Additionally, go [here ](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/other_samples.md )to find the differences between this repo and the one I linked earlier in my message.
