### ISSUE TITLE
Simple way to make adjustments in the code

### ISSUE THREAD

**Issue by nheij** [microsoft/sample-app-aoai-chatGPT#814]
**Is your feature request related to this sample app, or to an Azure service, such as Azure OpenAI or Azure AI Search?**
The feature is focused on the sample app

**Is your feature request related to a problem? Please describe.**
It's very unclear to me how to adjust the code and use that online in a different way than azd. Using the azure developer CLI does not work as I do not have the correct rights (and probably not getting them for this project). I deployed an azure webapp using the button Azure AI Studio playground. this set up a simple working webapp for me which works great and I can adjust some things using the environment variables. But I would like to make more adjustments now. 
So I have all the necessary azure resources already setup, as the created webapp is using those as well, just need a way to deploy my changes without having to do all the things I need specific rights for.
Next to this I would prefer to use azure devops instead of github, if that is possible

**Describe the solution you'd like**
Some documentation or way that explains how I can deploy changes to the code to an existing webapp without having to use azd. Or about a way to only run specific parts of the azd that skips the parts with specific rights requirements.

**Is this feature specific to your use case or your organization, or would it apply broadly across other uses of this app?**
I guess it might benefit others coming here through Azure AI Studio as well.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by abhahn** [comment]
Hi @nheij , thanks for sharing your suggestions.

We have a [section of our README](https://github.com/microsoft/sample-app-aoai-chatGPT?tab=readme-ov-file#deploy-with-the-azure-cli) describing how you can deploy the app using the `az` CLI as well.  Would this help solve the issue you are having with access?  If not, could you give more detail about the problem you are having, including the rights you are missing, to see if there is another way we can assist you getting set up?

As for using Azure Devops, if it's your preference to maintain your own custom application code this way, one thing you could try is to create a fork of this repo to host in Azure Devops in your organization, which you can then use exclusively for deploying changes with the `az` CLI as described in the docs above.  Is this something you have considered?

**Comment by nheij** [comment]
Hi @abhahn , I should have read better, thanks for pointing me in the right direction, I thought that part of the readme was about the same option as the `azd` option. I've got it working now, will have a look on getting it working together with Azure DevOps but I think this won't be a real issue anymore now! Thank you very much!
