### ISSUE TITLE
Chat history errors related to CosmosDB database not found.

### ISSUE THREAD

**Issue by lizylgit** [microsoft/sample-app-aoai-chatGPT#819]
I have deployed the App using Azure AI studio, with chat history enabled. 
However, when using the App,  chat history is appearing as not enabled, a popup with the below error. And, chat conversations are not getting stored in the CosmosDB database.  

I can confirm that the App CosmosDB environment variables are matching with the CosmosDB account, database  and url. 
This was working a day before. 

Please guide me, if I am missing anything? (In my account, there is no CosmosDB Account Key set - which other forums mentioned with a similar issue).  I am required to provide this app for demoing to our leadership.
Thanks

--
Error seen on when browsing the app: 
"Chat history is not enabled
CosmosDB database db_conversation_history on account https://appname....com:443/ not found. Please contact the site administrator."
--- 
**To Reproduce**
1. Go to 'Azure OpenAI'
2. Click on 'Chat'
3. Use your own data option
4. Select data sources  - existing Azure AI Search . (This data source was created previously 3days ago in AI studio did not want to create a new storage each time.)  
       -Select existing AI Service
       -Select AI Service index
5. Deploy new App. with Chat enabled option.
6.  
**Expected behavior**
Chat history should be recorded in the 'chat history button' and user conversations stored in the CosmosDB.

**Screenshots**
-- CosmosDB environment variables 
<img width="1323" alt="Screenshot 2024-04-26 at 12 33 08 pm" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/6202443/61188f8f-53d8-462b-a13a-b0f3d7358c94">
-- chat history error when app is loaded.
<img width="343" alt="Screenshot 2024-04-26 at 2 19 12 pm" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/6202443/4891b6c3-2475-43b2-b557-8007226dbd65">

**Configuration: Please provide the following**
 - Azure OpenAI model name and version - gpt-35-turbo
 - Is chat history enabled? Yes
 - Are you using data? Yes - Azure AI Search

Thanks

**Comment by lizylgit** [comment]
@sarah-widder, any advice on this would be greatly appreciated. Thanks.

**Comment by lizylgit** [comment]
It is working for me now.

**Comment by mittalpatel130** [comment]
@lizylgit  - Can you please tell me how did you solve this? I'm getting exact same error message.

**Comment by mittalpatel130** [comment]
@sarah-widder  -  Can you please post the solution here, I am also facing the same error message. Thank you!

**Comment by asaip9465** [comment]
@lizylgit and @mittalpatel130 I'm having the same problem with the same exact error message. Cosmos DB is there, database and collection as well. I verified that all environmental variables (AZURE_COSMOSDB_ACCOUNT, AZURE_COSMOSDB_DATABASE and AZURE_COSMOSDB_CONVERSATIONS_CONTAINER) point to the correct names of the resources. But the web app still says chat history is not enabled. Any help would be much appreciated!

**Comment by asaip9465** [comment]
@c2js Thanks for the tips!
