### ISSUE TITLE
Base URL is wrong

### ISSUE THREAD

**Issue by FL0S0T** [microsoft/sample-app-aoai-chatGPT#82]
I get the following error:

Error
Error communicating with OpenAI: HTTPSConnectionPool(host='MYACCOUNT.openai.azure.com', port=443): Max retries exceeded with url: //openai/deployments/MYDEPLOYMENT/chat/completions?api-version=2023-03-15-preview (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f00b540b670>: Failed to resolve 'MYACCOUNT.openai.azure.com' ([Errno -2] Name or service not known)"))

in the code the following is wrong I think:
    chatgpt_url = f"https://{AZURE_OPENAI_RESOURCE}.openai.azure.com/openai/deployments/{AZURE_OPENAI_MODEL}"

the Base URL in my cognitive service is the following and does not match the url mentioned before:
"https://westeurope.api.cognitive.microsoft.com/"

**Comment by FL0S0T** [comment]
I've found the problem.

We have deployed the solution with terraform and the service was set behind a private endpoint.

The url was different. When you deploy it with terraform the URL looks like the following:
`https://{AZURE_OPENAI_RESOURCE}.openai.MICROSOFT.com`

But if you deploy it manually it is:
`https://{AZURE_OPENAI_RESOURCE}.openai.azure.com`

I have checked it on different deployments and all ressources deployed without terraform are working...

**Comment by pamelafox** [comment]
Ah okay. I don't think we provide the terraform for this, right? Is that terraform you wrote yourself? I'm trying to see if there's anything we should be fixing in this repository. Thanks!

**Comment by Yafaa5** [comment]
I had the same issue I think the in app.py line 89 and line 194 the path and endpoint is hardcoded example  `endpoint = f"https://{AZURE_OPENAI_RESOURCE}.**openai.azure.com**/openai/deployments/{AZURE_OPENAI_MODEL}/extensions/chat/completions?api-version={AZURE_OPENAI_PREVIEW_API_VERSION}"` as it's not always the case to be **openai.azure.com** this portion should be passed an environment variable

**Comment by FL0S0T** [comment]
Thats true. It looks like there are two differnt base URLs...

**Comment by jakeatmsft** [comment]
+1 for compatibility with APIM endpoint connecting to OpenAI backend.

**Comment by davidm00** [comment]
I believe this issue has been resolved as AZURE_OPENAI_ENDPOINT is passed as an env variable now.
