### ISSUE TITLE
Unclear how /extensions/chat/completions does the retrieval behind the scenes

### ISSUE THREAD

**Issue by gingergenius** [microsoft/sample-app-aoai-chatGPT#84]
I have failed to understand from the documentation how the `"/deployments/{deployment-id}/extensions/chat/completions"` endpoint interacts with Cognitive Search behind the scenes.
The background is I'm trying to understand what flexibility it offers and what it would take to implement the retrieval and integration of documents into the LLM's prompt manually if we want to change something.

What Cognitive Search endpoint does the extension call and with what parameters? Here's an example of an API request I sent myself to try reproducing the top 5 results within the `tool` citations

```
curl --location 'https://[deployment].search.windows.net/indexes/[index]/docs/search?api-version=2023-07-01-Preview' \
--header 'Content-Type: application/json' \
--header 'api-key: [key]' \
--data '{  
     "queryType": [I tried full, simple and semantic here, semantic with different settings for other required parameters]
     "search": "[question text]",  
     "top": 5
   }  '
```

I am getting the same documents back as in the Search Explorer for Cognitive Search in the Azure portal, but they are different from what comes back from the `extensions/chat/completions` request. The relevance scores are sometimes the same for the same chunks, but sometimes also different. Could you unveil why that happens?

Is it correct that no embeddings are used in the document retrieval as implemented in the Azure OpenAI playground and this sample app?

Is there more system text hidden away somewhere instructing the model to look at the sources and provide references in this [doc1] format? How would we go about modifying that if we are not happy with the citation accuracy?

**Comment by lindazqli** [comment]
Hi,

Thanks for your questions. Please see the following to your questions:

1. cognitive search -- Azure OpenAI on your data and Azure Cognitive Search determine what data to retrieve from the designated data source based on the user input and provided conversation history. This data is then augmented and resubmitted as a prompt to the OpenAI model, with retrieved information being appended to the original prompt.
2. difference in search result -- Azure OpenAI on your data does not necessarily use the exact user message to query the search index so may not always produce the same results as directly searching the index. Relevance scores can also differ based on whether semantic search is used.
3. embeddings -- Yes, no embeddings are used currently. Additional capabilities are on our roadmap, please stay tuned.
4. citation -- There is no other place to instruct the model and we are currently working on improve the citation accuracy, please stay tuned.

For more details, you can read https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data, please let us know if you have any other question.

**Comment by sarah-widder** [comment]
Closing this thread as it is inactive.

**Comment by gingergenius** [comment]
>  Azure OpenAI on your data does not necessarily use the exact user message to query the search index so may not always produce the same results as directly searching the index. 

What does this mean? How is the query different from the user message?
