### ISSUE TITLE
Upload Capability for Computer Vision Integration and files upload

### ISSUE THREAD

**Issue by Fetheddine-Addad** [microsoft/sample-app-aoai-chatGPT#846]
**Is your feature request related to this sample app, or to an Azure service, such as Azure OpenAI or Azure AI Search?**
Since the playground provides computer vision using vision service integration, yes it's related

**Is your feature request related to a problem? Please describe.**
Currently, the app lacks the ability to upload images, which limits its potential for tasks that could benefit from computer vision technologies. For example, users may find it frustrating when they cannot directly upload images for immediate analysis within the app.

**Describe the solution you'd like**
I would like the app to include a feature that allows users to upload images. This functionality should be user-friendly and support various image formats. The uploaded images could then be used with computer vision services to enhance the chatbot’s analytical capabilities.

**Comment by ChmHsm** [comment]
Very important feature for us, please consider addind this.

**Comment by vlad-tsoy** [comment]
I'll second this as well. With the availability of gpt4o, it's critical to be able to upload the files.

**Comment by wherewith** [comment]
I think the scope of this should be expanded to all file types, since this sample does not support any type of upload yet. For example, something like this [https://github.com/lordlinus/Enterprise-ChatGPT](https://github.com/lordlinus/Enterprise-ChatGPT) would work similarly.
