### ISSUE TITLE
Mutliple Users using AI STUDIO deployed APP with history enbaled in cosmo db but the history is visible of all the users and not based on user id. 

### ISSUE THREAD

**Issue by rehat22** [microsoft/sample-app-aoai-chatGPT#851]
Shouldn't it show history based on cookie or device? The entire user history of multiple users are visible in the history tab and its not showing history based on per user i.e each person has his own history rather than seeing the collective history of all users.
Also the Cosmo db backend showing user id like this now.
![Screenshot 2024-05-10 at 5 57 24 PM](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/121556952/bcd3db7d-8d21-4347-8270-8629dd251b92)
Auth enabled is set to false

**Comment by neissljanik** [comment]
If there's no authentication the app cannot know who is currently using it, so it can't save or display a specific user's history.

**Comment by speedbunny** [comment]
There is an open pull request awaiting approval to hide the chat history button for cases where multiple users are using the same instance that you may like to follow  [Add env var to show/hide Chat History Button #771]  (https://github.com/microsoft/sample-app-aoai-chatGPT/pull/771)
