### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by Bouke** [microsoft/sample-app-aoai-chatGPT#86]
It looks like the web app is trying to use fonts that aren't generally available. I would suggest to look into picking a common fallback font, or using a web font.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/235882/8c9797ce-b834-4cbb-994d-e820482d5cb9)

**Comment by pamelafox** [comment]
Nice catch! I submitted https://github.com/microsoft/sample-app-aoai-chatGPT/pull/88 to address it.

**Comment by pamelafox** [comment]
Merged!

**Comment by Bouke** [comment]
Quick turnaround, great, thanks!
