### ISSUE TITLE
gpt-4o

### ISSUE THREAD

**Issue by ChingLuoH** [microsoft/sample-app-aoai-chatGPT#875]
**Is your feature request related to this sample app, or to an Azure service, such as Azure OpenAI or Azure AI Search?**
Please make this app compatible with gpt-4o.

**Is your feature request related to a problem? Please describe.**
Getting error: OpenAI.APIStatusError: Request Header Fields Too Large when testing with gpt-4o model. The app works fine when using gpt-35-turbo-16k, gpt-4, gpt-4-turbo.

**Describe the solution you'd like**
This app support gpt-4o as a LLM model option.

**Is this feature specific to your use case or your organization, or would it apply broadly across other uses of this app?**
It applies to all.

**Describe alternatives you've considered**

**Additional context**

**Comment by starlightretaiil** [comment]
im using gpt4.o flawlessly no issues

**Comment by abhahn** [comment]
Hi @ChingLuoH , I am not able to repro this using my AOAI resource in EastUS2, but just wanted to ask if you can share which region you're using for AOAI?  I can check to see if I can repro it in your region.

It may also help if you can share the full stack trace, to verify if the issue is with the webapp or in the underlying service call.  Based on what you've shared above, it looks like it may be coming back from the API, in which case the problem is not with the webapp code but with something else.

**Comment by John-Vance** [comment]
I am seeing this in East US, about to try East US 2.
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/84252756/71cb0fa8-e05e-43f6-bb97-4778e38d1aab)

**Comment by John-Vance** [comment]
I am seeing this in East US, trying East US 2 next

![Screenshot 2024-05-23 203820](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/84252756/43a5d961-6bf4-4438-98dc-abf21c716379)

**Comment by ChingLuoH** [comment]
My Azure OpenAI is in East US region having this error.

**Comment by John-Vance** [comment]
I'm seeing the same HTTP 431 errors in East US 2. I will try next with a gpt-4-32k model instead.

**Comment by ChingLuoH** [comment]
ERROR:root:Exception in send_chat_request
Traceback (most recent call last):
  File "C:\Users\yourfolder\app.py", line 676, in send_chat_request
    raw_response = await azure_openai_client.chat.completions.with_raw_response.create(**model_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_response.py", line 262, in wrapped
    return cast(APIResponse[R], await func(*args, **kwargs))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\resources\chat\completions.py", line 1295, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_base_client.py", line 1536, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_base_client.py", line 1315, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_base_client.py", line 1392, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.APIStatusError: Request Header Fields Too Large
ERROR:root:Request Header Fields Too Large
Traceback (most recent call last):
  File "C:\Users\yourfolder\app.py", line 705, in conversation_internal
    result = await stream_chat_request(request_body, request_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\app.py", line 692, in stream_chat_request
    response, apim_request_id = await send_chat_request(request_body, request_headers)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\app.py", line 681, in send_chat_request
    raise e
  File "C:\Users\yourfolder\app.py", line 676, in send_chat_request
    raw_response = await azure_openai_client.chat.completions.with_raw_response.create(**model_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_response.py", line 262, in wrapped
    return cast(APIResponse[R], await func(*args, **kwargs))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\resources\chat\completions.py", line 1295, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_base_client.py", line 1536, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_base_client.py", line 1315, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yourfolder\.venv\Lib\site-packages\openai\_base_client.py", line 1392, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.APIStatusError: Request Header Fields Too Large

**Comment by John-Vance** [comment]
Working great in East US using gpt-4-32k. No quota for that model in East US 2 so couldn't test. I'm also using vector search on my data. The problem seems to be something new with the gpt-4o model, maybe other features causes it to exceed header length when making calls? I've got some more deployments to do tomorrow and will try some different combinations.

**Comment by lathcf** [comment]
The same issue is also happening in the Chat playground when using your own data with a gpt-4o model. Switching to a gpt-4 model with no other changes makes it work, so it much be something with the gpt-4o model.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/12939430/665198d1-6398-44da-96ff-e1d20a8d574e)

**Comment by ianagoudie** [comment]
I am also seeing this error in East US 2

**Comment by abhahn** [comment]
Hi everyone, I got confirmation from the service team that this is a known issue impacting GPT-4o models.  There is a planned mitigation which will begin rolling out next Tuesday after the holiday, so by EOW next week we should see this resolved for all impacted regions.

I'll follow up here with more information as it becomes available.

**Comment by rliberoff** [comment]
Hello!

We are having the very same issue today with EastUS and EastUS2 regions, using `gpt-4o` with BYOD and Azure AI Search.

Do you have any ETA when a fix will be available?

Thank you.

**Comment by pocketlinkDev** [comment]
Same issue here - work good on Azure AI studio , getting Error Request Header Fields Too Large on the deployed web app.

**Comment by dizapico** [comment]
We have an OpenAI balancer by APIM and some consumers thought that it was an APIM problem. Any region without that issue? Confirmmed for East US, East US 2 and North Central US. I will try it on the others disponible regions tomorrow

**Comment by jack-vinitsky** [comment]
FYI... Azure AI Studio Chat Playground started working over the weekend when using your own data. 

> The same issue is also happening in the Chat playground when using your own data with a gpt-4o model. Switching to a gpt-4 model with no other changes makes it work, so it must be something with the gpt-4o model.
> 
> ![image](https://private-user-images.githubusercontent.com/12939430/333630182-665198d1-6398-44da-96ff-e1d20a8d574e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTk4MTMsIm5iZiI6MTcxNjkxOTUxMywicGF0aCI6Ii8xMjkzOTQzMC8zMzM2MzAxODItNjY1MTk4ZDEtNjM5OC00NGRhLTk2ZmYtZTFkMjBhOGQ1NzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE4MDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTI4ZDM1ZDBkZjc2NjU2MDRkMWFhMWNkMjdiNmRmYWU4ZDQ4NWQ3ZWY5MDFhMzAwMTgwODE2NWY4Yjk1MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bDIGdNzVc3-sqCx3UkDlAn9U7lsNbhuqiKRDQzrEXvc)

**Comment by rliberoff** [comment]
So, is it working? Is it fixed?

**Comment by ianagoudie** [comment]
I am still getting the error in east us 2.

**Comment by daharmon** [comment]
I'm still getting the error in our web app deployed from the azure ai studio but not getting the error from within the chat playground.

**Comment by jimmyshah83** [comment]
I am also getting the same issue even after upgrading the openai version to 1.30.5
https://github.com/microsoft/sample-app-aoai-chatGPT/issues/898

**Comment by daharmon** [comment]
It seems to be fixed this morning when I tried. I made no changes.

**Comment by jimmyshah83** [comment]
Fixed even in the webapp?
I am still seeing the same error with latest code:

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/24946322/23825127-e2fd-4dc7-94e2-8c1f27aa8a13)

**Comment by daharmon** [comment]
Maybe the difference now is the fact that I'm using chat history and you are?

**Comment by jimmyshah83** [comment]
Yes - chat history is enabled

**Comment by ianagoudie** [comment]
It is working for me now. If it is not working, are you using API version 2024-05-01-preview?

**Comment by jimmyshah83** [comment]
I am getting Out of Memory with the new code on Mac

I see a new variable in start.sh
export NODE_OPTIONS=--max_old_space_size=8192

Even 8G isn't enough for this?

**Comment by ChingLuoH** [comment]
GPT-4o is working now in East US region.
