### ISSUE TITLE
Could not open connection to the host, on port 50505

### ISSUE THREAD

**Issue by tanweichit** [microsoft/sample-app-aoai-chatGPT#876]
I'm trying to host the sample code on an edge device and let the web app publicly accessible.
But I encountered an error where I cannot launch the http://<edge device's ip>:50505 from my another host server.
What could be the issue? What could be done to resolve the issue here?

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/137980096/52e1b792-8727-4a90-9c85-81af9f0cc330)

**Comment by abhahn** [comment]
Hi @tanweichit , it looks like there could be a networking issue between hosts.  Did you verify that the application is running without any failures on the host where you started it?

I have changed the label to "question" for now, unless you find that there are issues with application startup which are causing this.
