### ISSUE TITLE
settings.py issue - Data Source Setting with Search - Azure OpenAI grounding Issue

### ISSUE THREAD

**Issue by apvarana** [microsoft/sample-app-aoai-chatGPT#879]
looks like some env variables required like Data Source type, the new code is failing saying the data source is not set and Az open ai cannot be grounded. Specifically if we are using AI search. This problem surfaced after the latest checkout and settings,py file . Can someone pls look into this issue

**Comment by mverhov** [comment]
perhaps it's the same issue. I'm not able to start backend on the local machine after running start.sh starting with this commit https://github.com/microsoft/sample-app-aoai-chatGPT/commit/57aa0351fb390a3c36a51120487e13aaa553e168

```
sample-app-aoai-chatgpt/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/Users/Mverkhov/work/git-bitbucket/sample-app-aoai-chatgpt/.venv/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for _AzureOpenAISettings
model
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
key
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
Failed to start backend
```

**Comment by warmdev** [comment]
Also encountered the same issue. If you use Azure AI Search, creating an environment variable DATASOURCE_TYPE = "AzureCognitiveSearch" (in your .env file or App Service environment settings) solves the problem.

**Comment by abhahn** [comment]
Hi @apvarana / @warmdev, thanks for bringing this to our attention.  The variable `DATASOURCE_TYPE` is now required.  I will update the docs accordingly in the README, which is something I missed in the recent settings refactoring PR.

**Comment by abhahn** [comment]
#881 Docs update is in this PR.

**Comment by apvarana** [comment]
Hi Thanks for the above one.

There is one more error that I got 

Error code: 400 - {'error': {'requestid': 'xxxxxx', 'code': 400, 'message': 'An error occurred when calling Azure Cognitive Search: Azure Search Error: 400, message=\'Server responded with status 400. Error message: {"error":{"code":"","message":"Invalid expression: Could not find a property named \\\'True\\\' on type \\\'search.document\\\'.\\\\r\\\\nParameter name: $filter"}}\', url=URL(\'https://xxxxxxxx.windows.net/indexes/xxxxxxxx/docs/search?api-version=2024-03-01-preview\')\nPotential issue with Azure search filter. Please ensure all field names in the filter are correct and syntax is correct for filter.'}}


Potential Fix
In settings.py , I changed the filters line to 
filter: Optional[str] = Field(default=None, exclude=True)

in  _AzureSearchSettings Class

**Comment by abhahn** [comment]
Hi @apvarana , thanks for sharing the details of the issue with the filter.  I have changed the line to what you have recommended above for the time being, but actually I'm not sure if `exclude=True` is what we want, since it will prevent the value from being available in the dumped model output.

Did you have the `AZURE_SEARCH_PERMITTED_GROUPS_COLUMN` variable set in your environment at the time you got the error message above?

**Comment by apvarana** [comment]
I do not have AZURE_SEARCH_PERMITTED_GROUPS_COLUMN variable set
