### ISSUE TITLE
Cosmos Database stops logging Chat History on Code Sync

### ISSUE THREAD

**Issue by speedbunny** [microsoft/sample-app-aoai-chatGPT#889]
**Describe the bug**
Cosmos Database stops logging conversations on Code Sync. Show Chat History button does not appear anymore. 

**To Reproduce**
1. Sync code from default repository

**Expected behavior**
No environment settings have changed, so the Cosmos database should continue to log conversations.

**Screenshots**

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-35-turbo-16k, version 0613')
 gpt-4
 - Is chat history enabled?
 Yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc)
 No

**Additional context**

**Comment by John-Vance** [comment]
I am seeing the same right now.

- Model: gpt-4-32k 0613
- Chat history enabled: Yes
- Data source: Azure AI Search + blob

I noticed that there was no AZURE_COSMOSDB_ACCOUNT_KEY environment variable, though the other COSMOSDB variables were configured. I added it and manually copied the key, but it didn't change the behavior. The chat history button never appears.

**Comment by John-Vance** [comment]
Update: Actually it seems like manually adding the CosmosDB account key env variable did fix it, just had to give it a few.

**Comment by speedbunny** [comment]
Can confirm that re-adding the AZURE_COSMOSDB_ACCOUNT_KEY environment variable manually after syncing fixes the issue. Hopefully whatever is over-writing it can be fixed in future versions.

**Comment by abhahn** [comment]
@iseabock , could you take a look at the refactored settings code when you have time to see if you can repro this issue?

**Comment by aspexdata** [comment]
We also ran in to the same issue recently using Azure OpenAI Studio deployment across different models and regions. I can confirm this workaround of adding back AZURE_COSMOSDB_ACCOUNT_KEY env variable manually also helped to resolve the issue for us, and now able to see chat history again too on the UI. Thanks for sharing!

**Comment by sarah-widder** [comment]
Fixed by #915
