### ISSUE TITLE
Support for GPT4o

### ISSUE THREAD

**Issue by jimmyshah83** [microsoft/sample-app-aoai-chatGPT#898]
**Is your feature request related to this sample app, or to an Azure service, such as Azure OpenAI or Azure AI Search?**
Currently GPT4o API isn't supported and get a below error:
There was an error generating a response. Chat history can't be saved at this time. Request Header Fields Too Large

**Is your feature request related to a problem? Please describe.**
When I try to upgrade OpenAI to 1.30.5 and use the new API version of 2024-05-01-preview, it does not support GPT4o

**Describe the solution you'd like**
Have GPT4o as a supported model

**Describe alternatives you've considered**
Using GPT4-turbo with vision

**Comment by Francois2024** [comment]
Is this issue with the header and GPT-4o fixed? If so which commit is it? Thanks

**Comment by jimmyshah83** [comment]
Resolved
