### ISSUE TITLE
Could not enable SANITIZE_ANSWER in Citation Panel

### ISSUE THREAD

**Issue by karamem0** [microsoft/sample-app-aoai-chatGPT#916]
**Describe the bug**
I have the document with a link including parameters (e.g. `https://www.example.com&abc=123`). When I open the Citations Panel, the link is sanitized (e.g. `https://www.example.com&amp;abc=123`). I want to disable, but the SANITIZE_ANSWER parameter does not effect to Citations Panel.

**To Reproduce**
1. Prepare the document with a link `https://www.example.com&abc=123`.
2. Enable SANITIZE_ANSWER parameter.
3. Search the document.
4. Open Citations Panel.
5. The link is `https://www.example.com&amp;abc=123`

**Expected behavior**
The link should be `https://www.example.com&amp;abc=123`

**Screenshots**

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/4537204/f2bdd6a9-4820-4fa8-b1c4-64f8d3fd6a52)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version: **GPT-4o**
 - Is chat history enabled?: **No**
 - Are you using data? If so, what data source?: **Azure AI Search**

**Comment by sarah-widder** [comment]
Hi @karamem0 this should be fixed by #944
