### ISSUE TITLE
Issue in Frontend while testing on windows platform locally 

### ISSUE THREAD

**Issue by Owaiskhan9654** [microsoft/sample-app-aoai-chatGPT#92]
I encountered an error while attempting to set up a tool locally on a Windows platform. The error message "Failed to load resource: net::ERR_INVALID_CHUNKED_ENCODING" appeared in the console log when I used the "start.cmd" command to initiate the application locally.

Here's a screenshot of console log displaying the error:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/47840160/39fdfc90-40df-4bd2-84f9-0008e0bfab98)

I'm seeking assistance from the following users: @pamelafox @satarupaguha11 @sarah-widder @ruoccofabrizio.

If anyone has encountered this issue before or knows how to resolve it for windows platform locally, I would greatly appreciate your help and guidance. 

Thank you!

**Comment by sarah-widder** [comment]
Hi @Owaiskhan9654 can you share more details of your setup, if you changed anything in the code prior to running the command, your network setup, etc?

**Comment by Owaiskhan9654** [comment]
Thanks @sarah-widder for responding. I got this issue resolved by setting SHOULD_STREAM = False. 

https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/app.py#L53

In my local Windows machine, streaming doesn't seem to support by frontend module of this codebase. For local testing purposes, I have disabled the streaming for now. So closing this issue for now.

**Comment by pamelafox** [comment]
Interesting, I actually got that error today while debugging a related app. It often indicates your server had a runtime error that you can see in the logs. If you do attempt to bring back SHOULD_STREAM = true in the future and see that error again, check your Terminal logs to see if there are any runtime errors there.

**Comment by Owaiskhan9654** [comment]
I was not getting any logs related to this issue in my local Python terminal. Then I explored and went to the Chrome browser console and saw that error which is attached as a screenshot above. So since it was a local testing thing I set streaming as false. @pamelafox
