### ISSUE TITLE
Unable to cite more than 5 documents, only 5 citation references compiled at one time.

### ISSUE THREAD

**Issue by Prashantty** [microsoft/sample-app-aoai-chatGPT#922]
**Describe the bug**
Unable to cite more than 5 documents, 5 citation references compiled at one time.

**To Reproduce**

**Expected behavior**
Should load more than 5 documents, if there are more than 50 documents are uploaded.

**Screenshots**
![Screenshot 2024-06-13 152554](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/95084475/5368225e-6b8b-4f21-9b7e-ec77c2b3f0e5)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version (e.g. 'gpt-4o, 2024-02-15-preview"')
 - Is chat history enabled? Yes
 - Are you using data? If so, what data source? (e.g. Azure AI Search, Azure CosmosDB Mongo vCore, etc) -> Azure Blob Storage

**Additional context**
I uploaded more than 50 documents including doc, docs, and pdf files, but at one time it only provided 5 citation references and displayed the message "please ensure that all documents are reviewed and compiled together."

**Comment by sarah-widder** [comment]
Hi @Prashantty, this behavior is controlled by the AZURE_SEARCH_TOP_K app setting, which you can modify in the Environment Variables page on your app service. For more information, check out the documentation here: https://learn.microsoft.com/en-us/azure/ai-services/openai/references/azure-search?tabs=python

**Comment by Prashantty** [comment]
Thanks @sarah-widder
