### ISSUE TITLE
web app deployment failed with error "ResourceDeploymentFailure"

### ISSUE THREAD

**Issue by immafrank** [microsoft/sample-app-aoai-chatGPT#931]
I tried deploying an Azure web app from the Azure Open AI studio playground but i am getting this error even after multiple trials.

![2](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/82779790/738e7b4e-bc4a-4063-ae17-58e41b7a8ea9)
![1](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/82779790/5724174f-d277-4105-a49a-086d89df7f08)

Web App resource deployment failed
{ "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'." } }

**Comment by abhahn** [comment]
Hey @davidm00 , this looks somewhat similar to an issue you were previously working on.  Just wanted to ask if you have any insight into this that you can share here.

**Comment by abhahn** [comment]
Hi @immafrank , just to give a quick follow up: this is a known issue that is currently being investigated by our team.  I will provide an update here once the root cause is determined.
