### ISSUE TITLE
Cannot use a deployed prompt flow in web app

### ISSUE THREAD

**Issue by Tanishk1** [microsoft/sample-app-aoai-chatGPT#934]
When I set the below environment variables to use a deployed prompt flow, it doesn't work in the web app as the web app is deployed normally as if it ignores these specific environment variables (other environment variables work). Is there anything else I need to do for my prompt flow to work?

# Chat with data: Prompt flow API
USE_PROMPTFLOW=True
PROMPTFLOW_ENDPOINT=redacted
PROMPTFLOW_API_KEY=redacted
PROMPTFLOW_RESPONSE_TIMEOUT=120
PROMPTFLOW_REQUEST_FIELD_NAME=query
PROMPTFLOW_RESPONSE_FIELD_NAME=reply
PROMPTFLOW_CITATIONS_FIELD_NAME=documents

**Comment by DOliana** [comment]
Hi @Tanishk1. I had the same issue and the reason is that promptflow is not used when AZURE_OPENAI_STREAM is set to true. set this to false and prompt flow will be used. (I am preparing a PR to fix this)

**Comment by abhahn** [comment]
Hi @Tanishk1 , I have just merged @DOliana 's PR.  Can you check to see if this solves your issue?
