### ISSUE TITLE
Creating an index using files with .docx and .pptx extensions

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#94]
Hi
When trying to create the index (using the command: python data_preparation.py --config config.json --njobs=4) using .docx and .pptx files, the following message appears:
raise Exception("No chunks found. Please check the data path and chunk size.")
Are the scripts prepared to create index with these types of files?

**Comment by pamelafox** [comment]
You can see the supported file formats here:
https://github.com/microsoft/sample-app-aoai-chatGPT/blob/7128fa0b683e9c6e921cd049cda157b0b0f6dd1d/scripts/data_utils.py#L21
It looks like docx and pptx are not currently supported.

There's some discussion about other formats in the similar repo in this issue https://github.com/Azure-Samples/azure-search-openai-demo/issues/181 but it doesn't look like anyone's succeeded there. It seems possible Form Recognizer could parse them, with some changes to the script.

**Comment by pamelafox** [comment]
I realize this is the same request as the earlier request https://github.com/microsoft/sample-app-aoai-chatGPT/issues/71 so I'll close this issue so we can keep the discussion in one place.
