### ISSUE TITLE
Support for gpt-4o multimodality

### ISSUE THREAD

**Issue by michirem** [microsoft/sample-app-aoai-chatGPT#945]
**Is your feature request related to this sample app, or to an Azure service, such as Azure OpenAI or Azure AI Search?**
Sample app

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to generate images or get answers on file uploads of text files, pdfs or images using the main input field.

**Is this feature specific to your use case or your organization, or would it apply broadly across other uses of this app?**
This would enable all gpt-4o features for all users of the sample app.

**Describe alternatives you've considered**
Currently, there is no alternative that is so easily deployable on Azure.

**Additional context**
None.

**Comment by koichino** [comment]
Hi @michirem Can I know the current status? It will great If this enhancement is implemented. If you have any timeline on thid, please update us.
