### ISSUE TITLE
Error in cognitive search with gpt-35-turbo-16k model

### ISSUE THREAD

**Issue by akashtalole** [microsoft/sample-app-aoai-chatGPT#98]
Getting below error 
`Invalid AzureCognitiveSearch configuration detected: 403 Client Error: Forbidden for url: https://mysearch.search.windows.net/indexes/mykb?api-version=2021-04-30-Preview`

when i checked in cogintive search explorer url shows like
`https://mysearch.search.windows.net/indexes/mykb/docs?api-version=2021-04-30-Preview`

**Comment by pamelafox** [comment]
Are you getting that error when running locally or when deployed?

**Comment by akashtalole** [comment]
I am getting this error while running locally when i ask question with data.

**Comment by akashtalole** [comment]
Yes I have set these parameters correctly

**Comment by superpoussin22** [comment]
GPT-65-turbo-16k is unstable for me , it was at one moment removed from some region

**Comment by sarah-widder** [comment]
@akashtalole are you using an admin key for AZURE_SEARCH_KEY? A regular query key is insufficient.

**Comment by akashtalole** [comment]
Yes using admin key for search.
